### ISSUE TITLE
grpc addresses that don't have http(s) prefix don't work

### ISSUE THREAD

**Issue by rparvizian-rbx** [grpc/grpc-dotnet#1022]
### What version of gRPC and what language are you using?
2.31.0 (latest)

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
Asp .NET core  Version:   3.1.401

### What did you do?
The following doesn't work:
```c#
using var channel = GrpcChannel.ForAddress("some.address:82");
var client = new MyService.MyServiceClient(channel);
var callServiceAsync = client.CallServiceAsync(request);
```
fails.
`some.address` isn't the real address I used. I'm obfuscating the actual address I called. Adding `http://` in front of the address doesn't work either (with a different exception).

### What did you expect to see?
It seems grpc-dotnet doesn't like that the address doesn't start with http(s). I tried to make a similar call with [Grpc.Core](https://www.nuget.org/packages/Grpc.Core):
```c#
_channel = new Channel(target, credentials);
_client = new MyService.MyServiceClient(_channel);
```
 and it worked fine.

### What did you see instead?
This exception:
```
System.ArgumentException: Only 'http' and 'https' schemes are allowed. (Parameter 'requestUri')
   at System.Net.Http.HttpRequestMessage.InitializeValues(HttpMethod method, Uri requestUri)
   at System.Net.Http.HttpRequestMessage..ctor(HttpMethod method, Uri requestUri)
   at Grpc.Net.Client.Internal.GrpcCall`2.CreateHttpRequestMessage(Nullable`1 timeout)
   at Grpc.Net.Client.Internal.GrpcCall`2.StartUnary(TRequest request)
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<AsyncUnaryCall>b__4_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.AsyncUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, AsyncUnaryCallCon
tinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
```

Considering the same address works with Grpc.Core, I suspect this is a bug in grpc-dotnet.

**Comment by JamesNK** [comment]
This isn't a bug, it is a design decision. `GrpcChannel.ForAddress` uses http or https to determine whether the gRPC call uses TLS or not.

**Comment by rparvizian-rbx** [comment]
So how do I solve this issue? Do I have to use grpc-core instead?

**Comment by JamesNK** [comment]
If you want to call a http endpoint then prefix with http, if you want to call a https endpoint then prefix with https. If neither then you'll need to use Grpc.Core.
