### ISSUE TITLE
PROTOCOL_ERROR after upgrading to .NET5

### ISSUE THREAD

**Issue by sjohag** [grpc/grpc-dotnet#1091]
I am getting this error when using .NET5.0 (RC 2) and Grpc.Net.Client.Web 2.33.1-pre1:

Grpc.Core.RpcException
  HResult=0x80131500
  Message=Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Error while copying content to a stream. IOException: The request was aborted. Http2ConnectionException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1).", DebugException="System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: The request was aborted.
 ---> System.Net.Http.Http2ConnectionException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1).
   at System.Net.Http.Http2Connection.ThrowProtocolError(Http2ProtocolErrorCode errorCode)
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()

The endpoint I am calling (from a console application) is a grpc-web hosted on IIS (backend of a Blazor WASM application).
Calling the exact same endpoint, but using .NET Core 3.1 and 2.32.0 in the console application works fine, application unchanged.

I am using this code to register the client (baseUri set outside).
services.AddSingleton(services =>
{
    var httpClient = new HttpClient(new GrpcWebHandler(GrpcWebMode.GrpcWeb, new HttpClientHandler()));
    var channel = GrpcChannel.ForAddress(baseUri, new GrpcChannelOptions { HttpClient = httpClient });
    return new BatchGrpc.BatchGrpcClient(channel);
});

Setting a breakpoint before returning and inspecting httpclient shows DefaultRequestVersion = 1.1 and DefaultRequestVersionPolicy=RequestVersionOrLower.
But it seems like the request is done using HTTP/2.

Any suggestions?

**Comment by sjohag** [comment]
Problem solved, int was not a bug, but a change in behavior.
The service is configured with "app.UseHttpsRedirection();", but I used an http-address instead of https when the channel was created.
With the .NET Core 3.1 version that works well, but not with the .NET 5 version.
Somewhere there is a difference in behavior in the handling of redirection.
