### ISSUE TITLE
gRPC calls fail with Azure AppService

### ISSUE THREAD

**Issue by koppa96** [grpc/grpc-dotnet#1115]
### What version of gRPC and what language are you using?
2.33.1 with C#

### What operating system (Linux, Windows,...) and version?
Windows on the client, Linux on the server

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET 5.0.100

### What did you do?
We created a server and client app that communicate with each other through gRPC.

### What did you expect to see?
The applications should work both in local and on Azure.

### What did you see instead?
The applications work as expected when launched on the developer computers locally. However when the server is ran on Azure in linux containers, we got the following errors at each gRPC call:
```
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while server offers only version fallback.", DebugException="System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while server offers only version fallback.
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
   ... // The invoking code's stack trace
```

This error message should be pretty straightforward to solve, as we looked into the configuration of the webapp on Azure, and it is indeed configured to use HTTP/1.1. So we set the app on Azure to use HTTP/2, but after setting it to HTTP/2 we get the following error message from the client:
```
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Request protocol 'HTTP/1.1' is not supported.")
```

I have also tried playing with the Kestrel server's HTTP Protocol settings, attempting to reproduce the issue locally. When the server was set Http1AndHttp2 / Http2 mode, the calls worked fine, in Http1 mode I received the following error:
```
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: The SSL connection could not be established, see inner exception. AuthenticationException: Authentication failed, see inner exception. Win32Exception: Nincs olyan alkalmazásprotokoll, amelyet az ügyfél és a kiszolgáló is használni tudna. Nem sikerült az alkalmazásprotokoll egyeztetése.", DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090367): Nincs olyan alkalmazásprotokoll, amelyet az ügyfél és a kiszolgáló is használni tudna. Nem sikerült az alkalmazásprotokoll egyeztetése.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
```
The exception message is in Hungarian because of my Windows' language settings, it vaguely means that "There is no application protocol that could be used by the client and the server. The negotiation of the application protocol was unsuccessful". So it clearly isn't supposed to work in HTTP/1, but work with HTTP/2, I just do not understand why I'm getting the 
"Request protocol 'HTTP/1.1' is not supported." error when the AppService is set to HTTP/2 mode if Http2 only mode works fine on my machine.

On the server side the services are registered well:
```csharp
// ConfigureServices
services.AddGrpc(options =>
{
    options.Interceptors.Add<RequestLoggerInterceptor>();
    options.EnableDetailedErrors = true;
});

// Configure
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
    endpoints.MapGrpcService<MyService>();
    endpoints.MapGrpcService<MyOtherService>();
});
```

The creation of a client looks like this:
```csharp
public MyService.MyServiceClient CreateMyServiceClient()
{
    if (syncChannel == null)
    {
        var credentials = CallCredentials.FromInterceptor(async (context, metadata) =>
        {
            metadata.Add("Authorization", $"Bearer {clientCredentialsFlowAuthService.AccessToken}");
        });

        syncChannel = GrpcChannel.ForAddress(configuration.GetValue<string>("ApiBaseUrl"), new GrpcChannelOptions
        {
            Credentials = ChannelCredentials.Create(new SslCredentials(), credentials)
        });
    }

    return new MyService.MyServiceClient(syncChannel);
}
```

**Comment by shirhatti** [comment]
gRPC is currently not supported on App Services due to known limitations in Http/2. In the interim, you may want to use gRPC-web: https://docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-5.0

**Comment by JunTaoLuo** [comment]
The question has been answered so I'm closing the issue.
