### ISSUE TITLE
What am i missing?

### ISSUE THREAD

**Issue by Roneri75** [grpc/grpc-dotnet#1126]
Hi

I downloaded the full project.
Opened the Blazor solusion in the Examples in VS 2019 (lastest update of today).
Built it without problem but it does not work when running it...
I get this in the browser:
POST https://localhost:5001/count.Counter/StartCounter net::ERR_CONNECTION_REFUSED
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: TypeError: Failed to fetch", DebugException="System.Net.Http.HttpRequestException: TypeError: Failed to fetch
         at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Grpc.Net.Client.Web.GrpcWebHandler.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
         at Grpc.Net.Client.Internal.GrpcCall`2.<RunCall>d__66[[Count.CounterRequest, Client, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad],[Count.CounterResponse, Client, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad]].MoveNext()")
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: TypeError: Failed to fetch", DebugException="System.Net.Http.HttpRequestException: TypeError: Failed to fetch
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Web.GrpcWebHandler.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.<RunCall>d__66[[Count.CounterRequest, Client, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad],[Count.CounterResponse, Client, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad]].MoveNext()")
   at Grpc.Net.Client.Internal.HttpContentClientStreamReader`2.<MoveNextCore>d__19[[Count.CounterRequest, Client, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad],[Count.CounterResponse, Client, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad]].MoveNext()
   at Grpc.Core.AsyncStreamReaderExtensions.<ReadAllAsyncCore>d__1`1[[Count.CounterResponse, Client, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad]].MoveNext()
   at Grpc.Core.AsyncStreamReaderExtensions.<ReadAllAsyncCore>d__1`1[[Count.CounterResponse, Client, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad]].System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at Client.Pages.Counter.IncrementCount() in C:\Users\RonnyEriksson\Documents\GitHub\grpc-dotnet\examples\Blazor\Client\Pages\Counter.razor:line 31
   at Client.Pages.Counter.IncrementCount() in C:\Users\RonnyEriksson\Documents\GitHub\grpc-dotnet\examples\Blazor\Client\Pages\Counter.razor:line 31
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by JamesNK** [comment]
I'm not sure.

Check that you run the Server project. Running the Client project will start the Blazor app but there won't be any gRPC services to call.

**Comment by Roneri75** [comment]
I've tested running the Client and server projects in multiple different ways in VS and i just keep getting the same problem.
The PC I'm testing this on is about a month old, so there should not be any strange configurations or anything, like network settings or firewall settings or alike, there might be something missing regarding installations but i can't figure out what, since every project on my old PC works on my new PC.
if you test this Blazor project on lets say a freshly installed windows like a virtual pc in VS 2019, does it work just like on your PC where it works?
Way I'm asking all this is that i got the same problem in my Blazor project when I test gRPC just like it is set up in your Blazor project, since i wanted to see the different between something that worked and compare it to my project and see what I was missing or did differently.

**Comment by JamesNK** [comment]
I'm not sure why it doesn't work on your computer.

The sample is deployed at https://grpcblazor.azurewebsites.net/ - Does it work for you?

**Comment by Roneri75** [comment]
Yes it does.

**Comment by Roneri75** [comment]
Does gRPC not work with IIS Express that VS by default is using?
Do i have to deploy the solution to my local IIS for it to work?
Because gRPC should work with IIS 10 on Windows 10 right?
Can that be it and that there is some bug in IIS Express or a setting in IIS Express i'm missing?

**Comment by JamesNK** [comment]
Ok, you're launching the site in IIS Express. Look at the website port. Now look at the port in the error message that the gRPC call is being made to. They don't match. You need to update the appsettings.json to have a port that matches the IIS Express website.

**Comment by Roneri75** [comment]
Okay that sounds logical.
So exactly what should i put in the appsetting?
I've just started looking in to gRPC and i'm pretty new at Blazor so i have no ide what to put in to the appsettings to get the gRPC on the correct port.
I currently only have this in the server appsettings:
{
  "Logging": {
    "LogLevel": {
      "Default": "Information"
    }
  },
  "AllowedHosts": "*"
}

**Comment by JamesNK** [comment]
https://github.com/grpc/grpc-dotnet/blob/master/examples/Blazor/Client/wwwroot/appsettings.json

**Comment by Roneri75** [comment]
Okay i was just stupid...
It was in the client appsettings, i didn't realise that it was located in the www folder.
I did read that you added the "backendUrl" in the appsettings somewhere else in some other issue but i just didn't realize that it was in the client.
That solve my problem.
Thanks so much for the help, and thanks for the create examples you put out, it really helps.
Keep the good work up!!!
