### ISSUE TITLE
Status(StatusCode="Cancelled", Detail="No grpc-status found on response.")

### ISSUE THREAD

**Issue by ikaccc** [grpc/grpc-dotnet#1164]
StackTrace:
```
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter``1.GetResult()
   at Web.WidgetManagement.HttpAggregator.Services.WidgetService.<<GetAppliedWidgetsAsync>b__4_0>d.MoveNext() in C:\Users\ivan.cekov\source\repos\Admin-v6-Services\ApiGateways\Web.WidgetManagement.HttpAggregator\Services\WidgetService.cs:line 36
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter``1.GetResult()
   at Web.WidgetManagement.HttpAggregator.Services.GrpcCallerService.<CallService>d__0``1.MoveNext() in C:\Users\ivan.cekov\source\repos\Admin-v6-Services\ApiGateways\Web.WidgetManagement.HttpAggregator\Services\GrpcCallerService.cs:line 38
```

client
WidgetService.cs
```
//_urls.GrpcWidget = https://localhost:5051
 public async Task<IEnumerable<WidgetData>> GetAppliedWidgetsAsync()
        {
            try
            {
                var res = await GrpcCallerService.CallService(_urls.GrpcWidget, async channel =>
                {
                    var client = new WidgetManager.API.Protos.WidgetManagement.WidgetManagementClient(channel);
                    _logger.LogDebug("grpc client created, GetAppliedWidgets");
                    var response = await client.GetAppliedWidgetsAsync(new Empty { });
                    _logger.LogDebug("grpc response {@response}", response);

                    return MapToWidgetData(response);
                });
                return res;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return null;
        }
```

GrpcCallerService.cs
```
public static class GrpcCallerService
    {
        public static async Task<TResponse> CallService<TResponse>(string urlGrpc, Func<GrpcChannel, Task<TResponse>> func)
        {
            AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
            AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2Support", true);
            var channel = GrpcChannel.ForAddress(urlGrpc);

            Log.Information("Creating grpc client base address urlGrpc ={@urlGrpc}, BaseAddress={@BaseAddress} ", urlGrpc, channel.Target);

            try
            {
                return await func(channel);
            }
            catch (RpcException e)
            {
                Log.Error("Error calling via grpc: {Status} - {Message}", e.Status, e.Message);
                return default;
            }
            finally
            {
                AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", false);
                AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2Support", false);
            }
        }
```

The issue appears when grpc server returns data to the client.

Environment details
OS: Windows 10
Package name and version: .NET Core v3.1.7 & Grpc.Core 2.31.0 & protobuf-net 3.13.0

**Comment by jtattermusch** [comment]
Btw the "No grpc-status found on response seem to indicate that HTTP/2 is not really being used (the grpc-status is send as a HTTP/2 trailer and should always be present, but HTTP1.1 doesn't support trailers).

**Comment by BrennanConroy** [comment]
> Btw the "No grpc-status found on response seem to indicate that HTTP/2 is not really being used (the grpc-status is send as a HTTP/2 trailer and should always be present, but HTTP1.1 doesn't support trailers).

@ikaccc Can you confirm if you're using HTTP/2? Also, could you try moving to net5.0?

**Comment by JamesNK** [comment]
Closing because of inactivity.

**Comment by forconz** [comment]
> > Btw the "No grpc-status found on response seem to indicate that HTTP/2 is not really being used (the grpc-status is send as a HTTP/2 trailer and should always be present, but HTTP1.1 doesn't support trailers).
> 
> @ikaccc Can you confirm if you're using HTTP/2? Also, could you try moving to net5.0?

I use .net 5.0 and http/2, but Grpc.Core.RpcException:“Status(StatusCode="Cancelled", Detail="No grpc-status found on response.")”

I added code blow
.WithExposedHeaders("Grpc-Status", "Grpc-Message", "Grpc-Encoding", "Grpc-Accept-Encoding");
but the exception was Grpc.Core.RpcException:“Status(StatusCode="Cancelled", Detail="No grpc-status found on response.")”

**Comment by mashood05** [comment]
![image](https://user-images.githubusercontent.com/28581688/176143194-5cf687be-191b-4028-aaff-cd5f15c75144.png)
Solution for my Prob

**Comment by zachrybaker** [comment]
This issue also occurs with a .Net 4.6 client attempting to use the WinHttpHandler.

`
                channel = GrpcChannel.ForAddress("https://localhost:10443", new GrpcChannelOptions
                {
                    HttpHandler = new System.Net.Http.WinHttpHandler()
                });
`

**Comment by brainiac005** [comment]
> ![image](https://user-images.githubusercontent.com/28581688/176143194-5cf687be-191b-4028-aaff-cd5f15c75144.png) Solution for my Prob

This Solves my issue

**Comment by vir2oz4y** [comment]
I had this error when using it.net 4.7.2 client and .net 8 server. After migrating the client to .net 8, the error disappeared
