### ISSUE TITLE
StatusCode="Unavailable" even  with option WithWaitForReady()

### ISSUE THREAD

**Issue by netcorefan1** [grpc/grpc-dotnet#1175]
.Net 5

Hello,
I am trying the transporter sample and I am having troubles. 
I launch the server directly from VS (with a call to Process.Run) and execute the client code, but I get immediately an RpcException of type "Unavailable". I tried to add WithWaitForReady(), but without effect:
`var resp = await client.SayHelloAsync(new HelloRequest {Name = "World"}, new CallOptions().WithWaitForReady());`
The only way I have been able to make it work is with a rude loop containing a "Thread.Sleep(1000)" in order to wait service availability, but as soon as I try to decrease the waiting time, the exceptions returns.

I also tried to play with GetStatus(), but I have gone in the same problem. As soon as I tried to decrease the waiting time I get "Unable to get the status because the call is not complete".

I also noticed that the ConnectAsync() in UnixDomainSocketConnectionFactory.cs contains a try catch block and I am not sure if this also plays some role.

I was hoping that the library contained an automatic mechanism to handle this without recurring to manually writing loops which introduce unpredictable results.
Is there something obvious that I am missing?

**Comment by JamesNK** [comment]
What operating system and version are you using? On Windows UDS only works with modern versions.

There isn't enough information to understand what is going on. Please add logs from the client and server. More info - https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-5.0

**Comment by netcorefan1** [comment]
Thanks for your help! I have the latest build of Windows 10 Pro, .Net 5.
So, from what I understand, if the service is not yet "on line", the client will wait until becomes ready without anything needed from my side.
Below is the full debug log.

START!
dbug: Grpc.Net.Client.Internal.GrpcCall[1]
      Starting gRPC call. Method type: 'Unary', URI: 'http://localhost/greet.Greeter/SayHello'.
dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
fail: Grpc.Net.Client.Internal.GrpcCall[6]
      Error starting gRPC call.
      System.Net.Http.HttpRequestException: Error connecting to 'C:\Users\user\AppData\Local\Temp\grpc-transporter.tmp'. (localhost:80)
       ---> System.Net.Http.HttpRequestException: Error connecting to 'C:\Users\user\AppData\Local\Temp\grpc-transporter.tmp'.
       ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
         at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
         at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, EndPoint remoteEP, CancellationToken cancellationToken)
         at Client.UnixDomainSocketConnectionFactory.ConnectAsync(SocketsHttpConnectionContext _, CancellationToken cancellationToken) in C:\Users\user\source\repos\Temp\2021-01-14\grpc-dotnet-examples\Transporter\Client\UnixDomainSocketConnectionFactory.cs:line 82
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Client.UnixDomainSocketConnectionFactory.ConnectAsync(SocketsHttpConnectionContext _, CancellationToken cancellationToken)
         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithProxyAuthAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPoolManager.SendAsyncCore(HttpRequestMessage request, Uri proxyUri, Boolean async, Boolean doRequestAuth, Boolean isProxyConnect, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPoolManager.SendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpMessageHandlerStage.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.SocketsHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Grpc.Shared.TelemetryHeaderHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
         at Grpc.Net.Client.Internal.GrpcCall`2.StartUnary(TRequest request)
         at Grpc.Net.Client.Internal.HttpClientCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
         at Grpc.Core.Interceptors.InterceptingCallInvoker.<AsyncUnaryCall>b__4_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
         at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.AsyncUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, AsyncUnaryCallContinuation`2 continuation)
         at Grpc.Core.Interceptors.InterceptingCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
         at Greet.Greeter.GreeterClient.SayHelloAsync(HelloRequest request, CallOptions options) in C:\Users\user\source\repos\Temp\2021-01-14\grpc-dotnet-examples\Transporter\Client\obj\Release\net5.0\GreetGrpc.cs:line 144
         at Client.Program.Main(String[] args) in C:\Users\user\source\repos\Temp\2021-01-14\grpc-dotnet-examples\Transporter\Client\Program.cs:line 63
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Client.Program.Main(String[] args)
         at Client.Program.<Main>(String[] args)
      --- End of stack trace from previous location ---
         at Client.UnixDomainSocketConnectionFactory.ConnectAsync(SocketsHttpConnectionContext _, CancellationToken cancellationToken) in C:\Users\user\source\repos\Temp\2021-01-14\grpc-dotnet-examples\Transporter\Client\UnixDomainSocketConnectionFactory.cs:line 82
         --- End of inner exception stack trace ---
         at Client.UnixDomainSocketConnectionFactory.ConnectAsync(SocketsHttpConnectionContext _, CancellationToken cancellationToken) in C:\Users\user\source\repos\Temp\2021-01-14\grpc-dotnet-examples\Transporter\Client\UnixDomainSocketConnectionFactory.cs:line 88
         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPoolUnhandled exception. .SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: Error connecting to 'C:\Users\user\AppData\Local\Temp\grpc-transporter.tmp'. (localhost:80) HttpRequestException: Error connecting to 'C:\Users\user\AppData\Local\Temp\grpc-transporter.tmp'. SocketException: No connection could be made because the target machine actively refused it.", DebugException="System.Net.Http.HttpRequestException: Error connecting to 'C:\Users\user\AppData\Local\Temp\grpc-transporter.tmp'. (localhost:80)
 ---> System.Net.Http.HttpRequestException: Error connecting to 'C:\Users\user\AppData\Local\Temp\grpc-transporter.tmp'.
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, EndPoint remoteEP, CancellationToken cancellationToken)
   at Client.UnixDomainSocketConnectionFactory.ConnectAsync(SocketsHttpConnectionContext _, CancellationToken cancellationToken) in C:\Users\user\source\repos\Temp\2021-01-14\grpc-dotnet-examples\Transporter\Client\UnixDomainSocketConnectionFactory.cs:line 82
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Client.UnixDomainSocketConnectionFactory.ConnectAsync(SocketsHttpConnectionContext _, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithProxyAuthAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPoolManager.SendAsyncCore(HttpRequestMessage request, Uri proxyUri, Boolean async, Boolean doRequestAuth, Boolean isProxyConnect, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPoolManager.SendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Shared.TelemetryHeaderHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
   at Grpc.Net.Client.Internal.GrpcCall`2.StartUnary(TRequest request)
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<AsyncUnaryCall>b__4_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.AsyncUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, AsyncUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Greet.Greeter.GreeterClient.SayHelloAsync(HelloRequest request, CallOptions options) in C:\Users\user\source\repos\Temp\2021-01-14\grpc-dotnet-examples\Transporter\Client\obj\Release\net5.0\GreetGrpc.cs:line 144
   at Client.Program.Main(String[] args) in C:\Users\user\source\repos\Temp\2021-01-14\grpc-dotnet-examples\Transporter\Client\Program.cs:line 63
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Client.Program.Main(String[] args)
   at Client.Program.<Main>(String[] args)
--- End of stack trace from previous location ---
   at Client.UnixDomainSocketConnectionFactory.ConnectAsync(SocketsHttpConnectionContext _, CancellationToken cancellationToken) in C:\Users\user\source\repos\Temp\2021-01-14\grpc-dotnet-examples\Transporter\Client\UnixDomainSocketConnectionFactory.cs:line 82
   --- End of inner exception stack trace ---
   at Client.UnixDomainSocketConnectionFactory.ConnectAsync(SocketsHttpConnectionContext _, CancellationToken cancellationToken) in C:\Users\user\source\repos\Temp\2021-01-14\grpc-dotnet-examples\Transporter\Client\UnixDomainSocketConnectionFactory.cs:line 88
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
   at Client.Program.Main(String[] args) in C:\Users\user\source\repos\Temp\2021-01-14\grpc-dotnet-examples\Transporter\Client\Program.cs:line 63
   at Client.Program.<Main>(String[] args)
info: Grpc.Net.Client.Internal.GrpcCall[3]
      Call failed with gRPC error status. Status code: 'Unavailable', Message: 'Error starting gRPC call. HttpRequestException: Error connecting to 'C:\Users\user\AppData\Local\Temp\grpc-transporter.tmp'. (localhost:80) HttpRequestException: Error connecting to 'C:\Users\user\AppData\Local\Temp\grpc-transporter.tmp'. SocketException: No connection could be made because the target machine actively refused it.'.
dbug: Grpc.Net.Client.Internal.GrpcCall[4]
      Finished gRPC call.
dbug: Grpc.Net.Client.Internal.GrpcCall[8]
      gRPC call canceled.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://unix:C:\Users\user\AppData\Local\Temp\grpc-transporter.tmp
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[0]
      Loaded hosting startup assembly Server
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\user\source\repos\Temp\2021-01-14\grpc-dotnet-examples\Transporter\Server\bin\Release\net5.0
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
Press any key to continue . . .

**Comment by JamesNK** [comment]
I'm not sure. The server and client have the same UDS address, but the client is getting a message that the connection was refused, and there is no record of the connection on the server.

**Comment by netcorefan1** [comment]
I attached a sample project (which basically is the same Greeter sample) where you can observe the connection failure despite WithWaitForReady(). In the client side there is a rude `Thread.Sleep(2000)`.  Uncomment this line to observe the successful connection.
[Transporter.zip](https://github.com/grpc/grpc-dotnet/files/5927581/Transporter.zip)

**Comment by JamesNK** [comment]
Ah, I see what you mean.

Grpc.Net.Client currently doesn't support `WaitForReady` or gRPC calls or `Channel.ConnectAsync`. They're useful features so I'll create an issue for supporting them.

**Comment by JamesNK** [comment]
Feature issue: https://github.com/grpc/grpc-dotnet/issues/1190

**Comment by netcorefan1** [comment]
Thanks. For now the only safe workaround is sleeping for the time I could expect the server to be online with its worse delay. Trying to reduce waiting time with polling generate bad exceptions on sockets and elsewhere. You can see my attempts in the commented code on `UnixDomainSocketConnectionFactory.cs`
Thanks for opening the feature issue.
Unless you have further questions, I will close this issue.
