### ISSUE TITLE
Unexpected end of content when streaming large message over slow connection

### ISSUE THREAD

**Issue by ThorstenReichert** [grpc/grpc-dotnet#1224]
### What version of gRPC and what language are you using?
Language: C#
Grpc.AspNetCore 2.35.0
Grpc.Net.Client: 2.35.0
Grpc.Tools: 2.36.1
Google.Protobuf: 3.15.5

### What operating system (Linux, Windows,...) and version?
Server: Windows Server 1809
Client: Windows 10

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
Server: netcoreapp3.1
Client: netcoreapp3.1

### What did you do?
We have a bi-directional streaming call (the only call being made at all), with an implementation as follows:
```csharp
public override async Task StartSimulation(
    IAsyncStreamReader<SimulationRequest> requestStream,
    IServerStreamWriter<SimulationResponse> responseStream,
    ServerCallContext context)
{
    // Client sends some requests.
    // Client calls CompleteAsync().

    // Server sends some responses

    var finalResponse = /* create a large protobuf message */;

    await responseStream.WriteAsync(finalResponse);
}
```
While the first responses are rather small (short strings), the `finalResponse` includes a binary blob of around 1-2MB (note, all message size limits on server and client have been disabled).

On the client, we simply consume responses via:
```csharp
while(await responseStream.MoveNext()) 
{
    // Use responseStream.Current
}
```

### What did you expect to see?
Expected to receive the `finalResponse` when consuming the responses client-side.

### What did you see instead?
On a fast connection to the server (client and server in the same network), everything works as expected.
On a slow connection (client remote, via VPN), the `finalResponse` is never received, instead we receive an `RpcException`
```csharp
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error reading next message. InvalidDataException: Unexpected end of content while reading the message content.", DebugException="System.IO.InvalidDataException: Unexpected end of content while reading the message content.
   at Grpc.Net.Client.StreamExtensions.ReadMessageContent(Stream responseStream, Memory`1 messageData, Int32 length, CancellationToken cancellationToken)
   at Grpc.Net.Client.StreamExtensions.ReadMessageAsync[TResponse](Stream responseStream, GrpcCall call, Func`2 deserializer, String grpcEncoding, Boolean singleMessage, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.HttpContentClientStreamReader`2.MoveNextCore(CancellationToken cancellationToken)")
   at Grpc.Net.Client.Internal.HttpContentClientStreamReader`2.MoveNextCore(CancellationToken cancellationToken)
```
The messages before the last one are received just fine, though.
Interestingly, when we modify the implementation of the streaming call to
```csharp
    // ...
    var finalResponse = /* ... */;

    await await responseStream.WriteAsync(finalResponse);
    await Task.Delay(TimeSpan.FromSeconds(2));
}
```
then everything works as expected also for the slow connection. However, by moving the delay one line further up, i.e.
```csharp
    // ...
    var finalResponse = /* ... */;

    await Task.Delay(TimeSpan.FromSeconds(2));
    await await responseStream.WriteAsync(finalResponse);
}
```
the issue reproduces again.

### Anything else we should know about your project / environment?
We tried settings the gRPC loglevel to "Debug", but the output appears to be identical in both cases. Nonetheless, here is the log for the slow-connection case (let me know if I should include the log for the other case as well):

```
2021-03-08 14:11:30.9982;Info;Now listening on: http://0.0.0.0:5000;<servername>;13876;;1;Microsoft.Hosting.Lifetime;
2021-03-08 14:11:30.9982;Info;Application started. Press Ctrl+C to shut down.;<servername>;13876;;1;Microsoft.Hosting.Lifetime;
2021-03-08 14:11:30.9982;Info;Hosting environment: Production;<servername>;13876;;1;Microsoft.Hosting.Lifetime;
2021-03-08 14:11:52.1704;Debug;Reading message.;<servername>;13876;;12;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:11:52.1853;Debug;Reading message.;<servername>;13876;;12;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:11:52.8852;Debug;Reading message.;<servername>;13876;;15;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:11:53.1803;Debug;Reading message.;<servername>;13876;;8;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:11:53.4048;Debug;Reading message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:11:54.2278;Debug;Reading message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:11:54.9595;Debug;Reading message.;<servername>;13876;;12;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:11:55.6174;Debug;Reading message.;<servername>;13876;;14;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:11:56.2698;Debug;Reading message.;<servername>;13876;;8;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:11:57.0672;Debug;Reading message.;<servername>;13876;;12;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:11:57.7343;Debug;Reading message.;<servername>;13876;;16;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:11:58.4637;Debug;Reading message.;<servername>;13876;;12;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:11:58.9603;Debug;Reading message.;<servername>;13876;;16;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:11:59.4491;Debug;Reading message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:11:59.9251;Debug;Reading message.;<servername>;13876;;16;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:00.4121;Debug;Reading message.;<servername>;13876;;10;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:01.0839;Debug;Reading message.;<servername>;13876;;12;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:01.5880;Debug;Reading message.;<servername>;13876;;18;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:02.0574;Debug;Reading message.;<servername>;13876;;18;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:02.5614;Debug;Reading message.;<servername>;13876;;12;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:03.0388;Debug;Reading message.;<servername>;13876;;18;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:03.4990;Debug;Reading message.;<servername>;13876;;17;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:03.9837;Debug;Reading message.;<servername>;13876;;14;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:04.4445;Debug;Reading message.;<servername>;13876;;10;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:04.9504;Debug;Reading message.;<servername>;13876;;8;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:05.4332;Debug;Reading message.;<servername>;13876;;16;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:05.9375;Debug;Reading message.;<servername>;13876;;18;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:06.3971;Debug;Reading message.;<servername>;13876;;16;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:06.8701;Debug;Reading message.;<servername>;13876;;16;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:07.3729;Debug;Reading message.;<servername>;13876;;16;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:07.8580;Debug;Reading message.;<servername>;13876;;14;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:08.3325;Debug;Reading message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:08.8145;Debug;Reading message.;<servername>;13876;;10;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:09.2928;Debug;Reading message.;<servername>;13876;;20;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:09.7716;Debug;Reading message.;<servername>;13876;;15;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:10.2351;Debug;Reading message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:10.7013;Debug;Reading message.;<servername>;13876;;17;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:11.1803;Debug;Reading message.;<servername>;13876;;17;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:11.6495;Debug;Reading message.;<servername>;13876;;15;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:12.1399;Debug;Reading message.;<servername>;13876;;17;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:12.6193;Debug;Reading message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:13.0896;Debug;Reading message.;<servername>;13876;;12;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:13.5585;Debug;Reading message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:14.0201;Debug;Reading message.;<servername>;13876;;12;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:14.4950;Debug;Reading message.;<servername>;13876;;17;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:14.9855;Debug;Reading message.;<servername>;13876;;20;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:15.4596;Debug;Reading message.;<servername>;13876;;12;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:15.9254;Debug;Reading message.;<servername>;13876;;10;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:16.3989;Debug;Reading message.;<servername>;13876;;17;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:16.8795;Debug;Reading message.;<servername>;13876;;16;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:17.3629;Debug;Reading message.;<servername>;13876;;16;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:17.8494;Debug;Reading message.;<servername>;13876;;10;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:18.3195;Debug;Reading message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:18.7956;Debug;Reading message.;<servername>;13876;;10;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:19.3006;Debug;Reading message.;<servername>;13876;;20;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:19.7589;Debug;Reading message.;<servername>;13876;;18;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:20.2304;Debug;Reading message.;<servername>;13876;;14;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:20.7039;Debug;Reading message.;<servername>;13876;;20;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:21.1894;Debug;Reading message.;<servername>;13876;;18;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:21.6602;Debug;Reading message.;<servername>;13876;;14;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:22.1386;Debug;Reading message.;<servername>;13876;;8;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:22.6091;Debug;Reading message.;<servername>;13876;;15;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:23.0816;Debug;Reading message.;<servername>;13876;;12;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:23.5700;Debug;Reading message.;<servername>;13876;;17;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:24.0410;Debug;Reading message.;<servername>;13876;;15;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:24.4992;Debug;Reading message.;<servername>;13876;;10;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:24.9539;Debug;Reading message.;<servername>;13876;;15;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:25.4463;Debug;Reading message.;<servername>;13876;;16;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:25.9206;Debug;Reading message.;<servername>;13876;;18;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:26.3793;Debug;Reading message.;<servername>;13876;;14;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:26.8371;Debug;Reading message.;<servername>;13876;;17;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:27.2973;Debug;Reading message.;<servername>;13876;;14;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:27.7938;Debug;Reading message.;<servername>;13876;;20;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:28.2675;Debug;Reading message.;<servername>;13876;;12;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:28.7292;Debug;Reading message.;<servername>;13876;;14;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:29.2914;Debug;Reading message.;<servername>;13876;;15;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:29.7651;Debug;Reading message.;<servername>;13876;;15;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:30.2252;Debug;Reading message.;<servername>;13876;;14;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:30.7343;Debug;Reading message.;<servername>;13876;;14;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:31.1895;Debug;Reading message.;<servername>;13876;;19;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:31.6596;Debug;Reading message.;<servername>;13876;;12;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:32.1317;Debug;Reading message.;<servername>;13876;;19;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:32.6205;Debug;Reading message.;<servername>;13876;;10;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:33.0808;Debug;Reading message.;<servername>;13876;;16;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:33.5680;Debug;Reading message.;<servername>;13876;;10;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:34.0543;Debug;Reading message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:34.5429;Debug;Reading message.;<servername>;13876;;8;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:35.0094;Debug;Reading message.;<servername>;13876;;12;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:35.5007;Debug;Reading message.;<servername>;13876;;5;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:35.9699;Debug;Reading message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:36.4419;Debug;Reading message.;<servername>;13876;;12;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:36.9170;Debug;Reading message.;<servername>;13876;;19;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:37.3651;Debug;Reading message.;<servername>;13876;;12;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:37.8181;Debug;Reading message.;<servername>;13876;;20;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:38.2860;Debug;Reading message.;<servername>;13876;;5;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:38.7637;Debug;Reading message.;<servername>;13876;;8;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:39.2366;Debug;Reading message.;<servername>;13876;;8;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:39.7167;Debug;Reading message.;<servername>;13876;;19;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:40.1864;Debug;Reading message.;<servername>;13876;;8;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:40.6606;Debug;Reading message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:41.1206;Debug;Reading message.;<servername>;13876;;12;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:43.2977;Debug;Sending message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:43.2977;Debug;Sending message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:43.2977;Debug;Sending message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:43.2977;Debug;Sending message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:43.2977;Debug;Sending message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:43.2977;Debug;Sending message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:43.2977;Debug;Sending message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:43.2977;Debug;Sending message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:43.2977;Debug;Sending message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:43.2977;Debug;Sending message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:43.2977;Debug;Sending message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:43.2977;Debug;Sending message.;<servername>;13876;;13;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:45.2825;Debug;Sending message.;<servername>;13876;;5;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:45.2825;Debug;Sending message.;<servername>;13876;;5;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:45.2825;Debug;Sending message.;<servername>;13876;;5;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:45.2825;Debug;Sending message.;<servername>;13876;;5;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:45.2825;Debug;Sending message.;<servername>;13876;;5;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:45.2825;Debug;Sending message.;<servername>;13876;;5;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:45.2825;Debug;Sending message.;<servername>;13876;;5;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:45.2825;Debug;Sending message.;<servername>;13876;;5;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:45.2825;Debug;Sending message.;<servername>;13876;;5;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:46.4038;Debug;Sending message.;<servername>;13876;;8;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:46.4038;Debug;Sending message.;<servername>;13876;;8;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:46.4038;Debug;Sending message.;<servername>;13876;;8;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:46.4038;Debug;Sending message.;<servername>;13876;;8;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:48.5872;Debug;Sending message.;<servername>;13876;;5;Grpc.AspNetCore.Server.ServerCallHandler;
2021-03-08 14:12:49.1908;Info;Request finished in 57084.8273ms 200 application/grpc;<servername>;13876;;12;Microsoft.AspNetCore.Hosting.Diagnostics;
2021-03-08 14:14:09.3012;Info;Application is shutting down...;<servername>;13876;;86;Microsoft.Hosting.Lifetime;

```

**Comment by lalernehl** [comment]
We have a similar issue where it fails with clients using managed code (grpc-dotnet, grpccurl, prototool-grpc). Using the grpc lib works fine (https://github.com/grpc/grpc). Also BloomRPC has no issues.

It only occurs with payloads relatively bigger (but not big) and the payload cuts off at size = 2^16-1.

**Comment by JamesNK** [comment]
@lalernehl grpc-dotnet uses .NET gRPC client. grpcurl and prototool-grpc both look like they use Go gRPC client.

@ThorstenReichert The order of a Task.Delay and a WriteAsync shouldn't have any impact. Does the timeout consistently happen at the same time? (approx 1 minute according to the log attached)

**Comment by ThorstenReichert** [comment]
@JamesNK There is no timeout happening on the server-side (where the attached log comes from). This was me manually closing the application (only included to show that there were no other trailing log messages).

According to the server application, the final message is actually sent (at least there were no observable errors on the server application):
```
2021-03-08 14:12:48.5872;Debug;Sending message.;<servername>;13876;;5;Grpc.AspNetCore.Server.ServerCallHandler;
```
It is only when the client tries to receive the final message, that the `InvalidDataException` is raised:
```csharp
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error reading next message. InvalidDataException: Unexpected end of content while reading the message content.", DebugException="System.IO.InvalidDataException: Unexpected end of content while reading the message content.
   at Grpc.Net.Client.StreamExtensions.ReadMessageContent(Stream responseStream, Memory`1 messageData, Int32 length, CancellationToken cancellationToken)
   at Grpc.Net.Client.StreamExtensions.ReadMessageAsync[TResponse](Stream responseStream, GrpcCall call, Func`2 deserializer, String grpcEncoding, Boolean singleMessage, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.HttpContentClientStreamReader`2.MoveNextCore(CancellationToken cancellationToken)")
   at Grpc.Net.Client.Internal.HttpContentClientStreamReader`2.MoveNextCore(CancellationToken cancellationToken)
```
And while I agree that the `Task.Delay` should not have any impact, so far we have seen that exception on every call that had no such delay (or placed before  `WriteAsync`), but on none of the calls, where the delay was included after `WriteAsync`.

**Comment by JamesNK** [comment]
I don't think the server is timing out, I think it is the request through the VPN. Can you reproduce this without using a VPN? (so still have the delay to simulate a slow connection, but not call via a VPN)

My guess is the VPN is the culprate here.

**Comment by ThorstenReichert** [comment]
Just curious, where did you see that timeout in the logfile?
> Does the timeout consistently happen at the same time? (approx 1 minute according to the log attached)

Back on track, this service is intended to be used in an internal network. Which means, people working remotely do need to access it via VPN. I'll try to get a repro up without using a VPN, might take a few days though.

**Comment by JamesNK** [comment]
I don't see a timeout, but from the client's perspective something is prematurally ending the request.

When a gRPC message is sent there is a header that specifies how large the message is. The client reads data until it has all the data required.

https://github.com/grpc/grpc-dotnet/blob/761bfe8f7156ce8517c4ba5f8f91dff68e95a6ec/src/Grpc.Net.Client/Internal/StreamExtensions.cs#L226-L245

Something is causing the response stream to report that it is done before it reaches the length. I would usually expect an error caused this to happen, in which case an exception is thrown when reading the response stream. But in your situation as far as the client is aware the response ended gracefully, but early.
