### ISSUE TITLE
.Net Standard 2.0 client exception Only HTTP/1.0 and HTTP/1.1 version requests are currently supported.

### ISSUE THREAD

**Issue by tdhintz** [grpc/grpc-dotnet#1231]
Using the pre-release and this documentation, #21689, I created a client.  This generates the following "internal" error exception.  Am I missing an option?

This is a Windows 10 workstation with current patches, although I need to support a wide variety of Windows OS'.

```
Channel = GrpcChannel.ForAddress($"https://localhost:{BINDING_PORT}", new GrpcChannelOptions
{
    HttpHandler = new GrpcWebHandler(new HttpClientHandler())
});
```

The server code allows http 1 & 2, although I doubt a call is actually performed.

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureLogging(logging =>
                {
                    logging.AddFilter("Grpc", LogLevel.Debug);
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.ConfigureKestrel(options =>
                    {
                        options.Listen(IPAddress.Loopback, BINDING_PORT, configure => 
                        { 
                            configure.UseHttps(GetCertificate());
                            configure.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http1AndHttp2;
                        });
                    });

                    webBuilder.UseStartup<Startup>();
                }).UseWindowsService();
```

Here is the exception detail:

```
Grpc.Core.RpcException
  HResult=0x80131500
  Message=Status(StatusCode="Internal", Detail="Error starting gRPC call. ArgumentException: Only HTTP/1.0 and HTTP/1.1 version requests are currently supported.
Parameter name: value", DebugException="System.ArgumentException: Only HTTP/1.0 and HTTP/1.1 version requests are currently supported.
Parameter name: value
   at System.Net.HttpWebRequest.set_ProtocolVersion(Version value)
   at System.Net.Http.HttpClientHandler.CreateAndPrepareWebRequest(HttpRequestMessage request)
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Net.Client.Web.GrpcWebHandler.<SendAsyncCore>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Net.Client.Internal.GrpcCall`2.<RunCall>d__70.MoveNext()")
  Source=mscorlib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at LicenseService.Licenses.LicensesClient.GetLicense(LicRequest request, CallOptions options) in C:\Repos\ImageDirector\Source\ImageDirector\LicenseClient\obj\x64\Debug\Protos\LicensesGrpc.cs:line 352
   at LicenseService.Licenses.LicensesClient.GetLicense(LicRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in C:\Repos\ImageDirector\Source\ImageDirector\LicenseClient\obj\x64\Debug\Protos\LicensesGrpc.cs:line 339
   at LicClient.LicenseGRpcClientChannel.GetLicense(String feature, String version, String sessionID, String user, Guid id) in C:\Repos\ImageDirector\Source\ImageDirector\LicenseClient\LicenseGRpcClientChannel.cs:line 77
   at LicClient.LicenseGRpcInterface.GetLicense(String feature, String version, String sessionID, String user) in C:\Repos\ImageDirector\Source\ImageDirector\LicenseClient\LicenseGRpcInterface.cs:line 79
   at LicClient.LicenseGrpcClient.GetLicense(String feature, String version, String sessionID, String user) in C:\Repos\ImageDirector\Source\ImageDirector\LicenseClient\LicenseGRpcClient.cs:line 72
   at LicTester.Program.Main(String[] args) in C:\Work\Petri\LicenseClient\LicTester\Program.cs:line 15

```

**Comment by JamesNK** [comment]
> This is a Windows 10 workstation with current patches, although I need to support a wide variety of Windows OS'.

Using WinHttpHandler requires the version of Windows specified in the docs. It may be backported to more versions of Windows, but doing that is out of my hands.

**Comment by tdhintz** [comment]
My laptop is very current but I haven't verified the specific version.  Its a mute point though because I can't go to .Net 5 and I must support customers on older operating systems.  I'll have to abandon this.  Thanks,

**Comment by JamesNK** [comment]
.NET 5 isn't required. I suggest you read the docs I linked to. They go into detail about what is and isn't supported.

**Comment by tdhintz** [comment]
I've spent 2 weeks and multiple strategies.  During that time I certainly did read lots of docs.  I can only assume what I need isn't supported but I do find it odd.

**Comment by pberggreen** [comment]
I have the same problem. 
I would like to call a gRPC-Web service from a full .net client. 
Any suggestions?
@JamesNK What documentation are you talking about?
