### ISSUE TITLE
GRPC calls not working in Azure app service

### ISSUE THREAD

**Issue by NaveenGopalakrishna** [grpc/grpc-dotnet#1246]
When trying in local GRPC calls are working fine. However when trying to call the same when hosted in azure app service is not working.

Getting below exception.

Grpc.Core.RpcException: 'Status(StatusCode="Internal", Detail="Error starting gRPC call. InvalidOperationException: The inner handler has not been assigned.", DebugException="System.InvalidOperationException: The inner handler has not been assigned.
   at System.Net.Http.DelegatingHandler.SetOperationStarted()
   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Web.GrpcWebHandler.<>n__0(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Web.GrpcWebHandler.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")'

source code used to call the service

 var httpHandler = new GrpcWebHandler();
            httpHandler.HttpVersion = new Version(1, 1);
var channel = GrpcChannel.ForAddress(address,new GrpcChannelOptions
            {
                HttpHandler = httpHandler,
                
            });
            var client = new AssetConfigurationGrpc.AssetConfigurationGrpcClient(channel);
            var input = new AssetConfigurationInput
            {
                AssetID = 11
            };

            var result = client.GetAssetAttributeConfiguration(input);

Please help with any suggestions or changes.

**Comment by JamesNK** [comment]
You haven't passed an inner handler to `GrpcWebHandler`.
