### ISSUE TITLE
An exception occurred while HTTPS was being used

### ISSUE THREAD

**Issue by iamfrankjie** [grpc/grpc-dotnet#1251]
```cs
Channel channel1 = new Channel("test.plsgames.com:5001", new SslCredentials());
GrpcChannel channel2 = GrpcChannel.ForAddress("https://test.plsgames.com:5001", new GrpcChannelOptions()
{
  Credentials = new SslCredentials()
});
```

When I press the above code creates Grpc.Core.Channel and Grpc.Net.Client.GrpcChannel.
Grpc.Core.Channel can work smoothly, but Grpc.Net.Client.GrpcChannel abnormal when calling:

>Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Bad gRPC response. Response protocol downgraded to HTTP/1.1.")
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   ....

What can I do to make it work?
Grpc.Net.Client 2.36.0
Thanks

**Comment by JamesNK** [comment]
You need to specify https in the address:

```csharp
GrpcChannel channel2 = GrpcChannel.ForAddress("https://test.plsgames.com:5001", new GrpcChannelOptions()
{
  Credentials = new SslCredentials()
});
```

**Comment by JamesNK** [comment]
What .NET version are you using?
Could you provide information about how your server is configured?

**Comment by iamfrankjie** [comment]
> What .NET version are you using?
> Could you provide information about how your server is configured?

.Net Core 3.1
Tests done on Windows 2008

**Comment by iamfrankjie** [comment]
> What .NET version are you using?
> Could you provide information about how your server is configured?


The server side uses the route_guide example.
I configured load balancing on the AWS ALB and placed the certificate on it.
AWS ALB already supports gRPC and  Grpc.Core.Channel can work smoothly.

**Comment by JamesNK** [comment]
I think the problem is your OS is too old.

See https://github.com/dotnet/aspnetcore/issues/23068
