### ISSUE TITLE
.NET 5. gRPC. Received an unexpected EOF or 0 bytes from the transport stream. Requesting HTTP version 2.0 with version policy RequestVersionOrHigher

### ISSUE THREAD

**Issue by SLavaLL** [grpc/grpc-dotnet#1252]
I have a server on the platform .Net Framework 4.8, which contains a gRPC service with SslServerCredentials for transport security, with self signed certificate. The certificate common name (CN) is LOCALHOST. 
So, I have some clients on the platform .Net Core 2.1 that works fine with this server. Now, I have started developing a new client on the platform .Net 5, and ran into some problems. 
Client code:

```
            var key = GetServerKey();
            var opt = new GrpcChannelOptions
            {
                MaxReceiveMessageSize = int.MaxValue,
                MaxSendMessageSize = int.MaxValue                    
            };                

            GrpcChannel channel;                
            var buf = GetBytesFromCrt(key);
            var cert = new X509Certificate2(buf);
                            
            var handler = new HttpClientHandler
            {
                ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator                                        
            };

            handler.ClientCertificates.Add(cert);
            var httpClient = new HttpClient(handler);                                

            opt.HttpClient = httpClient;
            channel = GrpcChannel.ForAddress($"https://{server}", opt);
            var _grpcClient = new AppWinServiceGrpc.AppWinServiceGrpcClient(channel);

            var res = _grpcClient.Ping(new PingRequest { Ping = "1" });
```                    

On other computers with Windows 10 and Windows 2016 Server, everything works correctly. 
On my computer with Windows 10, I get errors. 
When I specify the server IP address, the error is "Received an unexpected EOF or 0 bytes from the transport stream". 
In .Net Core 2.1 project I added parameter grpc.ssl_target_name_override = "LOCALHOST". 
In the project .Net 5 I didn't find where to add it.

When I specify the server as localhost instead of an IP address, the error is "Requesting HTTP version 2.0 with version policy RequestVersionOrHigher"

That is, the problem is clearly that something is missing on my computer. But what is missing, and what needs to be done to fix it, is unclear...

**Comment by BrennanConroy** [comment]
Do you have a repro app for this issue?

Also, was this the full error? "Requesting HTTP version 2.0 with version policy RequestVersionOrHigher"

**Comment by linmic30** [comment]
I run into a same kind of problem in 2 different scenarios. I have several kestrel services that need to talk to each other on different servers. I have 2 windows 2016 servers in different domains and 2 windows 2012 r2 servers that are in the same domain as one of the 2016 servers. the 2 2012 r2 servers communicate with each other perfectly after adding the following code to my program.cs :`AppContext.SetSwitch("Microsoft.AspNetCore.Server.Kestrel.EnableWindows81Http2", true);`. But when i try to communicate between server 2016 and server 2012 r2 i get the error as descirbed above. 

> The SSL connection could not be established, see inner exception. IOException:  Received an unexpected EOF or 0 bytes from the transport stream.", DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

My first thought was the difference in windows versions and the fact that windows server 2012 r2 does not really support tls over http2. But when i tried the windows server 2016 in the different domain i got the same error. I also tried to accept all certificates in the grpc channel through the http client with not much luck. 

The servers in the different domains could have problems with cors but then i would expect a cors exception and not this one. Could it be a cipher problem or a certificate problem? The server in the other domain has a self signed certificate and the 3 servers in the same domain have a certificate that was issued by a certficate provider.

**Comment by BrennanConroy** [comment]
Can you provide a wireshark trace of the handshake?
And also Trace level server logs.

**Comment by linmic30** [comment]
for me i found my issue, It was that the account i was running the service under, on the 2016 server in the domain with the 3 servers, was not able to access the private key of the certificate that was used. when i added the user to the permissions of the private key's the calls were working. i do not know if that wil fix the issue in general, but for me this worked.

**Comment by SLavaLL** [comment]
> Can you provide a wireshark trace of the handshake?

The first case is when its IP address is specified as the server. Here, the protocol is TLSv1 instead of TLSv1.2. The question is how to specify LOCALHOST as grpc.ssl_target_name_overrid for .Net5 client.

![image](https://user-images.githubusercontent.com/15767627/113243459-bb122400-92bb-11eb-8dd5-89df70a830c5.png)
[1.zip](https://github.com/grpc/grpc-dotnet/files/6241015/1.zip)

The second case is when LOCALHOST is specified as the server.

![image](https://user-images.githubusercontent.com/15767627/113244213-3cb68180-92bd-11eb-8212-7e27e78e0d1a.png)
[2.zip](https://github.com/grpc/grpc-dotnet/files/6241038/2.zip)

> And also Trace level server logs.

I don't know yet how to get a server trace for a project on .Net Framework 4.8. If I can do it, I'll post it here.

> Do you have a repro app for this issue?

I don't have a public repository for this case. If it helps a lot, I can create test projects. But, on other computers, this situation may not be reproduced.

> Also, was this the full error? "Requesting HTTP version 2.0 with version policy RequestVersionOrHigher"

The full error for the first case is:
```Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: The SSL connection could not be established, see inner exception. IOException:  Received an unexpected EOF or 0 bytes from the transport stream.", DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
```

The full error for the second case is:
```
Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while server offers only version fallback.", DebugException="System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while server offers only version fallback.
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
```

**Comment by JamesNK** [comment]
This error "Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while server offers only version fallback." means that the client is asking to create a HTTP/2 or HTTP/3 connection, and the server only offers HTTP/1.1. Why this is happening for your client and server I don't know.

I looked at the Wireshark traces and I couldn't find an [ALPN](https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation) section in the ClientHello.

Yours: (no ALPN)

![image](https://user-images.githubusercontent.com/303201/114499448-37244880-9c7a-11eb-9490-da2ebeda2eff.png)

Mine: (has ALPN)

![image](https://user-images.githubusercontent.com/303201/114499504-50c59000-9c7a-11eb-9e9e-c78e4a9cab42.png)

Windows 10 supports ALPN. I don't know why your trace is missing it.

**Comment by JamesNK** [comment]
Closing because of no activity.

**Comment by SLavaLL** [comment]
The problem is still being reproduced.
It is not clear how it is determined whether or not there will be an ALPN section in the ClientHello message.

**Comment by wfurt** [comment]
do you have packet captures for you test project  @SLavaLL? Schannel does some caching based on SNI. I'm not sure if that is applicable but we have seen some interop problems with TLS1.2 and TLS1.3

You can look at https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings and try to disable caching.

**Comment by SLavaLL** [comment]
> do you have packet captures for you test project @SLavaLL? Schannel does some caching based on SNI. I'm not sure if that is applicable but we have seen some interop problems with TLS1.2 and TLS1.3
> 
> You can look at https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings and try to disable caching.

The captured packets are attached to this [message](https://github.com/grpc/grpc-dotnet/issues/1252#issuecomment-811634733)

[1.zip](https://github.com/grpc/grpc-dotnet/files/6241015/1.zip)
[2.zip](https://github.com/grpc/grpc-dotnet/files/6241038/2.zip)

I tried setting ClientCacheTime to zero - nothing changed. And it is unlikely a problem with caching. It is happens regularly, and is also happens after a new certificate is created.

**Comment by wfurt** [comment]
the first capture does not have even server_name and that clearly suspicious. Cipher list is very short. 
When you say 'regularly' is that random and often or is there some consistency? 
Could you reproduce it with just simple HttpClient doing H/2 request to https://myhost:5001/XXX ?

**Comment by SLavaLL** [comment]
> the first capture does not have even server_name and that clearly suspicious. Cipher list is very short.

The first request was with the server's IP address. This is a separate issue, where the ClientHello request goes as TLSv1, not TLSv1.2. But, this is not the main problem.

> When you say 'regularly' is that random and often or is there some consistency?

The error is always reproduced on my computer, and on another server. There was never a time when it was not reproduced. I meant that the requests were executed over a long time and at different intervals, such that the cache lifetime was exceeded anyway.

> Could you reproduce it with just simple HttpClient doing H/2 request to https://myhost:5001/XXX ?

I wrote a test application .Net 5
```
            var url = "https://myhost:5001/greet.Greeter/SayHello";            

            ServicePointManager.ServerCertificateValidationCallback = delegate (Object obj, X509Certificate certificate, X509Chain chain, SslPolicyErrors errors)
            {
                return (true);
            };
            
            var message = new HttpRequestMessage(HttpMethod.Post, url)
            {
                Version = new Version(2, 0)
            };
            var client = new HttpClient();
            var resp = client.SendAsync(message).Result;
```
and got an error "IOException: The response ended prematurely."

Captured messages [3.zip](https://github.com/grpc/grpc-dotnet/files/6632207/3.zip)

Test application .NetFramework 4.8
```
            var url = "https://myhost:5001/greet.Greeter/SayHello";            

            ServicePointManager.ServerCertificateValidationCallback = delegate (Object obj, X509Certificate certificate, X509Chain chain, SslPolicyErrors errors)
            {
                return (true);
            };

            var handler = new WinHttpHandler();
            handler.ServerCertificateValidationCallback = delegate { return true; };

            var message = new HttpRequestMessage(HttpMethod.Post, url)
            {
                Version = new Version(2, 0)
            };

            var client = new HttpClient(handler);            
            var resp = client.SendAsync(message).Result;  
```
Got response "UnsupportedMediaType"

Captured messages [4.zip](https://github.com/grpc/grpc-dotnet/files/6632238/4.zip)

As far as I understand, in the version with the Net Framework, the request was successful, the problem is already in the content of the package, or rather, in its absence.

**Comment by wfurt** [comment]
ServicePointManager does really nothin on .NET Core.
Try
```c#
 handler.ServerCertificateCustomValidationCallback = (request, cert, chain, errors) => { return true; };
```

The 3.zip shows support for TLS 1.3. That is interesting as that exists only on new windows versions. As experiment, could you try to force TLS1.2 @SLavaLL?

**Comment by SLavaLL** [comment]
I tried using the fixed version of TLS 1.2, the result is the same
[5.zip](https://github.com/grpc/grpc-dotnet/files/6634361/5.zip)


```
            var url = "https://myhost:5001/greet.Greeter/SayHello";
            var handler = new HttpClientHandler
            {
                ServerCertificateCustomValidationCallback = (request, cert, chain, errors) => { return true; },
                SslProtocols = SslProtocols.Tls12
            };
            var client = new HttpClient(handler);
            var resp = client.PostAsync(url, new StringContent("")).Result;
```

Where did you see the TLS 1.3 version ?

I see TLS 1.0 and TLS 1.2 in 3.zip and 5.zip

![image](https://user-images.githubusercontent.com/15767627/121596839-aafb8b00-ca48-11eb-99cf-7bdbe85c145c.png)

And TLS 1.2 in 4.zip

![image](https://user-images.githubusercontent.com/15767627/121597039-e1d1a100-ca48-11eb-811d-5b899a2301f7.png)
