### ISSUE TITLE
Error using OpenIdConnectDefaults Authentication

### ISSUE THREAD

**Issue by FireSon** [grpc/grpc-dotnet#1277]
In my scenario I am hosting a grpc service in a Blazor ServerSide application. This application uses AzureAD authentication which is added in the following manner

```
    services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
        .AddMicrosoftIdentityWebApp(options =>
        {
            Configuration.Bind("AzureAd", options);
            options.ResponseType = "code";
            options.SaveTokens = true;
        });
```

I create my grpc client in the follwing way:
```
      var token = await context.HttpContext.GetTokenAsync("access_token");
      var httpClient = new HttpClient(new GrpcWebHandler(GrpcWebMode.GrpcWebText, new HttpClientHandler()));
      var credentials = CallCredentials.FromInterceptor(async (context, metadata) =>
          metadata.Add("Authorization", $"Bearer {token}"));
      Channel = GrpcChannel.ForAddress(navigationManager.BaseUri, Options = new GrpcChannelOptions
      {
          HttpClient = httpClient,
          Credentials = ChannelCredentials.Create(new SslCredentials(), credentials)
      });
      client = Channel.CreateGrpcService<IWeatherForecastService>();
```

When I do no secure my service everything works fine, but when I add the [Authorize] attribute to my service I get the following error:
```
Grpc.Core.RpcException: Status(StatusCode="Cancelled", Detail="Bad gRPC response. Invalid content-type value: text/html; charset=utf-8")
   at ServerSide.Pages.FetchData.OnInitializedAsync() in C:\Application\DevQatram2\Blazor\ServerSide\Pages\FetchData.razor:line 51
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

I am aware that calling a grpc service from the same blazor application which hosts the grpc service is not very smart, but it has to do with debugging and the possibility to switch between server side and client side blazor. Switching to another authentication type (I tried JwtBearer) also works, so my estimation is that it has to do with OpenId...

Any help would be much appreciated!
Thanks,
Jan

**Comment by JamesNK** [comment]
Does OpenID return a HTML response? That looks like what is happening and the gRPC client is correctly rejecting it as not a gRPC response.

You can setup logging in the client and server to get more information about what is going on: https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-5.0

**Comment by FireSon** [comment]
I added the logging and this is what it produces:

```
dbug: Grpc.Net.Client.Internal.GrpcCall[1]
      Starting gRPC call. Method type: 'Unary', URI: 'https://localhost:44384/weather.WeatherForecasts/GetWeatherForecasts'.
dbug: Grpc.Net.Client.Internal.GrpcCall[18]
      Sending message.
info: Grpc.Net.Client.Internal.GrpcCall[3]
      Call failed with gRPC error status. Status code: 'Cancelled', Message: 'Bad gRPC response. Invalid content-type value: text/html; charset=utf-8'.
dbug: Grpc.Net.Client.Internal.GrpcCall[4]
      Finished gRPC call.
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Status(StatusCode="Cancelled", Detail="Bad gRPC response. Invalid content-type value: text/html; charset=utf-8")
      Grpc.Core.RpcException: Status(StatusCode="Cancelled", Detail="Bad gRPC response. Invalid content-type value: text/html; charset=utf-8")
         at ServerSide.Pages.FetchData.OnInitializedAsync() in C:\Application\DevQatram2\Blazor\ServerSide\Pages\FetchData.razor:line 51
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'WtsyGREZGGYwIYD1vEaKQL8ov9OQ3PxUGGFLECAVgBc'.
      Grpc.Core.RpcException: Status(StatusCode="Cancelled", Detail="Bad gRPC response. Invalid content-type value: text/html; charset=utf-8")
         at ServerSide.Pages.FetchData.OnInitializedAsync() in C:\Application\DevQatram2\Blazor\ServerSide\Pages\FetchData.razor:line 51
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

**Comment by JamesNK** [comment]
Doesn't OpenID redirect the request to an HTML FORM page in some situations? Isn't that what is happening here?

**Comment by FireSon** [comment]
Well it had to do with authentication, since I am no expert in that area :-) I basically got it working with the following adjustments

I added
```
    services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
        .AddMicrosoftIdentityWebApi(Configuration);
    services.Configure<JwtBearerOptions>(JwtBearerDefaults.AuthenticationScheme, options => options.Events.OnTokenValidated = async context => await Task.Delay(0));
```
And on the service I added the following attribute:
`    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
`

After that it worked, and since it is for debugging purposes only I can live with that ;-)
