### ISSUE TITLE
ConvertHelpers.ToDurationText() do not serialize properly

### ISSUE THREAD

**Issue by baltie** [grpc/grpc-dotnet#1326]
### What version of gRPC and what language are you using?
Grpc.Net.Client 2.37.0

### What operating system (Linux, Windows,...) and version?
Windows 10 20H2

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET SDK 5.0.301

### What did you do?
With a client running with Norwegian culture (or any culture that doesn't use `.` as decimal separator), setting InitialBackoff of RetryPolicy to a fraction of a second breaks. For instance using this RetryPolicy:

```
new RetryPolicy
{
    InitialBackoff = TimeSpan.FromMilliseconds(100),
    MaxBackoff = TimeSpan.FromSeconds(30),
    BackoffMultiplier = 2,
    MaxAttempts = int.MaxValue
}
```

### What did you expect to see?
That setting the initial InitialBackoff of RetryPolicy to a fraction of a second would work when making a gRPC call.

### What did you see instead?
An exception when making a gRPC call:

```
  Error Message:
   System.FormatException : '0,1s' isn't a valid duration.
  Stack Trace:
     at Grpc.Net.Client.Internal.Configuration.ConvertHelpers.ConvertDurationText(String text)
   at Grpc.Net.Client.Configuration.RetryPolicy.get_InitialBackoff()
   at Grpc.Net.Client.Internal.GrpcMethodInfo.CreateRetryPolicy(RetryPolicy r)
   at Grpc.Net.Client.Internal.GrpcMethodInfo.CreateMethodConfig(MethodConfig methodConfig)
   at Grpc.Net.Client.Internal.GrpcMethodInfo..ctor(GrpcCallScope logScope, Uri callUri, MethodConfig methodConfig)
   at Grpc.Net.Client.GrpcChannel.CreateMethodInfo(IMethod method)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Grpc.Net.Client.GrpcChannel.GetCachedGrpcMethodInfo(IMethod method)
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.CreateRootGrpcCall[TRequest,TResponse](GrpcChannel channel, Method`2 method, CallOptions options)
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<AsyncUnaryCall>b__4_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.AsyncUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, AsyncUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   (... own code making a gRPC call ...)
```

### Anything else we should know about your project / environment?
Happened when starting a console app using the gRPC .NET client, started with the dotnet command from PowerShell, running with a Norwegian locale.

I am pretty sure line 119 is the culprit. https://github.com/grpc/grpc-dotnet/blob/5bb5f48fc472f09da2c264b62f0e6cdb630f0a63/src/Grpc.Net.Client/Internal/Configuration/ConvertHelpers.cs#L119

Here, InvariantCulture is used to parse it as a double which is correct, but it was serialized on line 119 with Norwegian culture.
https://github.com/grpc/grpc-dotnet/blob/5bb5f48fc472f09da2c264b62f0e6cdb630f0a63/src/Grpc.Net.Client/Internal/Configuration/ConvertHelpers.cs#L91-L92

**Comment by JamesNK** [comment]
Thanks for the detailed issue. As a temporary workaround you can use an integer with duration properties.
