### ISSUE TITLE
gRPC Windows service account permissions

### ISSUE THREAD

**Issue by MaximGurschi** [grpc/grpc-dotnet#1336]
Hi,

Unless i make the service account a local administrator on the box, i cannot communicate with the service. I have a certificate on the box that the service uses to secure traffic on the port it listens on. But without the account running the service process being a local admin i get an error in the service when the client tries to do a simple call:

Unhandled exception while processing {ConnectionId}.","Exception":"System.ComponentModel.Win32Exception (0x8009030D): The credentials supplied to the package were not recognized
  at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED* scc)
  at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED* secureCredential)
  at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchannelCred(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
  at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
  at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
  at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
  at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
  at System.Net.Security.SslStream.ProcessBlob(Int32 frameSize)
  at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
  at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
  at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()","Properties":{"ConnectionId":"0HMA0LD6OHU0F","SourceContext":"Microsoft.AspNetCore.Server.Kestrel

Can someone please point out a workaround to avoid having to make the service account running my grpc service a local admin? What are the minimum required permissions?

**Comment by MD-V** [comment]
Hello @MaximGurschi,

this is not a gRPC issue specifically. 

Does your service have the rights to access the private key of the certificate (per [Stackoverflow](https://stackoverflow.com/a/7990364/11089839))?

**Comment by MaximGurschi** [comment]
@MD-V Thank you so much, that was indeed the issue! It is strange that the service would start up and not crash given the missing permission. You see in the code i retrieve the certificate and assign it to the port grpc service listens on - this is done at service start up. So it is strange that that part does not blow up and the service does start up, it only blows up at runtime during service rpc requests.
