### ISSUE TITLE
Grpc client factory client doesn't wait for service to start

### ISSUE THREAD

**Issue by sadashivjp** [grpc/grpc-dotnet#1361]
I am using 
Grpc.Net version : Grpc.AspNetCore 2.27.0. 
Language: C#
Dot net core version : Asp.Net Core 3.1
Operating system: Windows 10.0.18363 - x64
.Net SDK : 5.0 (installed)
Project Sdk for Grpc service ="Microsoft.NET.Sdk.Web"
Project Sdk for Grpc client ="Microsoft.NET.Sdk"
Target framework : netcoreapp 3.1
Grpc.Net.ClientFactory version: 2.27.0

I have created named Grpc client using Grpc.Net.ClientFactory. But, the problem is, Grpc client doesn't wait for the Grpc server to start. I tried with configuring underlying HttpClient's timeout and also RPC call deadline. That is not working. How can I make Grpc client to wait for sometime for Grpc service to start, that could be indeterministic? (may be 10 seconds or 5 minutes waiting) Why deadline setting doesn't work here? What is the RPC deadline, whether it is the waiting time after service gets the request or is it the waiting time including the channel communication to be established? It immediately throws exception. How can I retry async Grpc calls after failure, what is the configuration for it? I am feeling, Grpc.Net.Client is better than client factory as Grpc.Net.Client waits for an infinite duration for Grpc service unless deadline or cancellation token is explicitly mentioned. Please provide the solution. I feel better documentation is needed from Microsoft on Grpc.Net.ClientFactory with few more configuration examples. I felt, it is not enough.

It is my **console Grpc client code**:

**Program.cs**
```
class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello Grpc client factory test...!!!");
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices((hostbuilderContext, services) =>
                {
                    services.AddHostedService<Worker>();
                    services.AddGrpcClient<Greeter.GreeterClient>("greeter-client",(o) =>
                        {
                            o.Address = new Uri("https://localhost:5001");
                        }).ConfigureHttpClient(client =>
                        {
                            client.Timeout = TimeSpan.FromSeconds(60);
                        });
                });
    }
```

**Worker.cs**
```
public class Worker : BackgroundService
    {
        private readonly Greeter.GreeterClient greeterClient;
        private readonly ILogger<Worker> _logger;
        public Worker(GrpcClientFactory clientFactory, ILogger<Worker> logger)
        {
            greeterClient = clientFactory.CreateClient<Greeter.GreeterClient>("greeter-client");
            _logger = logger;
        }
        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            var reply = await greeterClient.SayHelloAsync(new HelloRequest { Name = "Greeter client" },
                deadline: DateTime.UtcNow.AddSeconds(120));
            _logger.LogInformation($"Response from greeter service: {reply.Message}");
        }
    }
```
My **Grpc service code**:
```
public class GreeterService : Greeter.GreeterBase
    {
        private readonly ILogger<GreeterService> _logger;
        public GreeterService(ILogger<GreeterService> logger)
        {
            _logger = logger;
        }

        public override Task<HelloReply> SayHello(HelloRequest request, ServerCallContext context)
        {
            return Task.FromResult(new HelloReply
            {
                Message = "Hello " + request.Name
            });
        }
    }
```
**Startup.cs**
```
public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddGrpc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGrpcService<GreeterService>();

                endpoints.MapGet("/", async context =>
                {
                    await context.Response.WriteAsync("Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");
                });
            });
        }
    }
```
**Exception details that I am getting:**
```
fail: Grpc.Net.Client.Internal.GrpcCall[6]
      Error starting gRPC call.
      System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it.
       ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
         at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request)
fail: Grpc.Net.Client.Internal.GrpcCall[3]
      Call failed with gRPC error status. Status code: 'Internal', Message: 'Error starting gRPC call: No connection could be made because the target machine actively refused it.'.
```
It works fine, if already Grpc service is up and running before client makes request. Please guide me with the solution.

**Comment by JamesNK** [comment]
See https://github.com/grpc/grpc-dotnet/issues/1360

The next release will support wait for ready which will wait until the server is ready. Note that it won't be usable from gRPC client factory in the initial release. Instead you'll need to create GrcpChannel and clients yourself.

**Comment by sadashivjp** [comment]
Thanks for your reply @JamesNK . I hope WithWaitForReady and TryWaitForStateChanged will be released very soon.

**Comment by sadashivjp** [comment]
I have one more question on top of it. In case, if it fails with one of the RpcException, how can we retry async RPC call, until we get response from the service? Is there any implicit way for it in grpc.Net ? @JamesNK

**Comment by JamesNK** [comment]
There is retry functionality built into the client. Please read the documentation.

**Comment by JamesNK** [comment]
The new gRPC release is out - https://www.nuget.org/packages/Grpc.Net.Client/2.39.0-pre1

It would be great if you could try it out and see whether `WithWaitForReady` and `TryWaitForStateChangedAsync` work for you.

When trying it out I suggest configuring client logging - https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-5.0#grpc-client-logging - It provides information about changes in connectivity state.

**Comment by JamesNK** [comment]
Closing because of no activity.

**Comment by semihokur** [comment]
@JamesNK could you give an example for TryWaitForStateChangedAsync? I did not see it in the codebase as well.
