### ISSUE TITLE
HttpApi triggers synchronous Flush() when writing a large message to the response as JSON

### ISSUE THREAD

**Issue by cwe1ss** [grpc/grpc-dotnet#1375]
### What version of gRPC and what language are you using?
* Grpc.AspNetCore (_2.38.0_)
* Microsoft.AspNetCore.Grpc.HttpApi (_0.1.0-alpha.21317.5_)

### What operating system (Linux, Windows,...) and version?
* Windows 10.0.19043

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
* SDK: 5.0.400
* Runtime: 5.0.9

### What did you do?
I tried to return a large proto message as JSON via the `Microsoft.AspNetCore.Grpc.HttpApi` project. 

### What did you expect to see?
I expected it to work by default with AllowSynchronousIO turned off since it also works for smaller message objects.

### What did you see instead?
I received the following exception:

```
 System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
         at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.FlushInternal(Boolean flushEncoder)
         at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.Write(String value)
         at Google.Protobuf.JsonFormatter.WriteString(TextWriter writer, String text)
         at Google.Protobuf.JsonFormatter.WriteMessageFields(TextWriter writer, IMessage message, Boolean assumeFirstFieldWritten)
         at Google.Protobuf.JsonFormatter.WriteMessage(TextWriter writer, IMessage message)
         at Google.Protobuf.JsonFormatter.WriteList(TextWriter writer, IList list)
         at Google.Protobuf.JsonFormatter.WriteMessageFields(TextWriter writer, IMessage message, Boolean assumeFirstFieldWritten)
         at Google.Protobuf.JsonFormatter.WriteMessage(TextWriter writer, IMessage message)
         at Google.Protobuf.JsonFormatter.WriteList(TextWriter writer, IList list)
         at Google.Protobuf.JsonFormatter.WriteMessageFields(TextWriter writer, IMessage message, Boolean assumeFirstFieldWritten)
         at Google.Protobuf.JsonFormatter.WriteMessage(TextWriter writer, IMessage message)
         at Google.Protobuf.JsonFormatter.WriteList(TextWriter writer, IList list)
         at Google.Protobuf.JsonFormatter.WriteMessageFields(TextWriter writer, IMessage message, Boolean assumeFirstFieldWritten)
         at Google.Protobuf.JsonFormatter.WriteMessage(TextWriter writer, IMessage message)
         at Microsoft.AspNetCore.Grpc.HttpApi.UnaryServerCallHandler`3.WriteResponseMessage(HttpResponse response, Encoding encoding, Object responseBody)
         at Microsoft.AspNetCore.Grpc.HttpApi.UnaryServerCallHandler`3.SendResponse(HttpResponse response, Encoding encoding, TResponse message)
         at Microsoft.AspNetCore.Grpc.HttpApi.UnaryServerCallHandler`3.HandleCallAsync(HttpContext httpContext)
```

### Anything else we should know about your project / environment?

I can make it work by setting `KestrelServerOptions.AllowSynchronousIO` to `true` and I understand that the JsonFormatter of protobuf is synchronous, but since you're already writing smaller messages asynchronously (IIUC, they must be small enough to never hit Flush internally and therefore trigger your [FlushAsync](https://github.com/aspnet/AspLabs/blob/bd5cd1f4131db5055d1a1d8af15f28f40cc79135/src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/UnaryServerCallHandler.cs#L293)), I'm wondering if it's possible (and a good idea), to somehow force an asynchronous write for large objects as well? 

Ideally, I'd like to keep "AllowSynchronousIO" off as I don't need it anywhere else and having it off is a great way to be notified of such situations.

I'd be happy to try a PR if you want this changed and know of a good way to do it.

PS: Thank you for your efforts on grpc-dotnet and the JSON-API. I really enjoy working with it.

**Comment by JamesNK** [comment]
To use async the entire message will need to be serialized before all the memory is flushed.

I think the solution will be to do what MVC does with Newtonsoft.Json which also has a synchronous serializer. It writes to memory if the payload is below a certain size, and then falls back to the file system.

This serializer limitation is the main reason why this project is experimental.

**Comment by cwe1ss** [comment]
Thank you for your response, James!

IIUC, you are talking about [this code](https://github.com/dotnet/aspnetcore/blob/43bb8e0f9baf2b69118f668485dba4254d3b2918/src/Mvc/Mvc.NewtonsoftJson/src/NewtonsoftJsonOutputFormatter.cs#L166-L203), right?

Do you think it's time well spent doing a PR for this or would some other direction be better in general. (e.g. to just use `AllowSynchronousIO=true`, or to write a System.Text.Json-based protobuf-serializer, or ...?!)

**Comment by rafikiassumani-msft** [comment]
This will be fixed when the following issue is completed: https://github.com/grpc/grpc-dotnet/issues/167
