### ISSUE TITLE
Deployment as Windows Service brings SocketException (10013)

### ISSUE THREAD

**Issue by Rand-Random** [grpc/grpc-dotnet#1389]
When I deploy my app as a Windows Service I am getting the following exception.

```
Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: Error connecting to 'C:\ProgramData\KT\ClientRegister\grpc-transporter.tmp'. (localhost:80) HttpRequestException: Error connecting to 'C:\ProgramData\KT\ClientRegister\grpc-transporter.tmp'. SocketException: Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig.", DebugException="System.Net.Http.HttpRequestException: Error connecting to 'C:\ProgramData\KT\ClientRegister\grpc-transporter.tmp'. (localhost:80)
 ---> System.Net.Http.HttpRequestException: Error connecting to 'C:\ProgramData\KT\ClientRegister\grpc-transporter.tmp'.
 ---> System.Net.Sockets.SocketException (10013): Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, EndPoint remoteEP, CancellationToken cancellationToken)
   at Ktsw.Conx.gRpc.Service.Common.UnixDomainSocketConnectionFactory.ConnectAsync(SocketsHttpConnectionContext _, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Ktsw.Conx.gRpc.Service.Common.UnixDomainSocketConnectionFactory.ConnectAsync(SocketsHttpConnectionContext _, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
```

Attempt to translate the exception
German: SocketException (10013): Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig.
English:  SocketException (10013): The access to the socket failed because the accessrights to the socket are invalid.

Everything works as expected when I start the application as the normal user, so just simply double clicking the exe, instead of running it as a Windows Service.

As you may see from the error message I am using UDS (Unix Domain Sockets) and I am using the path `C:\ProgramData\KT\ClientRegister\grpc-transporter.tmp` where my service and users have access rights.

I am currently using the normal Local system account to run my windows service.

**Comment by JamesNK** [comment]
I'm not sure. Unfortunately, I'm not an expert at using UDS. I searched for UDS on Windows and access rights and results suggest that it is file access permissions that are important.

One suggestion is seeing whether your app can read and write to a file at the same location. If it can do that then you know that file access permissions are ok. I'm not sure what to try after that if they are ok...
