### ISSUE TITLE
Omit stack trace for user-thrown RpcException on server?

### ISSUE THREAD

**Issue by dpbevin** [grpc/grpc-dotnet#1409]
When implementing a server method, I'm validating the request message properties and throwing a `RpcException` like this:
```
throw new RpcException(new Status(StatusCode.InvalidArgument, "Something is not right here"));
```
This results in the following log entries (e.g. in the Console stdout):
```
[16:12:30 INF] Error status code 'InvalidArgument' raised.
Grpc.Core.RpcException: Status(StatusCode="InvalidArgument", Detail="Something is not right here")
   at MyGrpcApp.MagicService.PerformMagic(PerformMagicRequest request, ServerCallContext context) in C:\...\MagicService.cs:line 55
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.AwaitInvoker(Task`1 invokerTask, GrpcActivatorHandle`1 serviceHandle)
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.AwaitInvoker(Task`1 invokerTask, GrpcActivatorHandle`1 serviceHandle)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
[16:12:30 INF] HTTP POST /my.Magic/PerformMagic responded 200 in 216.8861 ms
```

Given that I'm deliberately throwing this exception, is it possible to omit the stack trace from this log?

Based on the code, I'm not sure it's possible without changes to this project. See:
https://github.com/grpc/grpc-dotnet/blob/9f72e70c6a47ae823bb3ddcc719f1c63bf721fc7/src/Grpc.AspNetCore.Server/Internal/HttpContextServerCallContext.cs#L178

**Comment by captainsafia** [comment]
Thanks for opening this issue, @dpbevin!

I think we'll want to add support for the `EnableDetailedErrors` configuration when logging `RpcException` errors similar to what we currently do for non-`RpcException`s. That won't specifically target exceptions thrown in user code but it should give some fidelity for dictating whether or not the full exceptions are displayed.

**Comment by JamesNK** [comment]
Good suggestion. Most of the time this exception isn't useful for debugging.

I think we should do this for any `RpcException` instances thrown by user code. We should review where `RpcException` is thrown by server framework code and see if the exception details are valuable for any.

The log message should be extended to include `Status.Detail`. Right now that information is only in the exception. There is also `Status.DebugException` which we might want to still log - need to investigate.
