### ISSUE TITLE
Setting `ConnectCallback` in `BalancerHttpHandler` causes `InvalidOperationException`

### ISSUE THREAD

**Issue by hypdeb** [grpc/grpc-dotnet#1413]
Hello,

I'm facing an issue where the `BalancerHttpHandler`'s constructor seems to be setting the `ConnectCallback` of its `SocketsHttpHandler` at an inappropriate time, causing the following exception:

```
System.InvalidOperationException: This instance has already started one or more requests. Properties can only be modified before sending the first request.
         at System.Net.Http.SocketsHttpHandler.CheckDisposedOrStarted()
         at System.Net.Http.SocketsHttpHandler.set_ConnectCallback(Func`3 value)
         at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler..ctor(HttpMessageHandler innerHandler, ConnectionManager manager)
         at Grpc.Net.Client.GrpcChannel.CreateInternalHttpInvoker(HttpMessageHandler handler)
         at Grpc.Net.Client.GrpcChannel..ctor(Uri address, GrpcChannelOptions channelOptions)
         at Grpc.Net.Client.GrpcChannel.ForAddress(Uri address, GrpcChannelOptions channelOptions)
         at Grpc.Net.ClientFactory.Internal.GrpcCallInvokerFactory.CreateCallInvoker(HttpMessageHandler httpHandler, String name, Type type, GrpcClientFactoryOptions clientFactoryOptions)
         at Grpc.Net.ClientFactory.Internal.DefaultGrpcClientFactory.CreateClient[TClient](String name)
```

This happens on the second time the `GrpcClientFactory` is called to create a client with the same name. I've wrapped client instantiation and invocation of remote procedure in some other class, is that somehow wrong ? My wrapper is a singleton.

```
public async Task<TResult> ExecuteAsync<TResult>(Func<TClient, Task<TResult>> procedure)
{
    var clientName = typeof(TClient).Name;
    var client = this.grpcClientFactory.CreateClient<TClient>(clientName);
    return await procedure(client);
}
```

I'm on `.NET 6 ` with `Grpc.Net.ClientFactory` version `2.40.0-pre1`

https://github.com/grpc/grpc-dotnet/blob/094532f0fbd3c9c877614beca7a73a797f3eba02/src/Grpc.Net.Client/Balancer/Internal/BalancerHttpHandler.cs#L45

**Comment by JamesNK** [comment]
I think there might be issues with 2.40.0-pre1 and the client factory. I recommend you use 2.39.0 for now.

**Comment by hypdeb** [comment]
Understood. Thank you for the quick update ! Will close once I've confirmed it works with 2.39.0.

**Comment by hypdeb** [comment]
2.39.0 works, thanks !
