### ISSUE TITLE
ChannelCredentials.Insecure + corporate proxy =  Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while HTTP/2 is not enabled.

### ISSUE THREAD

**Issue by boldt** [grpc/grpc-dotnet#1440]
### What version of gRPC and what language are you using?

* Grpc.Net.Client - 2.38.0

### What operating system (Linux, Windows,...) and version?

* Windows 20H2 (10.0.19042)

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)

* 5.0.400

#### Scenario a) Secure Connection

```
var uri = new Uri($"https://{options.Ip}:{options.Port}");
rpcChannel = GrpcChannel.ForAddress(uri);
```

##### Case 1: Circumvent the corporate proxy

To circumvent the corporate proxy, I set it to `HTTPS_PROXY=`:

```
HTTPS_PROXY= ./Client.exe
```

The gPRC connection works. ✓

##### Case 2: Use the corporate proxy

```
HTTPS_PROXY=http://corporate-proxy ./Client.exe
```

The gPRC connection works. ✓

#### Scenario b) Insecure Connection

```c#
var uri = new Uri($"http://{options.Ip}:{options.Port}");
var grpcChannelOptions = new GrpcChannelOptions
{
    Credentials = ChannelCredentials.Insecure
};
GrpcChannel grpcChannel = GrpcChannel.ForAddress(uri, grpcChannelOptions);
[...]
```
##### Case 3: Circumvent the corporate proxy

```
HTTP_PROXY= ./Client.exe
```

The gPRC connection works. ✓

##### Case 4: Use the corporate proxy

```
HTTP_PROXY=http://corporate-proxy ./Client.exe
```

The gPRC connection does not work. I get the following exception: **System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while HTTP/2 is not enabled**. The connection occus immediately, it does not even try to connect (nothing can be seen in Wireshark).

````
System.AggregateException: One or more errors occurred. (Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while HTTP/2 is not enabled.", DebugException="System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while HTTP/2 is not enabled.
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)"))
 ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while HTTP/2 is not enabled.", DebugException="System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while HTTP/2 is not enabled.
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Euroimmun.InfoApp.Protocol.RpcInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Euroimmun.InfoApp.Protocol.CommonService.CommonServiceClient.HandShake(HandShakeRequest request, CallOptions options)
   at Euroimmun.InfoApp.Protocol.CommonService.CommonServiceClient.HandShake(HandShakeRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)
   at Euroimmun.InfoApp.Protocol.DeviceClient`1.SendHandshakeIfRequired()
   at Euroimmun.InfoApp.Protocol.DeviceClient`1.UpdateConfiguration(String deviceId, String deviceName)
   at Euroimmun.InfoApp.DeviceClient.LabDevice.SimulateDevice() in D:\git\EIA\server\source\DeviceClient\LabDevice.cs:line 85
   at Euroimmun.InfoApp.DeviceClient.Program.<>c__DisplayClass1_0.<Main>b__1() in D:\git\EIA\server\source\DeviceClient\Program.cs:line 139
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
````

### What did you expect to see?

Case 4 should connect with a proxy as well.

### What did you see instead?

See Case 4.

**Comment by boldt** [comment]
Hey James,

I made some further investigations. For Case 4, I do not see any traffic to the proxy server in Wireshark. 

**Case 5**: Use the corporate proxy with explicit NO_PROXY

This is basically Case 3, since it circumvents the corporate proxy:

```
HTTP_PROXY=http://corporate-proxy NO_PROXY=grpcservice.mydomain.com ./Client.exe
```

The gPRC connection works. ✓

*Case 6*: Use the corporate proxy with asterix in NO_PROXY

This should be the same as Case 5:

```
HTTP_PROXY=http://corporate-proxy NO_PROXY=*.mydomain.com ./Client.exe
```

As in Case 4, I get the following exception: **System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while HTTP/2 is not enabled**. I also do not see any traffic to the proxy server in Wireshark. 

It seems, that also the asterix is not handled properly. Or it is handled correct, but another issue happens.

**Comment by JamesNK** [comment]
@boldt gRPC uses HttpClient for networking. Support for this will need to be added there.

> If this is an important scenario for you, please file an issue over at [dotnet/runtime](https://github.com/dotnet/runtime).

👍

**Comment by boldt** [comment]
That sounds feasible for **Case 4**, when it is not implemented. 👍

How about **Case 6**? The asterix of the reverse proxy seems to be broken. It should do a direct connection, like **Case 5** and **Case 3**, since **NO_PROXY** says so.
