### ISSUE TITLE
InvalidOpEx "Reading is already in progress" on read of 0 bytes

### ISSUE THREAD

**Issue by erikma** [grpc/grpc-dotnet#1442]
### What version of gRPC and what language are you using?
C#. Grpc.AspNetCore 2.40-pre and head of repo

### What operating system (Linux, Windows,...) and version?
Windows, Win10 20h2 client, Server 2022 server

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET 5

Hosting a proto with mix of single-message, server-stream, and bi-di streaming gRPC server methods. Existing system in production, trying to port from deprecated Google server to ASP.NET Core for net5.0. Regression of overall reliability in server calls by 1-2% over Google server implementation under load. Numerous errors from ASP.NET logging, along with some that throw across the wire to client as InternalError and cause service failures.

Exception traces look like following stack, but occur in both single message and streaming service methods randomly:

ERROR ASP.NET[ErrorExecutingServiceMethod]: Error when executing service method 'XXX'.
 System.InvalidOperationException: Reading is already in progress.
 at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_AlreadyReading()
 at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
 at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
 at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
 at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2MessageBody.ReadAsync(CancellationToken cancellationToken)
 at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadSingleMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer)
 at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
 at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)

I instrumented PipeExtensions.cs to see what it is encountering. The problem seems to occur after a PipeReader is reused across multiple message types and a server read of a client stream goes through a normal termination phase. The following message read believes the DefaultPipeReader (== Pipe.cs in System.IO.Pipelines) and its async read context are still in the middle of a read. Example traces watching what happened on a single Pipe context (== unique object pointer) from service start until one of the exceptions is thrown:

Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Exception during RunCommand: System.InvalidOperationException: Reading is already in progress.
completeMessage False, all pipe reads on this reader: 4 callbacks:
 Callback, 1 rounds, ReadSingleMessageAsync, IsCompleted=True: Consumed 91.
 Callback, 1 rounds, ReadStreamMessageAsync, IsCompleted=(unset): Consumed 3284.
 Callback, 1 rounds, ReadStreamMessageAsync, IsCompleted=True: Consumed 0.
 Callback, 0 rounds, ReadStreamMessageAsync, IsCompleted=(unset): 
 ---> System.InvalidOperationException: Reading is already in progress.

Legend:
- "rounds": The number of times the pipe data receive loop (call to PipeReader.ReadAsync) is run in the Read*MessageAsync call in PipeExtensions.cs.
- IsCompleted: Set to true when code like "if (result.IsCompleted)" is reached in the two methods. Unset means a gRPC message was returned prior to reaching that check.
- Consumed: Bytes read and consumed from the pipe.

Decoding the operations above:

1. A single message, 91 bytes, is received.
2. A client stream is received, first message is 3284 bytes and returned to our service. Next call completes the stream, result.IsCompleted is true. A zero-byte read was made to the PipeReader. (This call appears to update the Pipe state to read-in-progress, though reading the Pipe.cs code I'm not sure I see how: https://github.com/dotnet/corefx/blob/b8b81a66738bb10ef0790023598396861d92b2c4/src/System.IO.Pipelines/src/System/IO/Pipelines/PipeAwaitable.cs#L52 )
3. A new client stream call arrives, server attempts to start reading the stream, gets the "Reading is already in progress" exception from the PipeAwaitable.

The number of callbacks can vary greatly. But all seems to involve calling PipeReader.ReadAsync() after a previous client stream has been fully received. It's reproducible under stress load but I don't have a simple repro.

Any tips here? Instrumenting Kestrel and System.IO.Pipes is doable (Pipes is more difficult as it's bound into the netcore codebase). But perhaps the info above is enough to guess the problem.

**Comment by erikma** [comment]
A bit more detail: I have failure traces where client streams were successfully completed and no exception thrown, IOW it's not a deterministic failure on each client stream completion, but pseudo-random. The trace shown above was chosen for its brevity.

**Comment by erikma** [comment]
With some more instrumentation it seems that PipeExtensions.cs read methods are seeing an ObjectDisposedException from AdvanceTo() that does not reset the read state of the pipe for the next call:

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'HttpRequestStream'.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestPipeReader.<ValidateState>g__ThrowObjectDisposedException|13_0()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestPipeReader.AdvanceTo(SequencePosition consumed, SequencePosition examined)
   at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadStreamMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer, CancellationToken cancellationToken)
   at Grpc.AspNetCore.Server.Internal.HttpContextStreamReader`1.<MoveNext>g__MoveNextAsync|9_0(ValueTask`1 readStreamTask)

**Comment by JamesNK** [comment]
In Kestrel there is pooling of Http2Stream objects. Pooling should only happen if a request completes gracefully, i.e. the request stream gracefully ends and the response stream gracefully ends.

Is it possible your app is reading from the request stream after the request is complete? e.g. the gRPC method has finished, but a task is still trying to read from the request stream? That could cause interference between requests.

**Comment by erikma** [comment]
From the point of view of the server app, it is receiving gRPC messages to its service implementations and simply responding normally. It's a later callback to the impl and its attempt to respond to the client that blows up, with a message that is related to a failure in a previous call to a different API.

**Comment by erikma** [comment]
Rewrote the end-of-bidi related code to avoid the overhang and things are looking much better. Thanks @JamesNK and I hope this helps anyone else searching for this failure pattern.
