### ISSUE TITLE
AsyncUnaryCall throw exception when result.GetStatus() called

### ISSUE THREAD

**Issue by setood** [grpc/grpc-dotnet#1501]
my interceptor crashes with this exception:
```
System.InvalidOperationException: Unable to get the status because the call is not complete.
   at Grpc.Net.Client.Internal.GrpcCall`2.GetStatus()
   at DotnetNiceGrpcMetrics.GrpcMetricsInterceptor.<>c__DisplayClass19_0`2.<AsyncUnaryCall>b__0()
   at System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()System.InvalidOperationException: Unable to get the status because the call is not complete.
   at Grpc.Net.Client.Internal.GrpcCall`2.GetStatus()
   at DotnetNiceGrpcMetrics.GrpcMetricsInterceptor.<>c__DisplayClass19_0`2.<AsyncUnaryCall>b__0()
   at System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
simplified code is:
```csharp
public override AsyncUnaryCall<TResponse> AsyncUnaryCall<TRequest, TResponse>(TRequest request,
    ClientInterceptorContext<TRequest, TResponse> context,
    AsyncUnaryCallContinuation<TRequest, TResponse> continuation)
{
    var result = continuation(request, context);
    result.GetAwaiter().OnCompleted(() =>
    {
        var x = result.GetStatus().StatusCode;
    });
    return result;
}
```
where is my mistake?

**Comment by setood** [comment]
maybe problem in this line order?
```csharp
ClientStreamWriter?.WriteStreamTcs.TrySetCanceled();
ClientStreamWriter?.CompleteTcs.TrySetCanceled();
ClientStreamReader?.HttpResponseTcs.TrySetCanceled();
```
continuation completes before `httpResponse` which contains status
https://github.com/grpc/grpc-dotnet/blob/868adfe377090d6fb2971d5daef70389fdaed641/src/Grpc.Net.Client/Internal/GrpcCall.cs#L211

**Comment by JamesNK** [comment]
Are you using the latest Grpc.Net.Client version?

I couldn't recreate this. Some tests here: https://github.com/grpc/grpc-dotnet/pull/1502

Note that you can get this value using an await. See one the interceptors in the test.

**Comment by rafikiassumani-msft** [comment]
@setood  we are closing this issue due to a lack of activity.
