### ISSUE TITLE
Exception thrown in SocketConnectivitySubchannelTransport.Disconnect()

### ISSUE THREAD

**Issue by olivierboucher** [grpc/grpc-dotnet#1560]
### What version of gRPC and what language are you using?
2.42.0-pre1

### What operating system (Linux, Windows,...) and version?
Docker image:  `mcr.microsoft.com/dotnet/aspnet:5.0`

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)

```
Host (useful for support):
  Version: 5.0.13
  Commit:  b3afe99225

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

### What did you do?

Nothing. Seems to happens sporadically as the server runs

### What did you see instead?

Seems like this is an internal error unrelated to any application specific code. 

```
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
   at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
   at System.Threading.Timer.Change(TimeSpan dueTime, TimeSpan period)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.Disconnect()
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.OnStreamDisposed(Stream streamWrapper)
   at Grpc.Net.Client.Balancer.Internal.StreamWrapper.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.Net.Http.Http2Connection.CheckForShutdown()
   at System.Net.Http.Http2Connection.Dispose()
   at System.Net.Http.HttpConnectionPool.CleanCacheAndDisposeIfUnused()
   at System.Net.Http.HttpConnectionPoolManager.RemoveStalePools()
   at System.Net.Http.HttpConnectionPoolManager.<>c.<.ctor>b__12_0(Object s)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```

**Comment by JamesNK** [comment]
Thanks. This issue was fixed recently: https://github.com/grpc/grpc-dotnet/pull/1554

You could try using 2.41.0-pre1, or using a nightly build from the NuGet feed.

**Comment by olivierboucher** [comment]
Thanks James,

Recently updated my code to use the refactored Resolver API so my only option is the nightly build I guess... Do you know when 2.42 is supposed to land?

**Comment by JamesNK** [comment]
Probably in the next week or two.
