### ISSUE TITLE
ObjectDisposedException on cancellation of server-side-stream (grpc-web, .Net Framework 4.8)

### ISSUE THREAD

**Issue by ThorstenReichert** [grpc/grpc-dotnet#1564]
### What version of gRPC and what language are you using?
- Server: ASP.NET Core 5.0, Grpc.AspNetCore 2.41.0, Grpc.AspNetCore.Web 2.41.0
- Client: .Net Framework 4.8 console app, Grpc.Net.Client 2.41.0, Grpc.Net.Client.Web 2.41.0

### What operating system (Linux, Windows,...) and version?
Windows 10 (20H2)

### Problem Description
In a server-side grpc-web stream, when the client cancels `MoveNext` of the `ResponseStream`, occasionally I get an `RpcException(StatusCode="Internal")` wrapping an `ObjectDisposedException`.

The consuming code looks similar to
```csharp
using var call = client.StreamStuff();
while (!cancellationToken.IsCancellationRequested && await call.ResponseStream.MoveNext(cancellationToken))
{
    // do stuff with call.ResponseStream.Current;
}
```
Sometimes when the `cancellationToken` is cancelled during `MoveNext(cancellationToken)`, I get the exception attached below. On the server side, there is no observable error. Unfortunately, the issue does not reproduce reliably (and never with a debugger attached, so far).

When changing the client from `net48` to `netcoreapp3.0`, the issue does not seem to occur anymore.

My suspicion is, that is is the same underlying issue as in https://github.com/SignalR/SignalR/issues/1600, which was worked around via https://github.com/SignalR/SignalR/pull/1759 by suppressing the initial `ObjectDisposedException`. 

### Exception
```
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error reading next message. ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.", DebugException="System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.<ReadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Net.Client.Web.Internal.Base64ResponseStream.<ReadAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Net.Client.Web.Internal.GrpcWebResponseStream.<TryReadDataAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Net.Client.Web.Internal.GrpcWebResponseStream.<ReadAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Grpc.Net.Client.StreamExtensions.<ReadMessageAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Grpc.Net.Client.Internal.HttpContentClientStreamReader`2.<MoveNextCore>d__18.MoveNext()")
   at Grpc.Net.Client.Internal.HttpContentClientStreamReader`2.<MoveNextCore>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MyCode.<MyMethod>d__16.MoveNext() in C:\My\client\location\Client.cs:line 100
```

### Workaround
I am currently using the following workaround (wrapping the `MoveNext` call)
```csharp
internal static class GrpcClientHelpers
{
    public static async Task<bool> MoveNext<T>(IAsyncStreamReader<T> reader, CancellationToken cancellationToken)
    {
        try
        {
            return await reader.MoveNext(cancellationToken);
        }
        catch (RpcException e) when (cancellationToken.IsCancellationRequested)
        {
            throw new OperationCanceledException("Suppressing ObjectDisposedException from cancellation.", e, cancellationToken);
        }
    }
}
```

**Comment by JamesNK** [comment]
I think this fix here - https://github.com/grpc/grpc-dotnet/pull/1550 - also fixed your issue.

You could test using the latest Grpc.Net.Client package from the nightly feed - https://github.com/grpc/grpc-dotnet#grpc-nuget-feed. Or wait for the next preview.

**Comment by engsky** [comment]
i am using Grpc.Net.Client 2.56.0 and the same exception occur ? how can be solved ?
