### ISSUE TITLE
Exception being thrown when using the gRPC server reflection

### ISSUE THREAD

**Issue by danielvieiravega** [grpc/grpc-dotnet#1729]
### What version of gRPC and what language are you using?
gRPC: nuget packages version 2.45.0 & C#

### What operating system (Linux, Windows,...) and version?
Windows 11

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  3.1.418 [C:\Program Files\dotnet\sdk]
  5.0.407 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

### What did you expect to see?
The grpc methods and messages

### What did you see instead?
The following exception:
```
fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'ServerReflectionInfo'.
      System.InvalidOperationException: Multiple constructors accepting all given argument types have been found in type 'Grpc.Reflection.ReflectionServiceImpl'. There should only be one applicable constructor.
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.TryFindMatchingConstructor(Type instanceType, Type[] argumentTypes, ConstructorInfo& matchingConstructor, Nullable`1[]& parameterMap)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.FindApplicableConstructor(Type instanceType, Type[] argumentTypes, ConstructorInfo& matchingConstructor, Nullable`1[]& matchingParameterMap)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory(Type instanceType, Type[] argumentTypes)
         at Grpc.AspNetCore.Server.Internal.DefaultGrpcServiceActivator`1.<>c.<.cctor>b__4_0()
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
         at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
         at System.Lazy`1.CreateValue()
         at System.Lazy`1.get_Value()
         at Grpc.AspNetCore.Server.Internal.DefaultGrpcServiceActivator`1.Create(IServiceProvider serviceProvider)
         at Grpc.Shared.Server.DuplexStreamingServerMethodInvoker`3.ResolvedInterceptorInvoker(IAsyncStreamReader`1 requestStream, IServerStreamWriter`1 responseStream, ServerCallContext resolvedContext)
         at Grpc.Shared.Server.DuplexStreamingServerMethodInvoker`3.ResolvedInterceptorInvoker(IAsyncStreamReader`1 requestStream, IServerStreamWriter`1 responseStream, ServerCallContext resolvedContext)
         at Grpc.Shared.Server.InterceptorPipelineBuilder`2.<>c__DisplayClass3_0.<<DuplexStreamingPipeline>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Grpc.Shared.Server.InterceptorPipelineBuilder`2.<>c__DisplayClass3_0.<<DuplexStreamingPipeline>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Grpc.Shared.Server.DuplexStreamingServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, IAsyncStreamReader`1 requestStream, IServerStreamWriter`1 responseStream)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.DuplexStreamingServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo'
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST http://localhost:801/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo application/grpc -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST http://localhost:801/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo application/grpc - - 200 0 application/grpc 117.8488ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo'
fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'ServerReflectionInfo'.
      System.InvalidOperationException: Multiple constructors accepting all given argument types have been found in type 'Grpc.Reflection.ReflectionServiceImpl'. There should only be one applicable constructor.
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.TryFindMatchingConstructor(Type instanceType, Type[] argumentTypes, ConstructorInfo& matchingConstructor, Nullable`1[]& parameterMap)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.FindApplicableConstructor(Type instanceType, Type[] argumentTypes, ConstructorInfo& matchingConstructor, Nullable`1[]& matchingParameterMap)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory(Type instanceType, Type[] argumentTypes)
         at Grpc.AspNetCore.Server.Internal.DefaultGrpcServiceActivator`1.<>c.<.cctor>b__4_0()
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
      --- End of stack trace from previous location ---
         at System.Lazy`1.CreateValue()
         at System.Lazy`1.get_Value()
         at Grpc.AspNetCore.Server.Internal.DefaultGrpcServiceActivator`1.Create(IServiceProvider serviceProvider)
         at Grpc.Shared.Server.DuplexStreamingServerMethodInvoker`3.ResolvedInterceptorInvoker(IAsyncStreamReader`1 requestStream, IServerStreamWriter`1 responseStream, ServerCallContext resolvedContext)
         at Grpc.Shared.Server.DuplexStreamingServerMethodInvoker`3.ResolvedInterceptorInvoker(IAsyncStreamReader`1 requestStream, IServerStreamWriter`1 responseStream, ServerCallContext resolvedContext)
         at Grpc.Shared.Server.InterceptorPipelineBuilder`2.<>c__DisplayClass3_0.<<DuplexStreamingPipeline>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Grpc.Shared.Server.InterceptorPipelineBuilder`2.<>c__DisplayClass3_0.<<DuplexStreamingPipeline>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Grpc.Shared.Server.DuplexStreamingServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, IAsyncStreamReader`1 requestStream, IServerStreamWriter`1 responseStream)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.DuplexStreamingServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST http://localhost:801/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo application/grpc - - 200 0 application/grpc 7.3135ms
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc-dotnet/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
I'm trying to use grpc reflection in a project but this exception is being thrown above. I tested with postman and evans, and in both cases the same exception was thrown.
Postman:
![image](https://user-images.githubusercontent.com/7685159/167473472-20dc85fe-8177-4194-a0b6-b18787520112.png)

Evans:
![image](https://user-images.githubusercontent.com/7685159/167473540-23e24513-c8e5-4f92-af28-3a804c83a555.png)

**Comment by JamesNK** [comment]
Great. I'm going to reopen this as there might be something we can do to make the error message clearer in the future.

**Comment by danielvieiravega** [comment]
> Great. I'm going to reopen this as there might be something we can do to make the error message clearer in the future.

Nice, I opened this [PR](https://github.com/grpc/grpc-dotnet/pull/1732) to display a better error message.
