### ISSUE TITLE
gRPC C# .NET Framework issue "The server returned an invalid or unrecognized response"

### ISSUE THREAD

**Issue by Livius90** [grpc/grpc-dotnet#1733]
Hi!

I like to test a gRPC client in C# .NET Framework 4.7.2. I am using WinHttpHandler as was mentioned in [this official example](https://docs.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-6.0#net-framework).

I am using a Windows 10 21H2 and i downloaded the WinHttpHandler 6.0.1 from nuget. My proto file and generated sources are perfect because i could use it in .NET 5.0 project and in Python, well.

I got the following exception when my code try to call a gRPC method:
```console
Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. WinHttpException: Error 12152 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The server returned an invalid or unrecognized response'.", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Error 12152 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The server returned an invalid or unrecognized response'.
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequestAsync>d__122.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Grpc.Net.Client.Internal.GrpcCall`2.<RunCall>d__73.MoveNext() in /_/src/Grpc.Net.Client/Internal/GrpcCall.cs:line 493")
```

### What version of gRPC and what language are you using?
Grpc.Net.Client 2.45.0; C# .NET Framework 4.7.2

### What operating system (Linux, Windows,...) and version?
Windows 10 21H2

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
Visual Studio 2019 project; C# .NET Framework 4.7.2

### What did you do?
following WinHttpHandler [official example](https://docs.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-6.0#net-framework).

### What did you expect to see?
a returned string value from my gRPC method call

### What did you see instead?
HttpRequestException

**Comment by BrennanConroy** [comment]
Could you please include logs of the client and server?
https://docs.microsoft.com/aspnet/core/grpc/diagnostics?view=aspnetcore-6.0

**Comment by Livius90** [comment]
My server is implemented in Python, so for it i could quickly get it. I used the following environment variables:
```console
GRPC_VERBOSITY=DEBUG
GRPC_TRACE=http
```

```console
running the gRPC server
D0511 00:24:12.338000000  6472 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "grpclb"
D0511 00:24:12.342000000  6472 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "rls_experimental"
D0511 00:24:12.346000000  6472 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "priority_experimental"
D0511 00:24:12.351000000  6472 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "weighted_target_experimental"
D0511 00:24:12.357000000  6472 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "pick_first"
D0511 00:24:12.360000000  6472 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "round_robin"
D0511 00:24:12.363000000  6472 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "ring_hash_experimental"
D0511 00:24:12.369000000  6472 src/core/ext/xds/certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher"
D0511 00:24:12.373000000  6472 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "cds_experimental"
D0511 00:24:12.376000000  6472 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "xds_cluster_impl_experimental"
D0511 00:24:12.381000000  6472 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "xds_cluster_resolver_experimental"
D0511 00:24:12.387000000  6472 src/core/ext/filters/client_channel/lb_policy_registry.cc:42] registering LB policy factory for "xds_cluster_manager_experimental"
D0511 00:24:12.391000000  6472 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc:162] Using native dns resolver
Press Enter to stop server ...
I0511 00:24:34.042000000  1652 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:795] W:0000013175372FF0 SERVER [ipv6:[fe80::c71:4753:5f88:98aa%256]:58312] state IDLE -> WRITING [TRANSPORT_FLOW_CONTROL]
I0511 00:24:34.060000000  1652 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:795] W:0000013175372FF0 SERVER [ipv6:[fe80::c71:4753:5f88:98aa%256]:58312] state WRITING -> WRITING+MORE [INITIAL_WRITE]
I0511 00:24:34.070000000  1652 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1955] perform_transport_op[t=0000013175372FF0]:  START_CONNECTIVITY_WATCH:watcher=0x1317360a6c0:from=IDLE SET_ACCEPT_STREAM:0x7ffce9039c80(0x13175361688,...)
I0511 00:24:34.082000000  1652 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:795] W:0000013175372FF0 SERVER [ipv6:[fe80::c71:4753:5f88:98aa%256]:58312] state WRITING+MORE -> WRITING [begin write in current thread]
I0511 00:24:34.091000000  1652 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:795] W:0000013175372FF0 SERVER [ipv6:[fe80::c71:4753:5f88:98aa%256]:58312] state WRITING -> IDLE [finish writing]
I0511 00:24:34.097000000  1652 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:2969] transport 0000013175372FF0 set connectivity_state=4
I0511 00:24:34.101000000  1652 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1955] perform_transport_op[t=0000013175372FF0]:  SET_ACCEPT_STREAM:(nil)((nil),...)
```

**Comment by JamesNK** [comment]
What about logs for the client?

Is the server and client using TLS? TLS is required with WinHttpHandler.

**Comment by Livius90** [comment]
I would like to use gRPC between a C# .NET Framework (WinHttpHandler) client and a Python server. I had not used any TLS settings, i just used it in local network over http://.

**Comment by JamesNK** [comment]
TLS is required. There isn't a workaround. This is why you are getting an error.

**Comment by Livius90** [comment]
Can you provide a doc/example link about how to configure it in C# .NET Framework (WinHttpHandler) client and Python server?

**Comment by JamesNK** [comment]
WinHttpHandler + gRPC docs are here: https://docs.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-6.0#net-framework

Adding docs about configuring Python to use TLS doesn't make sense here.

**Comment by Livius90** [comment]
Thanks the infos. I could generate crt and key for my server in Linux. My gRPC method is working well between my Python client and Python server with my credentials in my first test.

But in C# .NET Framework client i need to use TLSv1, it seems to me my Python server wants to use any other because i have the following problem in Python server error log. Can you help in how can i force to use TLSv1 in Python3 gRPC server?

```console
E0511 14:59:33.778000000 22892 src/core/tsi/ssl_transport_security.cc:1495] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f0:SSL routines:OPENSSL_internal:UNSUPPORTED_PROTOCOL.
```

This is my code for C# .NET Framework (WinHttpHandler), it should be right, i think:
```cs
WinHttpHandler handler = new WinHttpHandler()
{
	SslProtocols = SslProtocols.Tls,
	WindowsProxyUsePolicy = WindowsProxyUsePolicy.DoNotUseProxy
};

X509Certificate2 cert = new X509Certificate2("server.crt");
handler.ClientCertificates.Add(cert);
GrpcChannelOptions options = new GrpcChannelOptions() { HttpHandler = handler };

this.channel = GrpcChannel.ForAddress(this.textBox_url.Text, options);
this.client = new GExchange.GExchangeClient(this.channel);
```

In my gRPC method call in C# i got the follwoing exception then i can see the unsupported protocol message in my Python server.

```console
Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. WinHttpException: Error 12029 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'A connection with the server could not be established'.", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Error 12029 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'A connection with the server could not be established'.
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequestAsync>d__122.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Grpc.Net.Client.Internal.GrpcCall`2.<RunCall>d__73.MoveNext() in /_/src/Grpc.Net.Client/Internal/GrpcCall.cs:line 493")
```

**Comment by Livius90** [comment]
I found that grpc-dotnet require a [Windows 10 Build 19622 or later](https://docs.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-6.0#net-framework) which is available only from Windows Insider. So this is the reason why not work on Windows 10 21H2 for me.
https://en.wikipedia.org/wiki/Windows_10_version_history

**Comment by p1x31** [comment]
if anyone will meet the same problem again here is a [solution](https://github.com/dotnet/runtime/issues/102452#issuecomment-2126770795)
