### ISSUE TITLE
MissingMethodException when client loaded in the LoadFrom context

### ISSUE THREAD

**Issue by silentone** [grpc/grpc-dotnet#1739]
### What version of gRPC and what language are you using?
2.45.0
C#

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
Microsoft.WindowsDesktop.App 6.0.5

### What did you do?
1. Load the assembly containing the class using the grpc client with AssemblyLoadContext.LoadFromAssemblyName()
2. Create the class using the grpc client with Activator.CreateInstance()
3. Send a message across the channel.

### What did you expect to see?
The message is sent successfully.

### What did you see instead?
First message sent over throws when trying to write to the channel.

Status(StatusCode="Internal", Detail="Error starting gRPC call. MissingMethodException: Method not found: 'Void Google.Protobuf.MessageExtensions.WriteTo(Google.Protobuf.IMessage, System.Buffers.IBufferWriter`1<Byte>)'.", DebugException="System.MissingMethodException: Method not found: 'Void Google.Protobuf.MessageExtensions.WriteTo(Google.Protobuf.IMessage, System.Buffers.IBufferWriter`1<Byte>)'.
   at ImagineSolutions.Encapture.ImageProcessing.Systems.Scanning.GdPictureTwain.Scanner.__Helper_SerializeMessage(IMessage message, SerializationContext context)
   at Grpc.Net.Client.StreamExtensions.WriteMessageAsync[TMessage](Stream stream, GrpcCall call, TMessage message, Action`2 serializer, CallOptions callOptions)
   at Grpc.Net.Client.Internal.PushUnaryContent`2.WriteMessageCore(ValueTask writeMessageTask)
   at System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")

*Note that it works fine when directly referencing my class that uses the grpc client.
*This also works fine if I rebuild Google.protobuf targetting .net 6 (the latest stable nuget package only targets .net 5) and load it into the loadfrom context.

**Comment by silentone** [comment]
Closing, there were some unrelated assembly loading issues involved.
