### ISSUE TITLE
RpcException seems to put inner exception details in the exception message but leaves InnerException property as null

### ISSUE THREAD

**Issue by jonathanou** [grpc/grpc-dotnet#1776]
When making a grpc call, I am trying to provide user friendly messages when the server address is not reachable or the connection times out.

However, in both cases the rpc exception returns status code of "Unavailable", and the HResult property has the same value.  I tried to read the `InnerException` property to help distinguish between the two cases, but found that the property is null.

The only information I have right now is in the exception `Message` property, where the `HttpRequestException` message is appended.  For example:

```
Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (192.168.132.127:64873) SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", DebugException="System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (192.168.132.127:64873)
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
```

So right now it seems I have to parse the exception message to know the exact reason of the `RpcException`.  However, `HttpRequestException.Message` is localized and makes it unsuitable for parsing if not in English language.

Is it possible to assign the caught `HttpRequestException` into the `RpcException.InnerException`?  Having access to the inner `HttpRequestException` will allow me to programmatically determine the reason of the exception.  For example, in the case of a connection time out, the `HttpRequestException` caught has `InnerException` of `SocketException` which has a property `SocketErrorCode` of `Timeout`.

**Comment by JamesNK** [comment]
You can access the exception via `RpcException.Status.DebugException`.

**Comment by jonathanou** [comment]
Ah ok, thanks for the tip!  That was definitely buried a bit deep, but happy to have access to the inner exception nonetheless!

**Comment by jonathanou** [comment]
Although I did see this in the property documentation:

```cs
//     ...Note that this field is available only
//     for debugging purposes, the application logic should never rely on values of
//     this field (it should use StatusCode and Detail instead). Example: when a client
//     fails to connect to a server, this field may provide additional details why the
//     connection to the server has failed. Note: experimental API that can change or
//     be removed without any prior notice.
```

I will use `DebugException` for now but I think ideally setting `InnerException` may be better?

**Comment by JamesNK** [comment]
There is an issue for doing that here: https://github.com/grpc/grpc/issues/25740

Using DebugException is fine. Either way, it would be the same exception.

**Comment by jonathanou** [comment]
Sounds good!  Hopefully `DebugException` won't get removed anytime soon since it's considered "experimental".  Thank you for your help!
