### ISSUE TITLE
RPC failed: Status{code=INTERNAL, description=http2 exception, cause=io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f

### ISSUE THREAD

**Issue by hareesha-smarsh** [grpc/grpc-dotnet#1823]
Created gRPC server in dotnet and am trying to connect from java client, getting below exception :

RPC failed: Status{code=INTERNAL, description=http2 exception, cause=io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:108)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:338)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:239)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
}

**Comment by JamesNK** [comment]
I'm guessing there is a mismatch between TLS or HTTP protocol. e.g. your server is using HTTP/1.1. Or your server is using TLS, and your client isn't.

* https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-6.0#mismatch-between-client-and-service-ssltls-configuration
* https://docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-6.0&tabs=visual-studio#protocol-negotiation

**Comment by hareesha-smarsh** [comment]
Hi @JamesNK ,

Am below setting:

![image](https://user-images.githubusercontent.com/96460599/179474660-b8bf2f9d-6bcf-42e8-87f5-6fa32755c4d0.png)

![image](https://user-images.githubusercontent.com/96460599/179474354-4ce19060-c902-45a3-bbee-ed936cce2f91.png)

**Comment by hareesha-smarsh** [comment]
when I access http://localhost:8951/ am getting below response:

Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909

![image](https://user-images.githubusercontent.com/96460599/179479294-b76972fa-4914-409d-88af-af1c37cfbff1.png)

But not able to connect from java-grpc-client, pls help here.

**Comment by JamesNK** [comment]
The problem is your server is using HTTP/1.1.

https://docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-6.0&tabs=visual-studio#protocol-negotiation

**Comment by hareesha-smarsh** [comment]
thank you very much for quick response, please tell me how to fix this.

- does it connect if client is also HTTP/1.1?
- need to enable TLS?

please suggest.

**Comment by hareesha-smarsh** [comment]
Hi @JamesNK ,

I don't want to enable TLS and I set HttpProtocols.Http2 like below but still not able to connect to server.

![image](https://user-images.githubusercontent.com/96460599/179535229-b9cd063b-7fd8-408a-8650-d3380c69eb04.png)

**Comment by JamesNK** [comment]
I don't know what is going on. The server should be doing HTTP/2 without TLS.

Ideas:
1. Enable server logging at trace level and see what the server is logging for hints
2. Use Wireshark to see what the client and server are sending each other.
3. I don't have experience with the Java client. You could ask the people who maintain the Java client for more information about what is going on.

**Comment by JamesNK** [comment]
Closing because of lack of activity.
