### ISSUE TITLE
gRPC .NET Standard 2.0 with UWP throws an exception

### ISSUE THREAD

**Issue by jefflhp** [grpc/grpc-dotnet#1824]
I am following this documentation to try and develop a UWP solution that is based on Grpc.Net.Client and not Grpc.Core.
https://docs.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-6.0#additional-resources

When I try and talk to the server it throws an exception. The solutions works with netstandard1.5 and Gprc.Core.

These are the nuget packages I'm including based on the documentation.
![image](https://user-images.githubusercontent.com/20073177/179321382-60d7be82-ddca-40e7-b480-f9c50dd0b1ee.png)

![image](https://user-images.githubusercontent.com/20073177/179321321-0bf3d4d5-9199-43c6-82ac-c771c58c1867.png)

Grpc.Core.RpcException
  HResult=0x80131500
  Message=Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. Exception: The text associated with this error code could not be found.

The connection with the server was terminated abnormally
", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Exception: The text associated with this error code could not be found.

The connection with the server was terminated abnormally

   at System.Net.Http.HttpHandlerToFilter.SendAsync(HttpRequestMessage request, CancellationToken cancel)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Web.GrpcWebHandler.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
  Source=Grpc.Net.Client
  StackTrace:
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at App2Uwp.Greeter.GreeterClient.SayHello(HelloRequest request, CallOptions options) in C:\code\cpp\grpc\gRPCMixlang\GreetingTwo\obj\Debug\netstandard2.0\HelloworldGrpc.cs:line 186
   at App2Uwp.Greeter.GreeterClient.SayHello(HelloRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in C:\code\cpp\grpc\gRPCMixlang\GreetingTwo\obj\Debug\netstandard2.0\HelloworldGrpc.cs:line 175
   at App2Uwp.MainPage.OnGrpcHelloClick(Object sender, RoutedEventArgs e) in C:\code\cpp\grpc\gRPCMixlang\App2Uwp\MainPage.xaml.cs:line 53

  This exception was originally thrown at this call stack:
    [External Code]
    App2Uwp.Greeter.GreeterClient.SayHello(App2Uwp.HelloRequest, Grpc.Core.CallOptions) in HelloworldGrpc.cs
    App2Uwp.Greeter.GreeterClient.SayHello(App2Uwp.HelloRequest, Grpc.Core.Metadata, System.DateTime?, System.Threading.CancellationToken) in HelloworldGrpc.cs
    App2Uwp.MainPage.OnGrpcHelloClick(object, Windows.UI.Xaml.RoutedEventArgs) in MainPage.xaml.cs

This is the main app.
```
using Grpc.Net.Client;
using Grpc.Net.Client.Web;
using System.Net.Http;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;

namespace App2Uwp
{
   public sealed partial class MainPage : Page
    {
        GrpcChannel _channel;
        Greeter.GreeterClient _client;
        public MainPage()
        {
            this.InitializeComponent();

            _channel = GrpcChannel.ForAddress("http://localhost:50051", new GrpcChannelOptions
            {
                HttpHandler = new GrpcWebHandler(new HttpClientHandler())
            });
            _client = new Greeter.GreeterClient(_channel);
        }     
        private void OnGrpcHelloClick(object sender, RoutedEventArgs e)
        {
            var reply = _client.SayHello(new HelloRequest { Name = "jeffl v2" });
            helloTextBlock.Text = "Server Reply: " + reply.Message;
        }  
    }
}
```

I did try replacing HttpClientHandler with WinHttpHandler but still got an exception.

I can provide the project files if necessary.

**Comment by JamesNK** [comment]
UWP doesn't support HTTP/2 so the server must be configured to use HTTP/1.1 with port 50051.

**Comment by jefflhp** [comment]
James, thanks for the reply. Do you have any documentation or links on how best to setup HTTP/1.1 for the server? I'm using a server based on a c++ implementation. 

Here is the core code.
```
void RunServer() {
	std::string server_address("0.0.0.0:50051");
	GreeterServiceImpl service;

	grpc::EnableDefaultHealthCheckService(true);
	grpc::reflection::InitProtoReflectionServerBuilderPlugin();
	ServerBuilder builder;

	builder.SetMaxMessageSize(1024 * 1024 * 1024);
	// Listen on the given address without any authentication mechanism.
	builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
	// Register "service" as the instance through which we'll communicate with
	// clients. In this case it corresponds to an *synchronous* service.
	builder.RegisterService(&service);
	// Finally assemble the server.
	std::unique_ptr<Server> server(builder.BuildAndStart());
	std::cout << "Server listening on " << server_address << std::endl;

	// Wait for the server to shutdown. Note that some other thread must be
	// responsible for shutting down the server for this call to ever return.

	server->Wait();
}
```

**Comment by JamesNK** [comment]
When using gRPC-Web both the client and server need to support it. Grpc Core doesn't have built-in support for gRPC-Web. You need to use a proxy like Envoy + its gRPC-Web plugin to translate it back to regular HTTP/2 gRPC.

**Comment by JamesNK** [comment]
I've added some notes to the docs to make this requirement clearer:

* https://github.com/dotnet/AspNetCore.Docs/pull/26450
* https://github.com/dotnet/AspNetCore.Docs/pull/26451

**Comment by JamesNK** [comment]
> @JamesNK Thanks for the information. Are there plans for UWP and Grpc.Net.Client to support HTTP/2?

Not that I know of.

**Comment by JamesNK** [comment]
Closing because of lack of activity.
