### ISSUE TITLE
Unable to access ClusterIP grpc service in Kubernetes Desktop

### ISSUE THREAD

**Issue by VenkateshSrini** [grpc/grpc-dotnet#1874]
Hi All,

I have created two projects at [Grpc File Cache](https://github.com/VenkateshSrini/GRpcFileCache). [CacheService](https://github.com/VenkateshSrini/GRpcFileCache/tree/main/CacheService) is the gRpc service. On Kubernetes, it is deployed as ClusterIP service. The service [CacheServiceWebProxy](https://github.com/VenkateshSrini/GRpcFileCache/tree/main/CacheServiceWebProxy). On Kubernetes, it is deployed as LoadBalancer. They both are deployed on the same namespace. But he CacheServiceWebProxy is not able to access GRpcFileCache code
### What version of gRPC and what language are you using?
C# 10.0

### What operating system (Linux, Windows,...) and version?
WSL Ubuntu 20, Docker Desktop with Kubernetes enabled. Kubernetes version 1.24.2 

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET 6

### What did you do?

1. Deployed the CacheService as cluster ip service. It uses gRpc protocol. The [cache service deployment.yaml](https://github.com/VenkateshSrini/GRpcFileCache/blob/main/CacheService/file-cache-deploy.yaml) and [cache service service.yaml](https://github.com/VenkateshSrini/GRpcFileCache/blob/main/CacheService/file-cache-grpc-service.yaml)
2. Deployed the CacheServiceWebProxy as LoadBalancer. It acts as proxy CacheService. The [deployment.yaml](https://github.com/VenkateshSrini/GRpcFileCache/blob/main/CacheServiceWebProxy/file-cache-client-deploy.yaml) and [service.yaml](https://github.com/VenkateshSrini/GRpcFileCache/blob/main/CacheServiceWebProxy/file-cache-client-service.yaml)
### What did you expect to see?
The service-to-service communication between CacheServiceWebProxy to CacheService should succed and work.

### What did you see instead?
The service-to-service communication between is failed. The following is log 
`fail: Grpc.Net.Client.Internal.GrpcCall[6]
      Error starting gRPC call.
      Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error connecting to subchannel.", DebugException="System.Net.Sockets.SocketException (111): Connection refused
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
         at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)")
         at Grpc.Net.Client.Balancer.Internal.ConnectionManager.PickAsync(PickContext context, Boolean waitForReady, CancellationToken cancellationToken)
         at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
info: Grpc.Net.Client.Internal.GrpcCall[3]
      Call failed with gRPC error status. Status code: 'Unavailable', Message: 'Error connecting to subchannel.'.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMKF7GSKJ5I2", Request id "0HMKF7GSKJ5I2:00000004": An unhandled exception was thrown by the application.
      Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error connecting to subchannel.", DebugException="System.Net.Sockets.SocketException (111): Connection refused
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
         at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)")
         at Grpc.Net.Client.Balancer.Internal.ConnectionManager.PickAsync(PickContext context, Boolean waitForReady, CancellationToken cancellationToken)
         at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
         at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
         at Grpc.Net.ClientFactory.Internal.CallOptionsConfigurationInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
         at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
         at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
         at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
         at CacheClient.Cache.CacheClient.SetCache(StoreCacheRequest request, CallOptions options) in /src/obj/Release/net6.0/Proto/CacheGrpc.cs:line 126
         at CacheClient.Cache.CacheClient.SetCache(StoreCacheRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in /src/obj/Release/net6.0/Proto/CacheGrpc.cs:line 121
         at CacheServiceWebProxy.Cache.FileCache.Set(String key, String value, Int32 timePeriod) in /src/Cache/FileCache.cs:line 24
         at CacheServiceWebProxy.Controllers.CacheController.Post(ReqSet request) in /src/Controllers/CacheController.cs:line 22
         at lambda_method2(Closure , Object , Object[] )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)`

### Anything else we should know about your project / environment?
environment WSL, Docker, Docker on Desktop 1.24

**Comment by davidfowl** [comment]
This is the problem https://github.com/VenkateshSrini/GRpcFileCache/blob/5e9cb1e2b8a78c60fa15077cbb42521ac5f017ec/CacheService/Program.cs#L6

You need to use `ListenAnyIP` instead of `ListenLocalHost`, this will allow incoming connections outside of the container/pod itself.

**Comment by VenkateshSrini** [comment]
@davidfowl thanks it worked
