### ISSUE TITLE
Why is catch block called twice in Grpc Interceptor C#?

### ISSUE THREAD

**Issue by jangarach** [grpc/grpc-dotnet#1895]
I ran into a problem when I started to implement a global error handler for the grpc server service. The problem is that when I get a validation error, I don't want to log it, but I want to return an RpcException with information to the client, and in other Exceptions I log it and return an unhandled error. *The question* is why do I repeatedly get into the catch block **(Exception e)** after I caught the **ValidationException** and **threw the RpcException**? To the fact that it is called twice, the logic I described above breaks down for me.
The implementation is shown below:

```
public class ExceptionInterceptor : Interceptor
{
    private readonly ILogger<ExceptionInterceptor> _logger;

    public ExceptionInterceptor(ILogger<ExceptionInterceptor> logger)
    {
        _logger = logger;
    }

    public override async Task<TResponse> UnaryServerHandler<TRequest, TResponse>(
        TRequest request,
        ServerCallContext context,
        UnaryServerMethod<TRequest, TResponse> continuation)
    {
        try
        {
            return await continuation(request, context);
        }
        catch (ValidationException e)
        {
            var error = string.Join(Environment.NewLine, e.Errors.Select(p => p.ErrorMessage));
            throw new RpcException(new Status(StatusCode.InvalidArgument, error));
        }
        catch (Exception e)
        {
            _logger.LogError(e, "gRPC Exception");
            throw;
        }
    }
}
```
Interceptor registration:
```
services.AddGrpc(o =>
{
    o.Interceptors.Add<ExceptionInterceptor>();
});
```

**Comment by jangarach** [comment]
The reason was that when we register the interceptor globally, it fires twice. If we register it for a specific service, then it works once.The answer is:

```
services.AddGrpc()
    .AddServiceOptions<MyService>(o =>
    {
        o.Interceptors.Add<ExceptionInterceptor>();
    });
```

**Comment by JamesNK** [comment]
Thanks for investigating and providing an update. I'll look into why registering globally is behaving oddly.

**Comment by JamesNK** [comment]
I couldn't replicate this. When I register the interceptor and throw an error, the error is logged once:

```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Development\Source\grpc-dotnet\examples\Reflector\Server
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST https://localhost:5001/greet.Greeter/SayHello application/grpc -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - /greet.Greeter/SayHello'
fail: ExceptionInterceptor[0]
      gRPC Exception
      System.Exception: Exception of type 'System.Exception' was thrown.
         at Server.GreeterService.SayHello(HelloRequest request, ServerCallContext context) in C:\Development\Source\grpc-dotnet\examples\Reflector\Server\Services\GreeterService.cs:line 37
         at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)
         at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)
         at ExceptionInterceptor.UnaryServerHandler[TRequest,TResponse](TRequest request, ServerCallContext context, UnaryServerMethod`2 continuation) in C:\Development\Source\grpc-dotnet\examples\Reflector\Server\Program.cs:line 49
fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'SayHello'.
      System.Exception: Exception of type 'System.Exception' was thrown.
         at Server.GreeterService.SayHello(HelloRequest request, ServerCallContext context) in C:\Development\Source\grpc-dotnet\examples\Reflector\Server\Services\GreeterService.cs:line 37
         at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)
         at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)
         at ExceptionInterceptor.UnaryServerHandler[TRequest,TResponse](TRequest request, ServerCallContext context, UnaryServerMethod`2 continuation) in C:\Development\Source\grpc-dotnet\examples\Reflector\Server\Program.cs:line 49
         at Grpc.Shared.Server.InterceptorPipelineBuilder`2.<>c__DisplayClass5_0.<<UnaryPipeline>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Grpc.Shared.Server.InterceptorPipelineBuilder`2.<>c__DisplayClass5_0.<<UnaryPipeline>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /greet.Greeter/SayHello'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST https://localhost:5001/greet.Greeter/SayHello application/grpc - - 200 0 application/grpc 241.5595ms
```

Changes to register interceptor: https://github.com/JamesNK/grpc-dotnet/commit/387e5810f931a5ae9cac2f456370ec053b418531

**Comment by jangarach** [comment]
Hey James. Yes, indeed, in your commit, I could not achieve such behavior as mine. When registering services, I use StashBox, if you try to register a service like mine, then you should have this behavior:
```
var builder = WebApplication.CreateBuilder(args);
builder.Host
    .UseStashbox()
    .ConfigureServices(ConfigureServices);

var app = builder.Build();
app.MapGrpcService<GreeterService>();

app.Run();

static void ConfigureServices(HostBuilderContext context, IServiceCollection services)
{
    services.AddGrpc(o => o.Interceptors.Add<ExceptionInterceptor>());
}
```
I am using package: **Stashbox.Extensions.Hosting 4.2.3**
I kept it minimal for the sake of the example, but Stashbox is used for a more complex situation. If this is not within the scope of your work, then I will independently study this issue. In any case, thank you for helping to find the cause.

**Comment by JamesNK** [comment]
It sounds like a bug in Stashbox. I don't know anything about that.

**Comment by jangarach** [comment]
The problem turned out to be in the Stashbox package.
