### ISSUE TITLE
How to use a custom ConnectCallback?

### ISSUE THREAD

**Issue by ogxd** [grpc/grpc-dotnet#1974]
Hello,

It seems I cannot set a custom `ConnectCallback` in my `SocketsHttpHandler`. I have checked the sources (master) and I cannot find a way to avoid a validation error from `ValidateHttpHandlerSupportsConnectivity`.    

It seems there was a fix a year ago #1542, after which `BalancerHttpHandler` was changed to take the HttpHandlerType as an argument to avoid overriding the ConnectCallback. However, in the current main branch, it seems this code is not there anymore.    

How would you set a custom ConnectCallback using the latest version of this library?     
By the way, I don't need client-side load balancing for the use case I work with.     

Thanks in advance for your help! 😄

**Comment by JamesNK** [comment]
This sample uses it: https://github.com/grpc/grpc-dotnet/tree/master/examples#transporter

**Comment by ogxd** [comment]
Thank you!

**Comment by ogxd** [comment]
I get the same exception as in my sample, which happens when I try to read the Channel State:
```
System.InvalidOperationException: Channel is configured with an HTTP transport doesn't support client-side load balancing or connectivity state tracking. The underlying HTTP transport must be a SocketsHttpHandler with no SocketsHttpHandler.ConnectCallback configured. The HTTP transport must be configured on the channel using GrpcChannelOptions.HttpHandler.
   at Grpc.Net.Client.GrpcChannel.ValidateHttpHandlerSupportsConnectivity()
   at Grpc.Net.Client.GrpcChannel.get_State()
```

I just added this line to the Transporter sample:
```csharp
Console.WriteLine("Greeting: " + reply.Message);
Console.WriteLine("State: " + channel.State); // <--
```
