### ISSUE TITLE
Is this a valid Debug.Assert in Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.OnConnect?

### ISSUE THREAD

**Issue by pcwiese** [grpc/grpc-dotnet#1980]
A Debug.Assert is firing with a debug build. I added some additional information to the Assert (and replaced the actual address and port with x's and y's) and I get something that looks like this

```
Process terminated. Assertion failed.
Context endpoint Unspecified/[::ffff:x.x.x.x]:yyyyy should equal address endpoint Unspecified/::ffff:x.x.x.x:yyyyy.
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.OnConnect(SocketsHttpConnectionContext context, CancellationToken cancellationToken) in D:\src\grpc-dotnet\src\Grpc.Net.Client\Balancer\Internal\BalancerHttpHandler.cs:line 88
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.OnConnect(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
   at System.Net.Http.HttpConnectionPool.<>c__DisplayClass78_0.<CheckForHttp2ConnectionInjection>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

The only difference here are the brackets in the address. Is this a valid Debug.Assert?

**Comment by JamesNK** [comment]
I haven't seen that before. What address are you using?

**Comment by pcwiese** [comment]
We have a custom resolver which is feeding endpoints back through the ResolverResult action that look like these:
::ffff:10.x.x.x:400xx

**Comment by amcasey** [comment]
Triage: The IP address you're setting in your load balancer must be different from the one being passed in, resulting in this assert.  It looks like one of the values is missing the required square brackets?

**Comment by pcwiese** [comment]
> Triage: The IP address you're setting in your load balancer must be different from the one being passed in, resulting in this assert. It looks like one of the values is missing the required square brackets?

Is this a question for me Andrew? The only thing we are passing to grpc-dotnet is a set of endpoints without brackets. Somewhere inside grpc-dotnet, the brackets are showing up...

**Comment by JamesNK** [comment]
Can you add a code sample of an endpoint you're adding? IPv6 isn't usual, and I'd like to get as close as possible to what you're doing when investigating this.

**Comment by pcwiese** [comment]
Ultimately we are constructing the BalancerAddress like this:

```
new BalancerAddress(new DnsEndPoint(new IPAddress(s.IpAddress.Span).ToString(), s.Port)))
```

where s is the Server class generated from 
https://github.com/grpc/grpc-proto/blob/2e2e8ebbf4a10882547419c837a66225884458fe/grpc/lb/v1/load_balancer.proto#L131

and we end up constructing something specific like:
```
var endpoint = new System.Net.DnsEndPoint("::ffff:10.2.3.4", 40000);
```

instead of
```
var endpoint = new System.Net.DnsEndPoint("[::ffff:10.2.3.4]", 40000);
```

I'll see if I can just include the brackets...

**Comment by JamesNK** [comment]
Closing because of lack of activity.
