### ISSUE TITLE
Retrying immediately triggers a timeout

### ISSUE THREAD

**Issue by lobster2012-user** [grpc/grpc-dotnet#1989]
### What version of gRPC and what language are you using?
net6.0
grpc 2.50

### What operating system (Linux, Windows,...) and version?
windows 10

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
7.0.100

### What did you do?
I am in a loop trying to send a request using the same channel. The connection timeout is set to 5 seconds in the channel settings.

### What did you expect to see?
For a non-working address, a connection error will be triggered after the timeout set in the channel settings

### What did you see instead?
Starting from the second attempt, the connection error is thrown out IMMEDIATELY.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

13.12.2022 21:15:31
Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error connecting to subchannel.", DebugException="System.TimeoutException: A connection could not be established within the configured ConnectTimeout.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)
   --- End of inner exception stack trace ---")
   at Grpc.Net.Client.Balancer.Internal.ConnectionManager.PickAsync(PickContext context, Boolean waitForReady, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at GrpcGreeter.Greeter.GreeterClient.SayHello(HelloRequest request, CallOptions options) in C:\Dev\playground\tg_bot\GrpcTestApp\obj\Debug\net6.0\SampleGrpc.cs:line 119
   at GrpcGreeter.Greeter.GreeterClient.SayHello(HelloRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in C:\Dev\playground\tg_bot\GrpcTestApp\obj\Debug\net6.0\SampleGrpc.cs:line 108
13.12.2022 21:15:31

```
using Grpc.Core;
using Grpc.Net.Client.Balancer;
using Grpc.Net.Client;
using Microsoft.Extensions.DependencyInjection;
using GrpcGreeter;
using System.Linq.Expressions;
using Grpc.Net.Client.Configuration;

var factory = new StaticResolverFactory(addr => new[]
{
    new BalancerAddress("localhost", 81),
    new BalancerAddress("google.com", 82)
});

var services = new ServiceCollection();
services.AddSingleton<ResolverFactory>(factory);

var channel = GrpcChannel.ForAddress(
    "static:///my-example-host",
    new GrpcChannelOptions
    {
        Credentials = ChannelCredentials.Insecure,
        ServiceProvider = services.BuildServiceProvider(),
        ServiceConfig = new ServiceConfig { LoadBalancingConfigs = { new RoundRobinConfig() } },
        HttpHandler = new SocketsHttpHandler
        {
            ConnectTimeout = TimeSpan.FromSeconds(5)
        }
    });

while (true)
{
    try
    {
        var client = new Greeter.GreeterClient(channel);
        Console.WriteLine(DateTime.Now.ToString());
        client.SayHello(new HelloRequest { Name = "Hello" });
    }
    catch(Exception ex)
    {
        Console.WriteLine(ex);
    }
    Console.WriteLine(DateTime.Now.ToString());
    await Task.Delay(TimeSpan.FromSeconds(5));
}
```

**Comment by ttohin** [comment]
I see the same issue. I have a suspicion that even if the address became working, the channel won't reconnect.

**Comment by pietjan12** [comment]
@JamesNK is there an estimate for when this fix will be released?

**Comment by JamesNK** [comment]
The next release. A pre-release should happen soon. Probably next week.

**Comment by denisivan0v** [comment]
@JamesNK are you planning to publish the pre-release this week?
