### ISSUE TITLE
.NET6 gRPC intermittent failure.

### ISSUE THREAD

**Issue by careless6666** [grpc/grpc-dotnet#1990]
I have error like in this issue, where no anwer
https://github.com/grpc/grpc-dotnet/issues/1710

I try to make client 2 ways:
old varian Grpc.core and modern via Grpc.Net.Client
old varian work ok, but new varian return error:
info from my logs:

info: Aer.Platform.Grpc.Interceptors.ClientLoggingInterceptor[106]
      GrpcRequest logged
dbug: Grpc.Net.Client.Internal.GrpcCall[1]
      Starting gRPC call. Method type: 'Unary', URI: 'http://loadbalancer.temporary.invalid/aer.dev.rt_config.RtConfigService/Ping'.
trce: Grpc.Net.Client.Balancer.PollingResolver[1]
      DnsResolver refresh requested.
trce: Grpc.Net.Client.Balancer.DnsResolver[2]
      Starting DNS query to get hosts from 'any.dev-rt-config-feature-debug-dotnet.dev.svc.dev1.company.domain'.
dbug: MicroElements.Swashbuckle.FluentValidation.FluentValidationRules[0]
      FluentValidationRules Created
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'http://localhost:5000'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:82
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:5000
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:84
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Local
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/alexander.usov/Documents/ae/gitlab/playground/rt-config-dotnet-client/src/Aer.RtConfig.DotnetService.Aer
dbug: Grpc.Net.Client.Balancer.DnsResolver[3]
      Received 2 DNS results from 'any.dev-rt-config-feature-debug-dotnet.dev.svc.dev1.company.domain'. Results: 10.41.132.209, 10.41.155.249
trce: Grpc.Net.Client.Balancer.PollingResolver[4]
      DnsResolver result with status code 'OK' and 2 addresses.
dbug: Grpc.Net.Client.Balancer.Subchannel[1]
      Subchannel id '1' created with addresses: 10.41.132.209:80
dbug: Grpc.Net.Client.Balancer.Subchannel[1]
      Subchannel id '2' created with addresses: 10.41.155.249:80
trce: Grpc.Net.Client.Balancer.Subchannel[4]
      Subchannel id '1' connection requested.
dbug: Grpc.Net.Client.Balancer.Subchannel[11]
      Subchannel id '1' state changed to Connecting. Detail: 'Connection requested.'.
trce: Grpc.Net.Client.Balancer.RoundRobinBalancer[1]
      Processing subchannel id '1' state changed to Connecting. Detail: 'Connection requested.'.
dbug: Grpc.Net.Client.Balancer.Internal.ConnectionManager[3]
      Channel state updated to Connecting.
dbug: Grpc.Net.Client.Balancer.Internal.ConnectionManager[4]
      Channel picker updated.
trce: Grpc.Net.Client.Balancer.Subchannel[6]
      Subchannel id '1' connecting to transport.
trce: Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport[1]
      Subchannel id '1' connecting socket to 10.41.132.209:80.
trce: Grpc.Net.Client.Balancer.Subchannel[4]
      Subchannel id '2' connection requested.
dbug: Grpc.Net.Client.Balancer.Subchannel[11]
      Subchannel id '2' state changed to Connecting. Detail: 'Connection requested.'.
trce: Grpc.Net.Client.Balancer.RoundRobinBalancer[1]
      Processing subchannel id '2' state changed to Connecting. Detail: 'Connection requested.'.
trce: Grpc.Net.Client.Balancer.Subchannel[6]
      Subchannel id '2' connecting to transport.
trce: Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport[1]
      Subchannel id '2' connecting socket to 10.41.155.249:80.
trce: Grpc.Net.Client.Balancer.Internal.ConnectionManager[5]
      Pick started.
dbug: Grpc.Net.Client.Balancer.Internal.ConnectionManager[8]
      Picked queued.
trce: Grpc.Net.Client.Balancer.Internal.ConnectionManager[11]
      Waiting for a new picker.
dbug: Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport[2]
      Subchannel id '1' connected to socket 10.41.132.209:80.
dbug: Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport[2]
      Subchannel id '2' connected to socket 10.41.155.249:80.
dbug: Grpc.Net.Client.Balancer.Subchannel[11]
      Subchannel id '1' state changed to Ready. Detail: 'Successfully connected to socket.'.
trce: Grpc.Net.Client.Balancer.RoundRobinBalancer[1]
      Processing subchannel id '1' state changed to Ready. Detail: 'Successfully connected to socket.'.
dbug: Grpc.Net.Client.Balancer.Internal.ConnectionManager[3]
      Channel state updated to Ready.
dbug: Grpc.Net.Client.Balancer.Internal.ConnectionManager[4]
      Channel picker updated.
dbug: Grpc.Net.Client.Balancer.Subchannel[11]
      Subchannel id '2' state changed to Ready. Detail: 'Successfully connected to socket.'.
trce: Grpc.Net.Client.Balancer.RoundRobinBalancer[1]
      Processing subchannel id '2' state changed to Ready. Detail: 'Successfully connected to socket.'.
dbug: Grpc.Net.Client.Balancer.Internal.ConnectionManager[4]
      Channel picker updated.
trce: Grpc.Net.Client.Balancer.Internal.ConnectionManager[5]
      Pick started.
dbug: Grpc.Net.Client.Balancer.Internal.ConnectionManager[6]
      Successfully picked subchannel id '1' with address 10.41.132.209:80.
Request:
Method: POST, RequestUri: 'http://10.41.132.209/aer.dev.rt_config.RtConfigService/Ping', Version: 2.0, Content: Grpc.Net.Client.Internal.PushUnaryContent`2[Aer.Dev.RtConfig.RTPingRequest,Aer.Dev.RtConfig.RTPingResponse], Headers:
{
  User-Agent: grpc-dotnet/2.47.0 (.NET 6.0.6; CLR 6.0.6; net6.0; osx; arm64)
  TE: trailers
  grpc-accept-encoding: identity,gzip,deflate
  Content-Type: application/grpc
}
dbug: Grpc.Net.Client.Internal.GrpcCall[18]
      Sending message.
trce: Grpc.Net.Client.Internal.GrpcCall[21]
      Serialized 'Aer.Dev.RtConfig.RTPingRequest' to 374 byte message.
trce: Grpc.Net.Client.Internal.GrpcCall[19]
      Message sent.
v
�eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlIjoicGxheWdyb3VuZC1ydC1jb25maWctZG90bmV0LWNsaWVudCIsImNyZWF0ZV9hdCI6IjIwMjEtMDgtMDUgMTU6MDQ6MzcuMDQ4MTAwMTA3ICswMDAwIFVUQyBtPSs5MjE5NS4zODg4MTE2MDEifQ.HDvZwy-W6s_SEmF8zR2zpxFzNvx_hVncknzIm5Qnfsd0Ndzb7paBKYmRcqTrZtr0wMJugpu7afgWDeqBwuBpWd4izfXWYCT1QIQPG74ydr6MptNVv5UcSlTldlkCHRNc0hWs5IsvF4UBZGrdK3-H60SGKXZn0K37ceTnKJXPj_g
AttributeContext.Types.Request headers:
User-Agent: grpc-dotnet/2.47.0 (.NET 6.0.6; CLR 6.0.6; net6.0; osx; arm64)
TE: trailers
grpc-accept-encoding: identity,gzip,deflate

trce: Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport[7]
      Subchannel id '1' creating stream for 10.41.132.209:80.
trce: Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport[8]
      Subchannel id '1' disposing stream for 10.41.132.209:80.
dbug: Grpc.Net.Client.Balancer.Subchannel[11]
      Subchannel id '1' state changed to Idle. Detail: 'Disconnected.'.
trce: Grpc.Net.Client.Balancer.RoundRobinBalancer[1]
      Processing subchannel id '1' state changed to Idle. Detail: 'Disconnected.'.
dbug: Grpc.Net.Client.Balancer.Internal.ConnectionManager[4]
      Channel picker updated.
trce: Grpc.Net.Client.Balancer.RoundRobinBalancer[4]
      Refreshing resolver because subchannel id '1' is in state Idle.
trce: Grpc.Net.Client.Balancer.PollingResolver[1]
      DnsResolver refresh requested.
dbug: Grpc.Net.Client.Balancer.DnsResolver[1]
      Starting rate limit delay of 00:00:14.1908420. DNS resolution rate limit is once every 00:00:15.
trce: Grpc.Net.Client.Balancer.RoundRobinBalancer[5]
      Requesting connection for subchannel id '1' because it is in state Idle.
trce: Grpc.Net.Client.Balancer.Subchannel[4]
      Subchannel id '1' connection requested.
dbug: Grpc.Net.Client.Balancer.Subchannel[11]
      Subchannel id '1' state changed to Connecting. Detail: 'Connection requested.'.
trce: Grpc.Net.Client.Balancer.RoundRobinBalancer[1]
      Processing subchannel id '1' state changed to Connecting. Detail: 'Connection requested.'.
dbug: Grpc.Net.Client.Balancer.Internal.ConnectionManager[4]
      Channel picker updated.
trce: Grpc.Net.Client.Balancer.Subchannel[6]
      Subchannel id '1' connecting to transport.
trce: Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport[1]
      Subchannel id '1' connecting socket to 10.41.132.209:80.
fail: Grpc.Net.Client.Internal.GrpcCall[6]
      Error starting gRPC call.
      System.Net.Http.HttpRequestException: An error occurred while sending the request.
       ---> System.IO.IOException: The request was aborted.
       ---> System.IO.IOException: The response ended prematurely while waiting for the next frame from the server.
         at System.Net.Http.Http2Connection.<ReadFrameAsync>g__ThrowMissingFrame|57_1()
         at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
         at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
         --- End of inner exception stack trace ---
         at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
         at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
         at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
         at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
         at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Aer.Platform.Helpers.Handlers.LoggingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/alexander.usov/Documents/ae/gitlab/common/platform/src/Aer.Platform.Helpers/Handlers/LoggingHandler.cs:line 29
         at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
info: Grpc.Net.Client.Internal.GrpcCall[3]
      Call failed with gRPC error status. Status code: 'Unavailable', Message: 'Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The request was aborted. IOException: The response ended prematurely while waiting for the next frame from the server.'.
dbug: Grpc.Net.Client.Internal.GrpcCall[4]
      Finished gRPC call.
dbug: Grpc.Net.Client.Internal.GrpcCall[8]
      gRPC call canceled.
dbug: Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport[2]
      Subchannel id '1' connected to socket 10.41.132.209:80.
dbug: Grpc.Net.Client.Balancer.Subchannel[11]
      Subchannel id '1' state changed to Ready. Detail: 'Successfully connected to socket.'.
trce: Grpc.Net.Client.Balancer.RoundRobinBalancer[1]
      Processing subchannel id '1' state changed to Ready. Detail: 'Successfully connected to socket.'.
dbug: Grpc.Net.Client.Balancer.Internal.ConnectionManager[4]
      Channel picker updated.

### Error in exception:

Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The request was aborted. IOException: The response ended prematurely while waiting for the next frame from the server.", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The request was aborted.
 ---> System.IO.IOException: The response ended prematurely while waiting for the next frame from the server.
   at System.Net.Http.Http2Connection.<ReadFrameAsync>g__ThrowMissingFrame|57_1()
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Aer.Platform.Helpers.Handlers.LoggingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/alexander.usov/Documents/ae/gitlab/common/platform/src/Aer.Platform.Helpers/Handlers/LoggingHandler.cs:line 29
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")

On a server side all okay in logs and server write that request completed successful 

### What version of gRPC and what language are you using?
dotnet 6, k8s, Grpc.Net.Client - 2.50.0

### What operating system (Linux, Windows,...) and version?
mac m1 && linux

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
dotnet 6

**Comment by careless6666** [comment]
My problem solved when i added port to connection string
i used
dns:///any.dev-rt-config-feature-debug-dotnet.dev.svc.dev1.k8s.company.domaint
instead of
dns:///any.dev-rt-config-feature-debug-dotnet.dev.svc.dev1.k8s.company.domaint:82
