### ISSUE TITLE
AuthenticationException when client-side load balancing is enabled

### ISSUE THREAD

**Issue by ttohin** [grpc/grpc-dotnet#2001]
### What version of gRPC and what language are you using?
C#
Grpc.Net.Client 2.50.0

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
net6
6.0.404

### What did you do?
1. Create GrpcChannel with dns:/// endpoint. The server has valid SSL certificate that matches with endpoint host name.
2. ChannelCredentials must be SslSecure.
3. Do not override RemoteCertificateValidationCallback for underlying HttpClient because it's production code that the server certificate validation must happen.

Something like this:
```
using var channel = GrpcChannel.ForAddress(
    "dns:///my-valid-host.com:5001",
    new GrpcChannelOptions
    {
        Credentials = ChannelCredentials.SslSecure
    });

var client = new Greeter.GreeterClient(channel);
        Console.WriteLine(DateTime.Now.ToString());
        client.SayHello(new HelloRequest { Name = "Hello" });
```

### What did you expect to see?
I expect that the client resolves the DNS record, checks server certificate and makes successful grpc call to the resulting IP address.

### What did you see instead?
Instead, the request fails with AuthenticationException.

```
      Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: The SSL connection could not be established, see inner exception. AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch",
DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
         at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
         at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Microsoft.R9.Extensions.HttpClient.Logging.Internal.HttpLoggingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Microsoft.R9.Extensions.HttpClient.Metering.HttpMeteringHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
         at Grpc.Net.Client.Internal.HttpContentClientStreamWriter`2.WriteAsyncCore[TState](Func`5 writeFunc, TState state)
         at Grpc.Net.Client.Internal.Retry.RetryCall`2.<>c__DisplayClass13_0.<<ClientStreamWriteAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Grpc.Net.Client.Internal.Retry.RetryCall`2.DoClientStreamActionAsync(Func`2 action)
         at Grpc.Net.Client.Internal.Retry.RetryCall`2.DoClientStreamActionAsync(Func`2 action)
         at Grpc.Net.Client.Internal.Retry.RetryCall`2.ClientStreamWriteAsync(TRequest message, CancellationToken cancellationToken)
```

I think it happens because `BalancerHttpHandler` replaces the request host by the IP address (resolved by ConnectionManager) and then underlying HttpClient tries to match the server SSL certificate with host name (which is IP) and fails because they do not match.

It looks like that Grpc.Net.Client must examine server certificate against the original host name configured for the channel (my-valid-host.com in my sample).

**Comment by JamesNK** [comment]
I think this is a bug and can be fixed in Grpc.Net.Client.

To test out a fix, you can use a DelegatingHandler to specify the hostname.


```cs
private sealed class HostHeaderDelegateHandler : DelegatingHandler
{
    public HostHeaderDelegateHandler(HttpMessageHandler innerHandler) : base(innerHandler)
    {
    }

    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        request.Headers.Host = "my-valid-host.com"; // <- replace with your host
        return base.SendAsync(request, cancellationToken);
    }
}
```

To use:

```cs
using var channel = GrpcChannel.ForAddress(
    "dns:///my-valid-host.com:5001",
    new GrpcChannelOptions
    {
        Handler = new HostHeaderDelegateHandler(new SocketsHttpHandler()),
        Credentials = ChannelCredentials.SslSecure
    });
```

Let me know if this works for you.
