### ISSUE TITLE
.NET gRPC Client can't send request to a gRPC Server (the server did not complete the HTTP/2 handshake. )

### ISSUE THREAD

**Issue by ArminShoeibi** [grpc/grpc-dotnet#2017]
Hi there folks,

We have a gRPC server in Golang, and we are exposing it to the browsers via an Nginx proxy pass. (it uses port 443 but with HTTP protocol, not HTTPS)

<img width="881" alt="Screenshot 2023-01-14 185728" src="https://user-images.githubusercontent.com/68565441/212479799-b3f4f151-6cc3-473f-b293-34548bd27eed.png">

We can invoke methods with grpCurl, but we can't invoke methods on server with the generated clients on our .NET project.

our NuGet packages related to gRPC:
```
    <PackageReference Include="Grpc.AspNetCore" Version="2.51.0" />
    <PackageReference Include="Grpc.Tools" Version="2.51.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

here is the registration part:

```
#if DEBUG
AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
#endif

builder.Services.AddGrpcClient<Indra.Integration.Insurance.MyTrips.OrderService.OrderServiceClient>(gcfo =>
{
    gcfo.Address = myTripsOptions.InsuranceUri;
}).ConfigurePrimaryHttpMessageHandler(hmh =>
{
    return new HttpClientHandler()
    {
        ClientCertificateOptions = ClientCertificateOption.Manual,
        ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator,
        UseProxy = false
    };
});
```

![image](https://user-images.githubusercontent.com/68565441/212480035-060d9f32-44f2-460a-90b0-9f0ecf3e3024.png)

And we have this exception:

```
Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The request was aborted. IOException: An HTTP/2 connection could not be established because the server did not complete the HTTP/2 handshake. HttpProtocolException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1).", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The request was aborted.
 ---> System.IO.IOException: An HTTP/2 connection could not be established because the server did not complete the HTTP/2 handshake.
 ---> System.Net.Http.HttpProtocolException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1).
   at System.Net.Http.Http2Connection.ThrowProtocolError(Http2ProtocolErrorCode errorCode, String message)
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
```

![image](https://user-images.githubusercontent.com/68565441/212480123-7d2cf9cd-aeb2-409a-9906-38b58fa1c1c5.png)

We have searched a lot, like this issue https://github.com/grpc/grpc-dotnet/issues/1552 but right now we don't know how to solve this issue.

** We don't have this issue in our Staging or Production areas, because we are using Kubernetes services, but for our development area, we are using an Nginx proxy pass for those Kubernetes services. **

**Comment by ArminShoeibi** [comment]
This is the Uri quick watch:
![image](https://user-images.githubusercontent.com/68565441/212480494-97015aa7-1d10-43a3-a9ff-fca689095a2a.png)

**Comment by ArminShoeibi** [comment]
We found a better solution instead of Nginx gRPC pass.
You can read more about ithttps://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/
