### ISSUE TITLE
Exception HTTP/2 error code 'PROTOCOL_ERROR' (0x1)

### ISSUE THREAD

**Issue by rupreck** [grpc/grpc-dotnet#2057]
### What version of gRPC and what language are you using?
2.51.0

### What operating system (Linux, Windows,...) and version?
Windows 11, Windows Server 2019

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET 7.0.3

### What did you do?
The following exception occurs when this package is used in a .NET 7 service with Kestrel where another connection type is also used.

```
01:56:10 ERR] An unhandled exception has occurred while executing the request.
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. HttpProtocolException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1).", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.Net.Http.HttpProtocolException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1).
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
   at async Task<TResponse> ProtoBuf.Grpc.Internal.Reshape.UnaryTaskAsyncImpl<TRequest, TResponse>(AsyncUnaryCall<TResponse> call, MetadataContext metadata, CancellationToken cancellationToken) i**n /_/src/protobuf-net.Grpc/Internal/Reshape.cs:line 549**
   at Organisation SA.Common.Client.Orchestrator.Request.OrganisationRequest.GetOrganisationByName(string organisationName) in C:/../common/SA.Common.Client.Orchestrator/Request/OrganisationRequest.cs:line 131

```
This occurs when opening a Azure Hybrid Relay Connection any time before or after the GRPC connection is established from the same service.

The connection hangs and then throws the above exception. It may be that the HTTP2 connection is downgraded in the background to HTTP1.1 when the connection is established with the listener on the other end of the Azure Relay.

The problem is not resolved by specifying HTTP2 for Kestrel or restricting Kestrel to only listen to LocalHost or by using https with a certificate.

### What did you expect to see?
Expected to see our middleware able to handle GRPC requests from our api and UI layers and be able to communicate with our cluster nodes using Azure Relay over HTTPS.

### What did you see instead?

A long hang of a couple of minutes until the exception is raised.

### Anything else we should know about your project / environment?
Perhaps this is due to this Kestrel problem discussed here..
https://github.com/dotnet/aspnetcore/issues/44537
https://github.com/dotnet/aspnetcore/pull/44657

**Comment by JamesNK** [comment]
Hi

I don't see how the linked issues are related.

> The following exception occurs when this package is used in a .NET 7 service with Kestrel where another connection type is also used.

Do you mean protocol type? e.g. the Kestrel port supported HTTP/1.1 and HTTP/2? I'm guessing you're not using TLS. It is required in this situation. More info: https://learn.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-7.0&tabs=visual-studio#protocol-negotiation
