### ISSUE TITLE
Interop test server failure seen on grpc/grpc interop suite

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-dotnet#206]
https://source.cloud.google.com/results/invocations/71ff4afa-806a-4947-a2d5-567c86e34735/log

This could be a bug in Grpc.AspNetCore.Server, as the server shouldn't just exit.

```
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - /grpc.testing.TestService/FullDuplexCall'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /grpc.testing.TestService/FullDuplexCall'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.8264ms 200 application/grpc
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/2 POST https://foo.test.google.fr/grpc.testing.TestService/FullDuplexCall application/grpc
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - /grpc.testing.TestService/FullDuplexCall'
fail: Grpc.Testing.TestServiceImpl[3]
      Error when executing service method 'FullDuplexCall'.
System.IO.IOException: The client reset the request stream.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadStreamMessageAsync(PipeReader input, HttpContextServerCallContext context, CancellationToken cancellationToken) in /var/local/git/grpc-dotnet/src/Grpc.AspNetCore.Server/Internal/PipeExtensions.cs:line 271
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Grpc.AspNetCore.Server.Internal.HttpContextStreamReader`1.<MoveNext>g__MoveNextAsync|10_0(ValueTask`1 readStreamTask) in /var/local/git/grpc-dotnet/src/Grpc.AspNetCore.Server/Internal/HttpContextStreamReader.cs:line 48
   at InteropTestsWebsite.AsyncStreamExtensions.ForEachAsync[T](IAsyncStreamReader`1 streamReader, Func`2 asyncAction) in /var/local/git/grpc-dotnet/testassets/InteropTestsWebsite/AsyncStreamExtensions.cs:line 35
   at Grpc.Testing.TestServiceImpl.FullDuplexCall(IAsyncStreamReader`1 requestStream, IServerStreamWriter`1 responseStream, ServerCallContext context) in /var/local/git/grpc-dotnet/testassets/InteropTestsWebsite/TestServiceImpl.cs:line 76
   at Grpc.AspNetCore.Server.Internal.CallHandlers.DuplexStreamingServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext) in /var/local/git/grpc-dotnet/src/Grpc.AspNetCore.Server/Internal/CallHandlers/DuplexStreamingServerCallHandler.cs:line 55
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /grpc.testing.TestService/FullDuplexCall'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2.1099ms 200 application/grpc
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature,TState](TFeature& cached, TState state, Func`2 factory)
   at Microsoft.AspNetCore.Http.DefaultHttpContext.Abort()
   at Grpc.AspNetCore.Server.Internal.HttpContextServerCallContext.DeadlineExceeded(Object state) in /var/local/git/grpc-dotnet/src/Grpc.AspNetCore.Server/Internal/HttpContextServerCallContext.cs:line 267
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
2019-04-09 12:12:20,641 FAILED: interop_server_aspnetcore [ret=139, pid=32584, time=338.8sec]
```

**Comment by jtattermusch** [comment]
Seen again:
https://source.cloud.google.com/results/invocations/372f4c19-991e-41f1-8759-b6967b288b42/log

**Comment by JamesNK** [comment]
Could the logging level for the test server be changed to debug? That would provide more info when errors occur.

**Comment by JunTaoLuo** [comment]
Could be addressed by https://github.com/grpc/grpc-dotnet/pull/299

**Comment by JamesNK** [comment]
Should be fixed. Reopen if the test fails post-fix.
