### ISSUE TITLE
Exception after update to version 2.52.0.

### ISSUE THREAD

**Issue by tingsby** [grpc/grpc-dotnet#2079]
Exception Message: Could not find a constructor for constraint type 'GrpcUnimplementedConstraint' with the following number of parameters: 0. 
I get this message in all services after update to version 2.52.0. The code has worked in all previous versions of gRPC Core.

**Comment by tingsby** [comment]
Output from Logfile;
Time......: 2023-03-20 08:53:24.3448684
Descr.....: Microsoft.AspNetCore.Routing.RouteCreationException
Message...: Could not find a constructor for constraint type 'GrpcUnimplementedConstraint' with the following number of parameters: 0.
Source....: Microsoft.AspNetCore.Routing
StackTrace: at Microsoft.AspNetCore.Routing.ParameterPolicyActivator.CreateParameterPolicy(IServiceProvider serviceProvider, Type parameterPolicyType, String argumentString)
   at Microsoft.AspNetCore.Routing.ParameterPolicyActivator.ResolveParameterPolicy[T](IDictionary`2 inlineParameterPolicyMap, IServiceProvider serviceProvider, String inlineParameterPolicy, String& parameterPolicyKey)
   at Microsoft.AspNetCore.Routing.DefaultParameterPolicyFactory.Create(RoutePatternParameterPart parameter, String inlineText)
   at Microsoft.AspNetCore.Routing.ParameterPolicyFactory.Create(RoutePatternParameterPart parameter, RoutePatternParameterPolicyReference reference)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherBuilder.DfaBuilderWorker.AddParentsWithMatchingLiteralConstraints(List`1 nextParents, DfaNode parent, RoutePatternParameterPart parameterPart, IReadOnlyList`1 parameterPolicyReferences)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherBuilder.DfaBuilderWorker.ProcessSegment(RouteEndpoint endpoint, List`1 parents, List`1 nextParents, RoutePatternPathSegment segment)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherBuilder.DfaBuilderWorker.ProcessLevel(Int32 depth)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherBuilder.BuildDfaTree(Boolean includeLabel)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherBuilder.Build()
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.CreateMatcher(IReadOnlyList`1 endpoints)
   at Microsoft.AspNetCore.Routing.DataSourceDependentCache`1.Initialize()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& , Boolean& , Object& , Func`1 )
   at System.Threading.LazyInitializer.EnsureInitialized[T](T& , Boolean& , Object& , Func`1 )
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher..ctor(EndpointDataSource dataSource, Lifetime lifetime, Func`1 matcherBuilderFactory)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherFactory.CreateMatcher(EndpointDataSource dataSource)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.InitializeCoreAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by JamesNK** [comment]
The error is strange. That type has a constructor: https://github.com/grpc/grpc-dotnet/blob/95cf7fc928e56e3037de321f3fae842f39c6fc91/src/Grpc.AspNetCore.Server/Model/Internal/GrpcUnimplementedConstraint.cs#L51

What version of .NET are you using? Is the app being published with trimming enabled?

Could you create a simple reproduction of the problem and put it in a GH repo for me to look at?

**Comment by tingsby** [comment]
Hi!

I use NET 6 published with trimming enabled. Sorry I don't have time right now to create a repo. I work in a project with a tight schedule.

//Regards

Från: James Newton-King ***@***.***>
Skickat: den 20 mars 2023 11:21
Till: grpc/grpc-dotnet ***@***.***>
Kopia: Anders Tingsby ***@***.***>; Author ***@***.***>
Ämne: Re: [grpc/grpc-dotnet] Exception after update to version 2.52.0. (Issue #2079)


The error is strange. That type has a constructor: https://github.com/grpc/grpc-dotnet/blob/95cf7fc928e56e3037de321f3fae842f39c6fc91/src/Grpc.AspNetCore.Server/Model/Internal/GrpcUnimplementedConstraint.cs#L51

What version of .NET are you using? Is the app being published with trimming enabled?

Could you create a simple reproduction of the problem and put it in a GH repo for me to look at?

**Comment by JamesNK** [comment]
Ok. ASP.NET Core in .NET 6 wasn't fully annotated for trimming and it looks like the route constructor is being trimmed away.

There are a range of options to fix this:
* Continue to use 2.51.0
* Update to .NET 7
* Disable trimming

**Comment by tingsby** [comment]
Hi!

Additional information. I forgot to change version on Grpc.AspNetCore and Grpc.AspNetCore.Web from 2.52.0 to 2.51.0 in one service. Then the same error occurs even if Grpc.Net.Client changed to 2.51.0 and trimming is disabled.

/Regards

Från: James Newton-King ***@***.***>
Skickat: den 20 mars 2023 14:00
Till: grpc/grpc-dotnet ***@***.***>
Kopia: Anders Tingsby ***@***.***>; Author ***@***.***>
Ämne: Re: [grpc/grpc-dotnet] Exception after update to version 2.52.0. (Issue #2079)


Ok. ASP.NET Core in .NET 6 wasn't fully annotated for trimming and it looks like the route constructor is being trimmed away.

There are a range of options to fix this:

  *   Continue to use 2.51.0
  *   Update to .NET 7
  *   Disable trimming

**Comment by JamesNK** [comment]
The error that is happening is a server error. Changing the client doesn't have any impact.

One of these changes needs to happen to the server:

>  *   Continue to use 2.51.0
>  *   Update to .NET 7
>  *   Disable trimming

If your server gets the same error when using .NET 7, I'd be surprised. It should be annotated for trimming.

**Comment by JamesNK** [comment]
I had an idea for how to fix this in future version of Grpc.AspNetCore.Server. I suggest you stick with 2.51.0 for now and update to 2.53.0 sometime in the future.

https://github.com/grpc/grpc-dotnet/pull/2080
