### ISSUE TITLE
Can't get grpc to work in docker

### ISSUE THREAD

**Issue by ray440** [grpc/grpc-dotnet#2085]
I have an app that uses gRPC and works fine until I run it in a docker container.  The container can successfully expose http and https on port 80 & 443.  But grpc produces the following error:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: The SSL connection could not be established, see inner exception. AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot", DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
      Application started. Press Ctrl+C to shut down.
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

```

I tried localhost and other addresses to create the channel:
```GrpcChannel.ForAddress("https://localhost:443", opts)```

The docker-compose.yml contains

```
version: "3.9"

services:

  web:
    container_name: myapp-web
    build: .

    ports:
      - "18080:80"
      - "18443:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=18443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=dontlookatme
      - ASPNETCORE_Kestrel__Certificates__Default__Path=C:\https\aspnetapp.pfx
    volumes:
      - ${USERPROFILE}\.aspnet\https:C:\https:ro
```

**Comment by JamesNK** [comment]
The error message says what is wrong.

**Comment by ray440** [comment]
@JamesNK I suspect I'm doing something stupid here. The certificate is a self-sign .. so it's an UntrustedRoot.  The puzzle for me is why a web view of `https:\\locahost:443` will work but grpc channel with the same url won't work.  Is it a http2 thing?

**Comment by JamesNK** [comment]
Have you looked at this?

https://learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-7.0#call-a-grpc-service-with-an-untrustedinvalid-certificate

**Comment by ray440** [comment]
Yeah, I had tried `ServerCertificateCustomValidationCallback ` but something didn't work.  Tried it again as you suggested. And it works now!

Thank you so much!  It's been a couple of days...  I can finally rest.
