### ISSUE TITLE
Cannot retry channel creation after PlatformNotSupportedException

### ISSUE THREAD

**Issue by leotohill** [grpc/grpc-dotnet#2101]
### What version of gRPC and what language are you using?
2.47 and 2.49, c#

### What operating system (Linux, Windows,...) and version?
Windows server 2019

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)

dotnet framework 4.8 and dotnet 6

The server application is dotnet6, and is meant to service both http1 and http2 connections. The relevant initialization is:
```
builder.WebHost.ConfigureKestrel(options =>
    options.Listen(ipAddress, port, listenOptions =>
    {
        listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
        listenOptions.UseHttps();
    }));
```

My client application is multi-targeted, building for both framework 4.8 and dotnet 6.  I want it to establish a http2 connection when it can, else http1.  I used exception detection and fallback as follows:

```
var handler = new HttpClientHandler();
handler.ServerCertificateCustomValidationCallback = (a, b, c, d) => true;
try
{
        var options = new GrpcChannelOptions() { LoggerFactory = loggerFactory, HttpHandler = handler };
	mGrpcChannel = GrpcChannel.ForAddress(grpcUrl, options);
}
catch (PlatformNotSupported)
{
     var options = new GrpcChannelOptions() 
				{ LoggerFactory = loggerFactory, HttpHandler = new GrpcWebHandler(handler) };
     mGrpcChannel = GrpcChannel.ForAddress(grpcUrl, options);
}

```
This doesn't work.  The second attempt fails with "System.ArgumentException: Only HTTP/1.0 and HTTP/1.1 version requests are currently supported."

Some remnant of the first attempt is remaining.  The second approach, where I use GrpcWebHandler, works fine if I don't first try the http2 approach. 
I also tried re-creating the HttpClientHandler in the second attempt.  I think.  That didn't help.  

I have a workaround: I just use #if NET6_0_OR_GREATER instead of runtime checks.  I just thought  you'd want to know about this issue. 

stack trace:
```
Parameter name: value
   at System.Net.HttpWebRequest.set_ProtocolVersion(Version value)
   at System.Net.Http.HttpClientHandler.CreateAndPrepareWebRequest(HttpRequestMessage request)
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Net.Client.Internal.GrpcCall`2.&lt;RunCall&gt;d__73.MoveNext() in /_/src/Grpc.Net.Client/Internal/GrpcCall.cs:line 493")</message>
         <context>Login.OnException</context>
         <other>Void Throw()</other>
         <stackTrace>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in /_/src/Grpc.Net.Client/Internal/HttpClientCallInvoker.cs:line 115
   at Grpc.Core.Interceptors.InterceptingCallInvoker.&lt;BlockingUnaryCall&gt;b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx) in /_/src/Grpc.Core.Api/Interceptors/InterceptingCallInvoker.cs:line 51
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation) in /_/src/Grpc.Core.Api/ClientBase.cs:line 174
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in /_/src/Grpc.Core.Api/Interceptors/InterceptingCallInvoker.cs:line 48
   at ProtoBuf.Grpc.Internal.Reshape.UnarySync[TRequest,TResponse](CallContext&amp; context, CallInvoker invoker, Method`2 method, TRequest request, String host) in /_/src/protobuf-net.Grpc/Internal/Reshape.cs:line 206
   at ProtoBuf.Grpc.Internal.Proxies.ClientBase.IDataServicesGrpc_Proxy_0.INetMenuServiceGrpc.GetVersion()
(application code from here)
```

**Comment by JamesNK** [comment]
The exception you're getting _should_ be prevented with this code:

https://github.com/JamesNK/grpc-dotnet/blob/5a57759536dc5b0ea812671a82e6e9c3695282fb/src/Grpc.Net.Client.Web/GrpcWebHandler.cs#L157-L162

https://github.com/JamesNK/grpc-dotnet/blob/5a57759536dc5b0ea812671a82e6e9c3695282fb/src/Grpc.Net.Client.Web/GrpcWebHandler.cs#L188-L203

What values do these properties have?
* Environment.Version.Major
* Environment.Version.Minor
* Environment.Version.Build

Also, can you confirm if the client app running on .NET Framework uses the netstandard2.0 Grpc.Net.Client.Web assembly?

**Comment by leotohill** [comment]
Environment.Version (Major.Minor.Build) is **6.0.16**

The following shows the versions/builds of grpc packages I'm putting into the run folder of the fw 4.8 client:

    "grpc.net.client\2.47.0\lib\netstandard2.0\*.*",
    "grpc.net.client.web\2.49.0\lib\netstandard2.0\*.*",
    "grpc.net.common\2.47.0\lib\netstandard2.0\*.*",
    "grpc.core.api\2.47.0\lib\netstandard2.0\*.*",

**Comment by leotohill** [comment]
Environment.Version (Major.Minor.Build) is  4.0.30319
The following shows the versions/builds of grpc packages I'm putting into the run folder of the fw 4.8 client:

    "grpc.net.client\2.47.0\lib\netstandard2.0\*.*",
    "grpc.net.client.web\2.49.0\lib\netstandard2.0\*.*",
    "grpc.net.common\2.47.0\lib\netstandard2.0\*.*",
    "grpc.core.api\2.47.0\lib\netstandard2.0\*.*",

From that code snippet you provided... I think that I tested re-creating the handler for the second attempt, but perhaps I didn't .  Would using the same handler (as the parm to ```new GrpcHttpHandler)``` cause the problem? Because it has been initialized from the first attempt?

**Comment by JamesNK** [comment]
It shouldn't make a difference.

Your try/catch sample above doesn't have a gRPC call inside the try. The exception happens when a gRPC call is made, not when the channel is created.
