### ISSUE TITLE
[dotnet-sdk-8.0.100-preview.3.23159.20]The type of exception changed from TaskCanceledException to OperationCanceledException

### ISSUE THREAD

**Issue by Junjun-zhao** [grpc/grpc-dotnet#2207]
**Description**
When run the grpc test with the latest .NET 8 Preview3 runtime, the type of exception changed from TaskCanceledException to OperationCanceledException.   
**This is a bug fix from .NET 8 Preview3, the test should be changed to handle OCE instead.
In general, it is discouraged catching TaskCanceledException instead of OperationCanceledException. The former is just the latter the carries a bit of extra information and is otherwise intended to be interchangeable.  Please refer to more details from https://github.com/dotnet/runtime/issues/83382**

**GitHub Site:**
[grpc-dotnet/HttpContextStreamReaderTests.cs at master · grpc/grpc-dotnet · GitHub](https://github.com/grpc/grpc-dotnet/blob/master/test/Grpc.AspNetCore.Server.Tests/HttpContextStreamReaderTests.cs)

**Test Project** : https://github.com/grpc/grpc-dotnet/tree/master/test/Grpc.AspNetCore.Server.Tests

**Reproduction Steps**

**The machine only has dotnet-sdk-8.0.100-preview.3.23159.20 or later version installed. And DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2 is set.**

1. Launch cmd window.
2. Cd to “\grpcdotnetTest04”.
3. Input “dotnet vstest Grpc.AspNetCore.Server.Tests.dll /Tests:MoveNext_TokenCancelledDuringMoveNext_CancelTask”.
4. Press keyboard “Enter”.

**Expected behavior**
A total of 1 test files matched the specified pattern.
Passed! - Failed: 0, Passed: 1, Skipped: 0, Total: 1, Duration: 74 ms - Grpc.AspNetCore.Server.Tests.dll (net7.0)

**Actual behavior**
```
A total of 1 test files matched the specified pattern.

  Failed MoveNext_TokenCancelledDuringMoveNext_CancelTask [293 ms]
  Error Message:
   System.OperationCanceledException : A task was canceled.
  ----> System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at System.IO.Pipelines.StreamPipeReader.<ReadAsync>g__Core|38_0(StreamPipeReader reader, CancellationTokenSource tokenSource, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadStreamMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer, CancellationToken cancellationToken) in C:\upgrade\grpc-dotnet\src\Grpc.AspNetCore.Server\Internal\PipeExtensions.cs:line 298
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Grpc.AspNetCore.Server.Internal.HttpContextStreamReader`1.<MoveNext>g__MoveNextAsync|9_0(ValueTask`1 readStreamTask) in C:\upgrade\grpc-dotnet\src\Grpc.AspNetCore.Server\Internal\HttpContextStreamReader.cs:line 44
   at Grpc.AspNetCore.Server.Tests.HttpContextStreamReaderTests.MoveNext_TokenCancelledDuringMoveNext_CancelTask() in C:\upgrade\grpc-dotnet\test\Grpc.AspNetCore.Server.Tests\HttpContextStreamReaderTests.cs:line 76
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
--TaskCanceledException
   at Grpc.Tests.Shared.SyncPointMemoryStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in C:\upgrade\grpc-dotnet\test\Shared\SyncPointMemoryStream.cs:line 107
   at System.IO.Pipelines.StreamPipeReader.<ReadAsync>g__Core|38_0(StreamPipeReader reader, CancellationTokenSource tokenSource, CancellationToken cancellationToken)

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 293 ms - Grpc.AspNetCore.Server.Tests.dll (net7.0)
```

**Comment by JamesNK** [comment]
That change is already on this branch - https://github.com/grpc/grpc-dotnet/pull/2021. It will be merged closer to the .NET 8 release.
