### ISSUE TITLE
New Grpc.Core.Server creation not working in a Mac M2

### ISSUE THREAD

**Issue by ropinheiro** [grpc/grpc-dotnet#2344]
### What version of gRPC and what language are you using?

I am using C# with the latest `grpc-dotnet` (2.59.0).

### What operating system (Linux, Windows,...) and version?

MacOS Sonoma 14.1.2 (23B92) - RID: osx-arm64

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)

.NET Core SDK 8.0.100 (runtime: 8.0.0)

### What did you do?

Run "dotnet run" :)

### What did you expect to see?

An application running without errors.

I know it is possible because I can do that on another Mac I have.

That other Mac has the same setup, same code, same .NET SDK and runtime, same .NET version, etc. Maybe something else needs to be checked (tell me what, then) but the main difference is that **it is an older Mac, still with the Intel chip** - hence my guess that maybe it's a bug related to the M2 chip.

### What did you see instead?

When I execute "dotnet run", I get this error:

_Note: I used (...) as a replacement for my specific irrelevant stuff_

```
[18:33:31 FTL] Unhandled exception!
System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations: 
  (...)/bin/Debug/net8.0/libgrpc_csharp_ext.arm64.dylib,
  (...)/bin/Debug/net8.0/runtimes/osx-arm64/native/libgrpc_csharp_ext.arm64.dylib,
  (...)/bin/Debug/net8.0/../../runtimes/osx-arm64/native/libgrpc_csharp_ext.arm64.dylib
   at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethodsUsingExplicitLoad()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.Internal.NativeMethods.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Server..ctor(IEnumerable`1 options)
   at Grpc.Core.Server..ctor()
   at (...).Grpc.GrpcServer.StartServer() in (...)/Grpc/GrpcServer.cs:line 41
   at (...).Grpc.GrpcServer..ctor(...) in (...)/Grpc/GrpcServer.cs:line 24
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at (...).Program.MainAsync() in (...)/Program.cs:line 196
   at (...).Program.Main() in (...)/Program.cs:line 39
[18:33:31 DBG] Flushing logs....
[18:33:31 INF] Trapped SIGTERM: shutting down...
```

Line 41 mentioned in the error message is the first line of this code block:

```
        var server = new Grpc.Core.Server
        {
            Services = { MyService.BindService(myService) },
            Ports =
            {
                new Grpc.Core.ServerPort("0.0.0.0", myPort, Grpc.Core.ServerCredentials.Insecure)
            }
        };
```

### Anything else we should know about your project / environment?

Not sure. I have a gut feeling that it is related to the Intel vs M2 chip difference. I spent some time checking all possible differences between the two Macs, and that's the major one. Also, the OS is 14.2.1 on the old Mac (I still had no opportunity to upgrade to the newer one from its 14.1.2).

**Comment by JamesNK** [comment]
You're using Grpc.Core. The source code and issues for that library are at https://github.com/grpc/grpc. Please create an issue there.

**Comment by ropinheiro** [comment]
Already moved (and reviewed it a bit) here: https://github.com/grpc/grpc/issues/35414 (to help redirect someone else that also wrongly stumbles here).

Thank you @JamesNK, and happy new year :)
