### ISSUE TITLE
If connection is not established, the Polly retry policy i HttpMessageHandlers are not called.

### ISSUE THREAD

**Issue by magiino** [grpc/grpc-dotnet#2447]
Hello,

why is not called Polly policy http message handler when connection could not be established?
I would like to retry even if connection could not be established, the service might be restarting when I'm doing the grpc call.

How can I add http message handler which will be called even during connection?

```csharp
      serviceCollection
                     .AddGrpcClient<TGrpcClientType>(option =>
                     {
                         option.Address = new Uri(configuration.EndpointAddress);
                         option.CallOptionsActions.Add(ctx =>
                             ctx.CallOptions =
                                 ctx.CallOptions
                                     .WithDeadline(DateTime.UtcNow.Add(configuration.Deadline)))
                                     ;
                     })
                     .AddPolicyHandler(retryFunc);
```
This sample code was taken from past discussion https://github.com/grpc/grpc-dotnet/issues/686
```csharp
    Func<HttpRequestMessage, IAsyncPolicy<HttpResponseMessage>> retryFunc = (request) =>
    {
        return Policy.HandleResult<HttpResponseMessage>(r => r.Headers.GetValues("grpc-status").FirstOrDefault() != "0")
                                 .WaitAndRetryAsync(3, (input) => TimeSpan.FromSeconds(3 + input), (result, timeSpan, retryCount, context) =>
                                 {
                                     var grpcStatus = (StatusCode)int.Parse(result.Result.Headers.GetValues("grpc-status").FirstOrDefault() ?? "0");
                                     Console.WriteLine($"Request failed with {grpcStatus}. Retry.");
                                 });
    };
```

**Comment by vitkulis** [comment]
Hello,
We have the same problem.

It have started happening after upgrading Grpc.Net.ClientFactory from version 2.43. to newer version. 

The policy is not invoked when making the first request to the server. If the connection is interrupted after it has already been established once, the policies are called correctly.

Here is the error that is thrown during the first gRPC request attempt when the server is unavailable.

```
Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error connecting to subchannel.", DebugException="System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it.")
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context, Int32 attempt)
   --- End of inner exception stack trace ---
   at Grpc.Net.Client.Balancer.Internal.ConnectionManager.PickAsync(PickContext context, Boolean waitForReady, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
```
