### ISSUE TITLE
Setting `HttpVersionPolicy` breaks gRPC client completely

### ISSUE THREAD

**Issue by Eagle3386** [grpc/grpc-dotnet#2546]
### What version of gRPC and what language are you using?
ASP.NET Core gRPC-Web service, freshly upgraded to 2.66.0

### What operating system (Linux, Windows,...) and version?
Windows 11, latest patch version

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET SDK 8.0.400

### What did you do?
Upgraded the NuGet package from 2.65.0 to 2.66.0 & changed this:
```csharp
channel.HttpHandler = new GrpcWebHandler(GrpcWebMode.GrpcWeb, new HttpClientHandler()) { HttpVersion = new(2, 0) };
```
to this:
```csharp
channel.HttpHandler       = new GrpcWebHandler(GrpcWebMode.GrpcWeb, new HttpClientHandler());
channel.HttpVersionPolicy = HttpVersionPolicy.RequestVersionOrHigher;
```

### What did you expect to see?
Client running as before.

### What did you see instead?
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Method not found: void Grpc.Net.Client.GrpcChannelOptions.set_HttpVersionPolicy(System.Nullable`1<System.Net.Http.HttpVersionPolicy>)
System.MissingMethodException: Method not found: void Grpc.Net.Client.GrpcChannelOptions.set_HttpVersionPolicy(System.Nullable`1<System.Net.Http.HttpVersionPolicy>)
   at Grpc.Net.ClientFactory.Internal.GrpcCallInvokerFactory.CreateInvoker(EntryKey key)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Grpc.Net.ClientFactory.Internal.EntryKey, Grpc.Net.ClientFactory, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad],[Grpc.Core.CallInvoker, Grpc.Core.Api, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad]].GetOrAdd(EntryKey key, Func`2 valueFactory)
   at Grpc.Net.ClientFactory.Internal.GrpcCallInvokerFactory.CreateInvoker(String name, Type type)
   at Grpc.Net.ClientFactory.Internal.DefaultGrpcClientFactory.CreateClient[RedirectionClient](String name)
   at Microsoft.Extensions.DependencyInjection.GrpcClientServiceExtensions.<>c__DisplayClass7_0`1[[Hmd.Services.Redirection.Redirection.RedirectionClient, Hmd.Portal, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null]].<AddGrpcHttpClient>b__0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine.<>c__DisplayClass4_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue() blazor.webassembly.js:1:46958
```

### Anything else we should know about your project / environment?
No, but you're free to ask if necessary.

**Comment by JamesNK** [comment]
My guess is 2.66.0 isn't correctly being deployed with your app. When this code in another assembly tries to call the new method it can't find it because an older version is present.

**Comment by Eagle3386** [comment]
Thanks, @JamesNK! Cleaning & rebuilding the whole solution worked.
But even after setting `HttpVersion` to `3.0` & keeping `RequestVersionOrHigher` as policy, it still does HTTP/2 only:
```
Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware:
Debug: Connection {id} established using the following protocol: Tls13

Microsoft.AspNetCore.Hosting.Diagnostics:
Information: Request starting HTTP/2 OPTIONS https://localhost:4430/MyService.My/SendData - - -
```

Why is that? I _really_ want to test HTTP/3, so that we can adopt it for our gRPC-Web(Text) services ASAP..

**Comment by JamesNK** [comment]
I'm not sure. Negotiating HTTP/3 involves a number of things to work correctly. Perhaps setting the policy to exact and HTTP/3 in the client might work?

HTTP/3 is only supported on full .NET (not WebAssembly). The server will also need to support HTTP/3.

**Comment by Eagle3386** [comment]
Tried even that & it still went HTTP/2 for some requests, e.g., `HTTP OPTIONS`.
Though, the "actual" requests where done in HTTP/3 - and that's with a Blazor WASM standalone client!

As the server is just Kestrel (with NGinX as proxy in production), I set it to that already.

**Comment by JamesNK** [comment]
I don't think those options have any impact in WebAssembly. In the browser the initial request is often HTTP/2 and then it upgrades to HTTP/3.

**Comment by Eagle3386** [comment]
I see. Thanks for clarification, @JamesNK! 👍🏻
