### ISSUE TITLE
Status not set by server on exception.

### ISSUE THREAD

**Issue by altnp** [grpc/grpc-dotnet#300]
When an exception is thrown by a service method status code is not set.  The client throws StatusCode=Unknown, Details="**No status received**".

Expected:
https://github.com/grpc/grpc-dotnet/blob/74666fffdf9f48701205a147a212d9e82cab7eb2/src/Grpc.AspNetCore.Server/Internal/HttpContextServerCallContext.cs#L137

I first noticed the issue in 6/1's nightly build, however it likely existed prior.

**Comment by JamesNK** [comment]
I get a status detail from the server in both the Grpc.Core client and Grpc.Net.Client

```
Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Exception was thrown by handler.")
   at Sample.Clients.Program.UnaryCallExample(GreeterClient client) in C:\Development\Source\grpc-dotnet\examples\Clients\Greeter\Program.cs:line 50
   at Sample.Clients.Program.Main(String[] args) in C:\Development\Source\grpc-dotnet\examples\Clients\Greeter\Program.cs:line 38
   at Sample.Clients.Program.<Main>(String[] args)
```

```
Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Exception was thrown by handler.")
   at Grpc.Net.Client.Internal.GrpcCall`2.FinishResponse() in C:\Development\Source\grpc-dotnet\src\Grpc.Net.Client\Internal\GrpcCall.cs:line 241
   at Grpc.Net.Client.Internal.GrpcCall`2.GetResponseAsync() in C:\Development\Source\grpc-dotnet\src\Grpc.Net.Client\Internal\GrpcCall.cs:line 301
   at Sample.Clients.Program.UnaryCallExample(GreeterClient client) in C:\Development\Source\grpc-dotnet\examples\Clients\Greeter\Program.cs:line 53
   at Sample.Clients.Program.Main(String[] args) in C:\Development\Source\grpc-dotnet\examples\Clients\Greeter\Program.cs:line 41
   at Sample.Clients.Program.<Main>(String[] args)
```

**Comment by altnp** [comment]
I confirmed using the /Examples/Clients/Greeter and /Examples/Server by

1. Removing all server side interceptors in case they were masking the error.
2. Replacing SayHello's implementation with the below code.

```
public override Task<HelloReply> SayHello(HelloRequest request, ServerCallContext context)
    {
        throw new Exception("Dummy Exception");
        //_logger.LogInformation($"Sending hello to {request.Name}");
        //return Task.FromResult(new HelloReply { Message = "Hello " + request.Name });
    }
```
To be clear the issue is the with server side handling of exceptions.

**Comment by altnp** [comment]
I have narrowed down the issue to 1.21-pre, the 1.20-pre package on nuget handles exceptions as expected.

Repo w/ reproduction is here:
https://github.com/altnp/grpc-dontnet-exception-reproduce/tree/master/DotNetServer

**Comment by JamesNK** [comment]
I ran your repo and this is the result I got:

```
Invoking gRPC Core Server
Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Exception was thrown by handler.")
   at CoreClient.Program.Main(String[] args) in C:\Development\Temp\grpc-dontnet-exception-reproduce\CoreClient\Program.cs:line 17
Invoking Asp.Net gRPC Server
Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Exception was thrown by handler. Exception: Example Exception!")
   at CoreClient.Program.Main(String[] args) in C:\Development\Temp\grpc-dontnet-exception-reproduce\CoreClient\Program.cs:line 34
```

What is the problem here?

**Comment by altnp** [comment]
Odd, here are my logs from a fresh clone, build, run.

```
PS C:\Users\Nick-PC\Desktop\grpc-dontnet-exception-reproduce> dotnet run --project coreserver
Greeter server listening on port 50052
Press any key to stop the server...
```

```
PS C:\Users\Nick-PC\Desktop\grpc-dontnet-exception-reproduce> dotnet run --project dotnetserver
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:50051
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\Nick-PC\Desktop\grpc-dontnet-exception-reproduce\dotnetserver
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST http://localhost:50051/Greet.Greeter/SayHello application/grpc
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - /Greet.Greeter/SayHello'
fail: DotNetServer.GreeterService[3]
      Error when executing service method 'SayHello'.
System.Exception: Example Exception!
   at DotNetServer.GreeterService.SayHello(HelloRequest request, ServerCallContext context) in C:\Users\Nick-PC\Desktop\grpc-dontnet-exception-reproduce\dotnetserver\Services\GreeterService.cs:line 14
   at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext)
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /Greet.Greeter/SayHello'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 94.37190000000001ms 200 application/grpc
```

```
PS C:\Users\Nick-PC\Desktop\grpc-dontnet-exception-reproduce> dotnet run --project coreclient
Invoking gRPC Core Server
Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Exception was thrown by handler.")
   at CoreClient.Program.Main(String[] args) in C:\Users\Nick-PC\Desktop\grpc-dontnet-exception-reproduce\coreclient\Program.cs:line 17
Invoking Asp.Net gRPC Server
Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="No status received")
   at CoreClient.Program.Main(String[] args) in C:\Users\Nick-PC\Desktop\grpc-dontnet-exception-reproduce\coreclient\Program.cs:line 34
```

Here is my dotnet info:

```
PS C:\Users\Nick-PC\Desktop\grpc-dontnet-exception-reproduce> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  2.2.201 [C:\Program Files\dotnet\sdk]
  3.0.100-preview5-011568 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

I did my first commit to the repo using package grpc-dotnet 1.20 rather than 1.21+. The issue is not present in 1.20, if you cloned the repo shortly after I created it that could be the issue.

**Comment by altnp** [comment]
Confirmed the issue exist on macOS as well, again using a clean clone/build/run. 

Here are the logs from my repo as well as dotnet info.

```grpc-dontnet-exception-reproduce [master]: dotnet run --project  coreclient
Invoking gRPC Core Server
Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Exception was thrown by handler.")
   at CoreClient.Program.Main(String[] args) in /Users/nalt/Desktop/grpc-dontnet-exception-reproduce/CoreClient/Program.cs:line 17
Invoking Asp.Net gRPC Server
Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="No status received")
   at CoreClient.Program.Main(String[] args) in /Users/nalt/Desktop/grpc-dontnet-exception-reproduce/CoreClient/Program.cs:line 34
```
```
grpc-dontnet-exception-reproduce [master]: dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview5-011568/

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.504 [/usr/local/share/dotnet/sdk]
  2.1.505 [/usr/local/share/dotnet/sdk]
  3.0.100-preview5-011568 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by JamesNK** [comment]
Preview 6 will be available soon. Lets wait until it + new versions of the package are on NuGet then retry to see whether it is still a problem.

**Comment by altnp** [comment]
Issue is resolved with SDK preview 6.

```
PS C:\Users\Nick-PC\Desktop\grpc-dontnet-exception-reproduce> dotnet run --project coreclient
Invoking gRPC Core Server
Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Exception was thrown by handler.")
   at CoreClient.Program.Main(String[] args) in C:\Users\Nick-PC\Desktop\grpc-dontnet-exception-reproduce\coreclient\Program.cs:line 17
Invoking Asp.Net gRPC Server
Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Exception was thrown by handler. Exception: Example Exception!")
   at CoreClient.Program.Main(String[] args) in C:\Users\Nick-PC\Desktop\grpc-dontnet-exception-reproduce\coreclient\Program.cs:line 34


```
