### ISSUE TITLE
ConnectionResetException when request finishes

### ISSUE THREAD

**Issue by KyleGobel** [grpc/grpc-dotnet#385]
I'm trying to make a few examples that include some authentication/authorization.

Anytime I add the authentication/authorization middleware, the server starts logging out SocketExceptions after each request

**example logs**
```
[08:39:22 DBG] Request matched endpoint 'gRPC - /RpcService/GetContactRules' 
[08:39:22 INF] Successfully validated the token. 
[08:39:22 DBG] AuthenticationScheme: Bearer was successfully authenticated.
[08:39:22 INF] Authorization was successful.
[08:39:22 INF] Executing endpoint 'gRPC - /RpcService/GetContactRules' 
[08:39:22 DBG] Connection id "0HLO60KMSRR8U", Request id "0HLO60KMSRR8U:00000003": started reading request body.
[08:39:22 DBG] Connection id "0HLO60KMSRR8U", Request id "0HLO60KMSRR8U:00000003": done reading request body.
[08:39:22 INF] Cleaning up 
[08:39:22 VRB] Connection id "0HLO60KMSRR8U" sending HEADERS frame for stream ID 3 with length 108 and flags END_HEADERS 
[08:39:22 VRB] Connection id "0HLO60KMSRR8U" sending DATA frame for stream ID 3 with length 9 and flags NONE 
[08:39:22 INF] Executed endpoint 'gRPC - /RpcService/GetContactRules'
[08:39:22 VRB] Connection id "0HLO60KMSRR8U" sending HEADERS frame for stream ID 3 with length 15 and flags END_STREAM, END_HEADERS
[08:39:22 INF] Request finished in 122.3816ms 200 application/grpc 
[08:39:22 DBG] Connection id "0HLO60KMSRR8U" reset. 
[08:39:22 INF] Connection id "0HLO60KMSRR8U" request processing ended abnormally.
Microsoft.AspNetCore.Connections.ConnectionResetException: An existing connection was forcibly closed by the remote host. 
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host. 
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketErro
r e)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application) 
[08:39:22 DBG] Connection id "0HLO60KMSRR8U" is closed. The last processed stream ID was 3.
[08:39:22 DBG] Connection id "0HLO60KMSRR8U" sending FIN because: "The client closed the connection."
[08:39:22 DBG] Connection id "0HLO60KMSRR8U" stopped. 
```

I get the proper response, I'm just not sure why that exception occurs on every request.

If I remove the authentication middleware it doesn't happen.

**Program.cs**
```csharp
    public class Program
    {
        public static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Verbose()
                .WriteTo.Console()
                .CreateLogger();

            BuildAndRun(args);
        }
        public static void BuildAndRun(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(builder =>
                {
                    builder.ConfigureAppConfiguration(config => { config.AddJsonFile("appsettings.json", false); });
                    builder.ConfigureServices(services =>
                    {
                        services
                            .AddAuthorization()
                            .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                            .AddJwtBearer(options =>
                            {
                                options.Authority = "<my identity server>";
                                options.TokenValidationParameters = new TokenValidationParameters
                                {
                                    ValidateAudience = false,
                                    ValidateIssuer = true,
                                    ValidateLifetime = true,
                                    ValidateActor = false
                                };
                            })
                            .Services
                            .AddGrpc(options => { options.EnableDetailedErrors = true; });
                    });
                    builder.Configure(app =>
                    {
                        app
                            .UseRouting()
                            .UseAuthentication()
                            .UseAuthorization()
                            .UseEndpoints(route =>
                            {
                                route.MapGrpcService<Services.NotificationService>();
                            });
                    });
                    builder.ConfigureKestrel(options =>
                    {
                        options.ListenAnyIP(50052,
                            listenOptions => { listenOptions.Protocols = HttpProtocols.Http2; });
                    });
                    builder.UseSerilog();
                })
                .Build().Run();
    }
```

**Test Code**
```csharp
[Fact]
public async Task Test1()
{
    AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);

    // create client
    var httpClient = new HttpClient { BaseAddress = new Uri("http://localhost:50052") };
    var client = GrpcClient.Create<RpcService.RpcServiceClient>(httpClient);

    // auth
    var token = "<identityserver token>";
    var callOptions = new CallOptions(new Metadata
    {
        {"Authorization", $"Bearer {token}"}
    });


    // test calls
    var response = await client.AddContactRuleAsync(new AddContactRuleRequest(), callOptions);
    var result = await client.GetContactRulesAsync(new GetContactRulesRequest
    {
        ContactRuleId = response.Id
    }, callOptions);

    
    result.ContactRules.Single().Id.Should().Be(response.Id);
}
```

More curious on why this happens, and if it's actually a problem.

**Comment by JamesNK** [comment]
I don't believe the error is from the authentication or authorization.

I think the error you see on the server is from the test application exiting which forcibly closes the HttpClient connection immediately after finishing the last call. An `await Task.Delay(1000)` at the end of your test would probably stop the ConnectionResetException.

Either way, it's not an error to worry about. The server is just reporting that a client didn't cleanly disconnect.
