### ISSUE TITLE
Is Grpc.AspNetCore server compatible with official gRPC (other language) clients?

### ISSUE THREAD

**Issue by PavelPZ** [grpc/grpc-dotnet#431]
I receive the exception when trying to call gRPC server (Microsoft.NETCore.App 3.0.0-preview7-27912-14, Grpc.AspNetCore 0.1.22-pre2) from following clients:
* Official version of gRPC DART client
* Official version of gRPC C# client

Other observations:
* Official clients (similar to above) for calling Google Cloud API (when insecure credential is replaced by google one) works well.
* New Grpc.Net.Client.GrpcClient (from GREETER examples) works fine.
* I cannot find any example regarding official gRPC client and new asp.net 3.0 gRCP server. It looks like the Grpc.AspNetCore.Server works just with Grpc.Net.Client.GrpcClient, which is not desired behavior.

# Official DART client

```
    import 'package:grpc/grpc.dart' as grpc;

    final channel= grpc.ClientChannel('localhost', port: 5001, 
        options: grpc.ChannelOptions(credentials: grpc.ChannelCredentials.insecure()));
    final cl = utils.GreeterClient(channel);
    var resp = await cl.sayHello(utils.HelloRequest()..name = 'Name from client');
```
raises error: **gRPC Error (2, HTTP/2 error: Connection error: Connection is being forcefully terminated. (errorCode: 10))**

# Official C# client 

I created simple repository on https://github.com/PavelPZ/GrcpError

Client code from repository is as follows:
```
      var channel = new Grpc.Core.Channel("localhost", 5001, Grpc.Core.ChannelCredentials.Insecure);
      var invoker = new Grpc.Core.DefaultCallInvoker(channel);
      var client = new GrpcServer.Greeter.GreeterClient(invoker);
      try {
        var res = client.SayHello(new GrpcServer.HelloRequest { Name = "Hello name" });
        Console.WriteLine(res.Message);
      } catch (Exception exp) {
        if (exp == null) return;
      }
```

and raises following error:

```
Grpc.Core.RpcException
  HResult=0x80131500
  Message=Status(StatusCode=Unknown, Detail="Stream removed")
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at GrpcServer.Greeter.GreeterClient.SayHello(HelloRequest request, CallOptions opti) in C:\Users\pavel\source\repos\GrpcServer\GrcpLib\obj\Debug\netcoreapp3.0\GreetGrpc.cs:line 84

```

**Comment by JamesNK** [comment]
Your client code to connect with Dart and Grpc.Core are both specifying the channel is insecure. That means it won't use HTTPS. By default Grpc.AspNetCore.Server and Grpc.Net.Client will use HTTPS.

You need to either change the server to not use HTTPS or change the clients to use it.

**Comment by PavelPZ** [comment]
Just a simple solution, thanks.

**Comment by ztl8702** [comment]
So how do I make the server use HTTP?

**Comment by ztl8702** [comment]
It turns out I need to do this on the server:
```csharp
.ConfigureKestrel(options =>
                    {
                        options.Listen(IPAddress.Any, 5001, listenOptions =>
                        {
                            listenOptions.Protocols = HttpProtocols.Http2;
                        });
                    });
```

(And I realised there is a different between "HTTP2 over insecure channel" and HTTP1)

**Comment by TomasWeg** [comment]
@JamesNK @PavelPZ @ztl8702 Hello. I know this is an old post, but I need a solution too. How can I turn off HTTPS on my server-side? I've something like @ztl8702 's one but it doesn't work. For my Dart client, I accept all certificates but I can't do it with my Golang client.

**Comment by ztl8702** [comment]
@TomasWeg here's my appsetting.json
```json
{ //...
  "Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "http://*:80",
        "Protocols": "Http1AndHttp2"
      },
      "HttpsCustomCert": {
        "Url": "https://*:443",
        "Certificate": {
          "Path": "/data/cert.pfx" 
        }
      }
    }
  }
}
```

and `Startup.cs`

```cs
public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddGrpc();
            services.AddControllers();
            services.AddCors(o => o.AddPolicy("AllowAll", builder =>
            {
                builder.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader().WithExposedHeaders(
                    "Grpc-Status", "Grpc-Message", "Grpc-Encoding", "Grpc-Accept-Encoding");
            }));
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseGrpcWeb(); // Must be between UseRouting and UseEndpoints.
            app.UseCors();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHealthChecks("/health");

                endpoints.MapGrpcService<YngdiengService>().EnableGrpcWeb().RequireCors("AllowAll");

                endpoints.MapControllers();

                endpoints.MapGet("/", async context =>
                {
                    await context.Response.WriteAsync(
                        "Communication with gRPC endpoints must be made through a gRPC client. ");
                });
            });
        }
    }
```
