### ISSUE TITLE
GPRC server/client test.

### ISSUE THREAD

**Issue by christophedemey** [grpc/grpc-dotnet#560]
Hi

I was following tutorials on microsoft documentation pages, everything worked except making the call itself, the error states :
```
Grpc.Core.RpcException: 'Status(StatusCode=Cancelled, Detail="Bad gRPC response. Expected HTTP status code 200. Got status code: 426")'
```
I guess this has something to do with the HTTP2.0 protocol ?
I have created a repository with my example code at : https://github.com/christophedemey/gprc

Any help is greatly appreciated.
Kind regards Christophe.

**Comment by JamesNK** [comment]
Are you running the app through Visual Studio? You might have IIS Express selected. It currently isn't supported

**Comment by christophedemey** [comment]
Hi, no i am using the in process host not iis.

**Comment by JamesNK** [comment]
Ok. That was the problem for the same error [here](https://github.com/grpc/grpc-dotnet/issues/526).

Retry and copy the logs from the server console here.

Or if it is simple, upload a repo to GitHub.

**Comment by christophedemey** [comment]
Hi @JamesNK 

The server output
```
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\christophe.de.mey\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
dbug: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[2]
      Discovering gRPC methods for WebApplication45.GreeterService.
dbug: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
      Added gRPC method 'SayHello' to service 'Greet.Greeter'. Method type: 'Unary', route pattern: '/Greet.Greeter/SayHello'.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\christophe.de.mey\Desktop\gprc\WebApplication45\WebApplication45
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST https://localhost:5001/Greet.Greeter/SayHello application/grpc
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - /Greet.Greeter/SayHello'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /Greet.Greeter/SayHello'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 75.9953ms 426
```
The client
```
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode=Cancelled, Detail="Bad gRPC response. Expected HTTP status code 200. Got status code: 426")
   at Grpc.Net.Client.Internal.GrpcCall`2.GetResponseAsync()
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\christophe.de.mey\Desktop\gprc\WebApplication45\ConsoleApp1\Program.cs:line 16
   at ConsoleApp1.Program.<Main>(String[] args)
```
The code used
https://github.com/christophedemey/gprc

Thanks

**Comment by JamesNK** [comment]
Your Kestrel server doesn't seem to accept HTTP/2 on that port. What is your operating system?

Explicitly specifying that the endpoint uses HTTP/2 in the server's `appsettings.json` may fix it.

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information"
    }
  },
  "AllowedHosts": "*",
  "Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http2"
    }
  }
}
```

**Comment by christophedemey** [comment]
Hi @JamesNK  other error output now.

Client
```
Grpc.Core.RpcException: 'Status(StatusCode=Cancelled, Detail="Bad gRPC response. Expected HTTP status code 200. Got status code: 504")'
```
Server
```
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\christophe.de.mey\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
dbug: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[2]
      Discovering gRPC methods for WebApplication45.GreeterService.
dbug: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
      Added gRPC method 'SayHello' to service 'Greet.Greeter'. Method type: 'Unary', route pattern: '/Greet.Greeter/SayHello'.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\christophe.de.mey\Desktop\gprc\WebApplication45\WebApplication45
fail: Microsoft.AspNetCore.Server.Kestrel[0]
      HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.
fail: Microsoft.AspNetCore.Server.Kestrel[0]
      HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.
```

**Comment by JamesNK** [comment]
Is the ASP.NET Core dev certificate installed and trusted?

https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0#call-a-grpc-service-with-an-untrustedinvalid-certificate

**Comment by JamesNK** [comment]
Or do you have a proxy running on your computer?

**Comment by christophedemey** [comment]
@JamesNK it was exactly that.

Fiddler was running on my PC.
I could now even remove this part 
```
  "AllowedHosts": "*",
  "Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http2"
    }
  }
```

And it still worked.
Thanks for your help!
