### ISSUE TITLE
System.InvalidOperationException: Error binding gRPC service

### ISSUE THREAD

**Issue by khteh** [grpc/grpc-dotnet#590]
### What version of gRPC and what language are you using?
2.23.2, C#

### What operating system (Linux, Windows,...) and version?
Ubuntu 19.04

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
```
$ dn --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.04
 OS Platform: Linux
 RID:         ubuntu.19.04-x64
 Base Path:   /usr/share/dotnet-3.0.100/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/usr/share/dotnet-3.0.100/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet-3.0.100/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet-3.0.100/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
I have the following .proto:
```
service Auth {
    rpc RefreshSignIn(RefreshSignInRequest) returns (RefreshSignInResponse);
}
message RefreshSignInRequest {
    Biz4x.Core.Grpc.User user = 1;
}
message RefreshSignInResponse {
    string id = 1;
    Biz4x.Core.Grpc.Response response = 2;
}
```
And I get the following runtime exception which I have no clue about:
```
15:18:33 [Fatal] () Application startup exception
System.InvalidOperationException: Error binding gRPC service 'AuthService'.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at System.Type.GetMethod(String name)
   at Grpc.AspNetCore.Server.Model.Internal.ProviderServiceBinder`1.CreateModelCore[TDelegate](String methodName)
   at Grpc.AspNetCore.Server.Model.Internal.ProviderServiceBinder`1.AddMethod[TRequest,TResponse](Method`2 method, UnaryServerMethod`2 handler)
   at Biz4x.Core.Auth.Auth.BindService(ServiceBinderBase serviceBinder, AuthBase serviceImpl) in /usr/src/4xlabs/identityservice/src/Biz4x.Core/obj/Debug/netcoreapp3.0/AuthGrpc.cs:line 88
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Grpc.AspNetCore.Server.Model.Internal.BinderServiceMethodProvider`1.OnServiceMethodDiscovery(ServiceMethodProviderContext`1 context)
   --- End of inner exception stack trace ---
   at Grpc.AspNetCore.Server.Model.Internal.BinderServiceMethodProvider`1.OnServiceMethodDiscovery(ServiceMethodProviderContext`1 context)
   at Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder`1.Build(IEndpointRouteBuilder endpointRouteBuilder)
   at Microsoft.AspNetCore.Builder.GrpcEndpointRouteBuilderExtensions.MapGrpcService[TService](IEndpointRouteBuilder builder)
   at Biz4x.API.Startup.<>c.<Configure>b__7_2(IEndpointRouteBuilder endpoints) in /usr/src/4xlabs/identityservice/src/Biz4x.API/Startup.cs:line 270
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at Biz4x.API.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IHostApplicationLifetime lifetime, IServiceProvider serviceProvider) in /usr/src/4xlabs/identityservice/src/Biz4x.API/Startup.cs:line 265
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
```
The exception happens in `Startup.cs`: `endpoints.MapGrpcService<AuthService>();`
### What did you expect to see?
No exception

### What did you see instead?
Exception
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc-dotnet/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by JamesNK** [comment]
Do you have another method named `RefreshSignIn` on `AuthService`? Try renaming it to something else to see if that fixes the error.

**Comment by khteh** [comment]
Yes, you are right. I have derived class `public class AuthService : Auth.AuthBase` and I missed out the `override` keyword in the function implementation.
