### ISSUE TITLE
Asp.net core 3.0 Grpc.AspNetCore.Server.ClientFactory Error

### ISSUE THREAD

**Issue by wuaries** [grpc/grpc-dotnet#626]
```
Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Error starting gRPC call: An error occurred while sending the request.")
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at GrpcService2.Chat.ChatClient.SendChat(ChatRequest request, CallOptions options) in C:\Users\Aries\Desktop\ConsoleApp3\ConsoleApp3\obj\Debug\netcoreapp3.0\ChatGrpc.cs:line 92
   at GrpcService2.Chat.ChatClient.SendChat(ChatRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in C:\Users\Aries\Desktop\ConsoleApp3\ConsoleApp3\obj\Debug\netcoreapp3.0\ChatGrpc.cs:line 88
   at WebApplication1.Controllers.TestController.GetName() in C:\Users\Aries\Desktop\ConsoleApp3\WebApplication1\Controllers\TestController.cs:line 25
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

HEADERS
=======
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrTmFtZSI6IuWPr-i-vum4rSIsImVtYWlsIjoiYWRtaW5AMTYzLmNvbSIsInVpZCI6IjB4MTAyNCIsImFwcENvZGUiOiIyMTQiLCJsb2dpblRpbWUiOiIyMDE5LTEwLTIyIDE2OjU1IiwiZXhwIjoxNTcxNzM4MTM2LCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xIiwiYXVkIjoiemh1cXVlIn0.-W__S8RuM2bvj8t6ZaqwEZQ0nhjX0pc0vE_dXPyosAY
Host: localhost:5000
User-Agent: PostmanRuntime/7.19.0
Content-Length: 249
Postman-Token: 605b5837-28b9-42e1-910c-a93a022f7a2a

Code:
```
   public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddGrpcClient<Chat.ChatClient>(o =>
            {
                o.Address = new Uri("http://192.168.1.109:5001");
            });
        }


 public class TestController : ControllerBase
    {
        private readonly Chat.ChatClient _c;

        public TestController(Chat.ChatClient client)
        {
            _c = client;
        }

        [HttpGet]
        public ActionResult GetName()
        {
            var a = _c.SendChat(new ChatRequest { Name = "test request....." });
            return Ok(a);
        }
    }
```

**Comment by JamesNK** [comment]
An error occured while sending the request. Increase your logging level - [instructions here](https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-3.0) - and then get more information from the error details in the logs.

**Comment by JamesNK** [comment]
Closing because there is no response. If this is still a problem add a comment here and this issue can be reopened.

**Comment by JulianBirch** [comment]
Not OP, but I have the same issue and did get a log:

```
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request)
```

I'm no wiser as to what the failure is, but at the very least the exception should contain this information in the InnerException field. Could we re-open this, please?

**Comment by Justin-Lessard** [comment]
Not the OP, but I'm able to reproduce. It's working fine using https but when I try over http, I get the same error.

    Exception thrown: 'Grpc.Core.RpcException' in System.Private.CoreLib.dll
    An unhandled exception of type 'Grpc.Core.RpcException' occurred in System.Private.CoreLib.dll
    Status(StatusCode=Internal, Detail="Error starting gRPC call: An error occurred while sending the request.")
	
There is nothing else in the debug logs. I'm able to access the RPC server without any issues using BloomRPC, so I also suspect Grpc.Net.Client is at fault.

I've looked at the wireshark capture of both a failed call using Grpc.Net.Client and here are the results.

No. | Time | Source | Destination | Protocol | Length | Info
-- | -- | -- | -- | -- | -- | --
1 | 0 | 192.168.0.161 | 172.17.131.244 | TCP | 66 | 5186  >  80 [SYN] Seq=0 Win=65535 Len=0 MSS=65495   WS=256 SACK_PERM=1
2 | 0.000497 | 172.17.131.244 | 192.168.0.161 | TCP | 66 | 80  >  5186 [SYN, ACK] Seq=0 Ack=1 Win=65535 Len=0   MSS=1460 WS=256 SACK_PERM=1
3 | 0.00056 | 192.168.0.161 | 172.17.131.244 | TCP | 54 | 5186  >  80 [ACK] Seq=1 Ack=1 Win=2102272 Len=0
4 | 0.055721 | 192.168.0.161 | 172.17.131.244 | TCP | 339 | 5186  >  80 [PSH, ACK] Seq=1 Ack=1 Win=2102272   Len=285 [TCP segment of a reassembled PDU]
5 | 0.05687 | 192.168.0.161 | 172.17.131.244 | TCP | 59 | [TCP segment of a reassembled PDU]
6 | 0.057291 | 172.17.131.244 | 192.168.0.161 | TCP | 54 | 80  >  5186 [ACK] Seq=1 Ack=291 Win=2102272 Len=0
7 | 0.058108 | 172.17.131.244 | 192.168.0.161 | HTTP2 | 71 | GOAWAY[0]
8 | 0.058161 | 192.168.0.161 | 172.17.131.244 | TCP | 54 | 5186  >  80 [ACK] Seq=291 Ack=18 Win=2102272 Len=0
9 | 0.058282 | 172.17.131.244 | 192.168.0.161 | TCP | 54 | 80  >  5186 [FIN, ACK] Seq=18 Ack=291 Win=2102272   Len=0
10 | 0.058314 | 192.168.0.161 | 172.17.131.244 | TCP | 54 | 5186  >  80 [ACK] Seq=291 Ack=19 Win=2102272 Len=0
11 | 0.074949 | 192.168.0.161 | 172.17.131.244 | TCP | 54 | 5186  >  80 [FIN, ACK] Seq=291 Ack=19 Win=2102272   Len=0
12 | 0.075183 | 172.17.131.244 | 192.168.0.161 | TCP | 54 | 80  >  5186 [ACK] Seq=19 Ack=292 Win=2102272 Len=0

It's not really my area of expertise, but it looks like the client never initiate communication using HTTP2 and GRPC after the initial TCP handshake. The client just send the whole message over TCP and is rejected by the server.

**Comment by Justin-Lessard** [comment]
I've found [a workaround](https://stackoverflow.com/questions/58682933/how-do-i-enable-http2-in-c-sharp-kestrel-web-server-over-plain-http) for now.

Setting this flag inside the client seems to make it work.

    AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);

**Comment by JulianBirch** [comment]
I wish I'd found that before I recoded the whole thing to use the Google client... (which works)

**Comment by JamesNK** [comment]
This is discussed here - https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0#call-a-grpc-service-with-an-untrustedinvalid-certificate

This will be done for you in .NET 5, but for now you must set that flag.
