### ISSUE TITLE
certifier example not working

### ISSUE THREAD

**Issue by ironpython2001** [grpc/grpc-dotnet#672]
The example certifier is not working .Please update the correct code or with some instructions
https://github.com/grpc/grpc-dotnet/tree/master/examples/Certifier

once we start the server and run the client got the below error 
*******************************************************************
Setting up HttpClient. Client has certificate: False
Sending gRPC call...
gRPC error from calling service: Error starting gRPC call: The SSL connection could not be established, see inner exception.
Setting up HttpClient. Client has certificate: True
Sending gRPC call...
**gRPC error from calling service: Error starting gRPC call: The SSL connection could not be established, see inner exception.**
Press any key to exit...

**Comment by JamesNK** [comment]
You can get more information about the error by configuring client logging - https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-3.0#grpc-client-logging

My guess is you haven't trusted the development certificate - https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0#call-a-grpc-service-with-an-untrustedinvalid-certificate

**Comment by ironpython2001** [comment]
i trusted the development certificate and i got the below error .enabled logging

dbug: Grpc.Net.Client.Internal.GrpcCall[1]
      Starting gRPC call. Method type: 'Unary', URI: 'https://localhost:5001/xxxx/yyyy'.
dbug: Grpc.Net.Client.Internal.GrpcCall[18]
      Sending message.
fail: Grpc.Net.Client.Internal.GrpcCall[20]
      Error sending message.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.Http2Connection.AcquireWriteLockAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.StartWriteAsync(Int32 writeBytes, CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendStreamDataAsync(Int32 streamId, ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.Http2Stream.SendDataAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at Grpc.Net.Client.StreamExtensions.WriteMessageAsync[TMessage](Stream stream, ILogger logger, TMessage message, Action`2 serializer, String grpcEncoding, Nullable`1 maximumMessageSize, Dictionary`2 compressionProviders, CallOptions callOptions)
fail: Grpc.Net.Client.Internal.GrpcCall[6]
      Error starting gRPC call.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.Http2Connection.AcquireWriteLockAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.StartWriteAsync(Int32 writeBytes, CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendStreamDataAsync(Int32 streamId, ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.Http2Stream.SendDataAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at Grpc.Net.Client.StreamExtensions.WriteMessageAsync[TMessage](Stream stream, ILogger logger, TMessage message, Action`2 serializer, String grpcEncoding, Nullable`1 maximumMessageSize, Dictionary`2 compressionProviders, CallOptions callOptions)
   at Grpc.Net.Client.Internal.PushUnaryContent`2.WriteMessageCore(ValueTask writeMessageTask)
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   at System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request)
Error while RedeemToken : Status(StatusCode=Cancelled, Detail="")
dbugWould you like to Continue with other Request [y/n] : Grpc.Net.Client.Internal.GrpcCall[8]
      gRPC call canceled.
fail: Grpc.Net.Client.Internal.GrpcCall[3]
      Call failed with gRPC error status. Status code: 'Cancelled', Message: ''.
dbug: Grpc.Net.Client.Internal.GrpcCall[4]
      Finished gRPC call.

**Comment by ironpython2001** [comment]
[Certifier.zip](https://github.com/grpc/grpc-dotnet/files/3911390/Certifier.zip)
please find the attached code

**Comment by JamesNK** [comment]
So the previous cert had expired. I have a PR to update it here: https://github.com/grpc/grpc-dotnet/pull/676

I tried the app with your new certificate and saw that the client wasn't sending the cert to the server. A cert needs to have the right encryption and usage flags to be sent by HttpClient. See https://github.com/dotnet/corefx/issues/30483 for more details.

You could retry with the cert from my PR.

**Comment by ironpython2001** [comment]
[Certifier.zip](https://github.com/grpc/grpc-dotnet/files/3915377/Certifier.zip)
[grpc certificate error.docx](https://github.com/grpc/grpc-dotnet/files/3915378/grpc.certificate.error.docx)
The issue is not resolved. Please find the attached word document and the code. Still i am getting the same error . Please let me know if i am missing some step.

**Comment by JamesNK** [comment]
Ah, the new cert isn't chained so the example server isn't allowing it. You can see that in the logs. It is just a matter of configuring the certificate authentication to allow self-signed certificates:

In Startup.cs:

```cs
.AddCertificate(options =>
{
    // Not recommended in production environments. The example is using a self-signed test certificate.
    options.RevocationMode = X509RevocationMode.NoCheck;
    options.AllowedCertificateTypes = CertificateTypes.All;
});
```

**Comment by ironpython2001** [comment]
[Certifier.zip](https://github.com/grpc/grpc-dotnet/files/3916132/Certifier.zip)
It was working by modifying your code 
added the above mentioned lines in server  options.AllowedCertificateTypes = CertificateTypes.All;
 added the following lines  in client
handler.ClientCertificateOptions = ClientCertificateOption.Manual;
handler.SslProtocols = SslProtocols.Tls12;
Please find the attached zip 
I am not sure about the exact reason for this. 
I personally feel the documentation should be proper and step by step as this sort of authentication is used by many people in grpc services.

**Comment by JamesNK** [comment]
I think ClientCertificateOption.Manual is already the default option.

I don't know why you need SslProtocols.Tls12. It works for me without it.

**Comment by ironpython2001** [comment]
I added the same example with the code fix in this github location. So that people can use this.
[asp.net-core-grpc-certificate-authentication](https://github.com/ironpython2001/asp.net-core-grpc-certificate-authentication)
