### ISSUE TITLE
Big header values cause client-side "Error starting gRPC call: An error occurred while sending the request"

### ISSUE THREAD

**Issue by nyjl** [grpc/grpc-dotnet#696]
### What version of gRPC and what language are you using?
Grpc.AspNetCore 2.25.0

### What operating system (Linux, Windows,...) and version?
MacOS, same on Ubuntu 18.04

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

### What did you do?
Trying to send big header values causes RpcException
You need any grpc-server, client is generated from proto. Programmaticaly add a big header value to metadata.
```csharp
var req = new BatchingProcessGetRequest
            {
                    Id = 1
                };
var meta = new Metadata();
meta.Add("test",        "segesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegsegesggsesegsgsegesgsegsegse");
var res = _client.BatchingProcessGet(req, meta);
```

### What did you expect to see?
Request should finish normally.

### What did you see instead?
RpcException
```
Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Error starting gRPC call: An error occurred while sending the request.")
  at at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
  at at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
  at at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
  at at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
  at Settings.SettingsClient.BatchingProcessGet(BatchingProcessGetRequest request, CallOptions options) in /Users/vkonyaev/wmscli/GrpcService1/GrpcService1/obj/Debug/netcoreapp3.1/SettingsGrpc.cs:1954
  at Settings.SettingsClient.BatchingProcessGet(BatchingProcessGetRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in /Users/vkonyaev/wmscli/GrpcService1/GrpcService1/obj/Debug/netcoreapp3.1/SettingsGrpc.cs:1950
  at GrpcService1.GreeterService.SayHello(HelloRequest request, ServerCallContext context) in /Users/vkonyaev/wmscli/GrpcService1/GrpcService1/Services/GreeterService.cs:30
  at at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
```

debug grpc logs
```
dbug: Grpc.Net.Client.Internal.GrpcCall[1]
      Starting gRPC call. Method type: 'Unary', URI: 'http://xxx:82/Settings/BatchingProcessGet'.
info: System.Net.Http.HttpClient.SettingsClient.LogicalHandler[100]
      Start processing HTTP request POST http://xxx:82/Settings/BatchingProcessGet
info: System.Net.Http.HttpClient.SettingsClient.ClientHandler[100]
      Sending HTTP request POST http://xxx:82/Settings/BatchingProcessGet
dbug: Grpc.Net.Client.Internal.GrpcCall[18]
      Sending message.
fail: Grpc.Net.Client.Internal.GrpcCall[6]
      Error starting gRPC call.
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The request was aborted.
 ---> System.IO.IOException: The response ended prematurely, with at least 9 additional bytes expected.
   at System.Net.Http.Http2Connection.ReadAtLeastAsync(Stream stream, Memory`1 buffer, Int32 minReadBytes)
   at System.Net.Http.Http2Connection.EnsureIncomingBytesAsync(Int32 minReadBytes)
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request)
```

### Anything else we should know about your project / environment?
We have tls disable switch on client side.
```csharp
AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
```
Although we were able to reproduce it on ubuntu without this switch.

**Comment by JamesNK** [comment]
I created a test that sends this header and didn't get this error.

> The response ended prematurely, with at least 9 additional bytes expected.

This error using occurs when there is a mismatch between TLS settings on the client and server. You should double check the server settings for this port. Also look at the server logs.

**Comment by nyjl** [comment]
I guess you are right, i tried it on helloworld server locally and it works.

Still i dont understand why this problem only shows with big header values, since if you trim  it in half it still works.

**Comment by JamesNK** [comment]
Perhaps there is a proxy in between the calling client and Kestrel that rejects large headers.

It's not a problem in the gRPC library.

**Comment by JohannSig** [comment]
> I guess you are right, i tried it on helloworld server locally and it works.
> 
> Still i dont understand why this problem only shows with big header values, since if you trim it in half it still works.

@nyjl How do you trim your header values?
