### ISSUE TITLE
Set Server and client without TLS , Client throws error when call server

### ISSUE THREAD

**Issue by dingsongjie** [grpc/grpc-dotnet#707]
I write a demo from [aspnetcore-3.1-client](https://docs.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-3.1) . And I replace https to http , client throws error when call server. But when I use  BloomRPC to test the server , it works fine .

errors
```log
Status(StatusCode=Internal, Detail="Error starting gRPC call: An error occurred while sending the request.")

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Client.Program.<UnaryCallExample>d__1.MoveNext() in D:\Repos\grpc-dotnet\examples\Greeter\Client\Program.cs:line 46
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Client.Program.<Main>d__0.MoveNext() in D:\Repos\grpc-dotnet\examples\Greeter\Client\Program.cs:line 35
```

**Comment by JamesNK** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.1#call-insecure-grpc-services-with-net-core-client

**Comment by dingsongjie** [comment]
> See https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.1#call-insecure-grpc-services-with-net-core-client

Thanks for help
