### ISSUE TITLE
Where is the simple project including javascript client and aspnetcore grpc-web

### ISSUE THREAD

**Issue by dingsongjie** [grpc/grpc-dotnet#800]
I built an aspnetcore grpc project and added grpc-web. I access this service through the react app and I get the following error
```log
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2ConnectionErrorException: HTTP/2 connection error (PROTOCOL_ERROR): Invalid HTTP/2 connection preface.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ParsePreface(ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.TryReadPrefaceAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
```

Can anyone give me a simple project including javascript client and aspnetcore grpc web? 
Thanks!

**Comment by JamesNK** [comment]
https://github.com/grpc/grpc-dotnet/tree/master/examples

**Comment by dingsongjie** [comment]
Thanks for help
