### ISSUE TITLE
Client Streaming Calls are Mysteriously Canceled

### ISSUE THREAD

**Issue by thefringeninja** [grpc/grpc-dotnet#811]
### What version of gRPC and what language are you using?
`2.28.0-pre1`

### What operating system (Linux, Windows,...) and version?
```
uname --kernel-version --kernel-release
5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020
```

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
`3.1.102`

### What did you do?
This seems to be happening with streaming calls. We will send some exception information down as trailers. On the client side, we look for these and wrap the rpc exception with our own exception in an interceptor.

Upgrading to `Microsoft.AspNetCore.TestHost Version="3.1.2"` did not help.

### What did you expect to see?
Our exception.

### What did you see instead?
We do in fact see our exception going over the wire and noted by grpc:
```
Error status code 'Aborted' raised.

Grpc.Core.RpcException: Status(StatusCode=Aborted, Detail="Subscription group existing on stream update_existing_with_subscribers was dropped.")
   at EventStore.Core.Services.Transport.Grpc.PersistentSubscriptions.PersistentStreamSubscriptionEnumerator.MoveNextAsync()
   at EventStore.Core.Services.Transport.Grpc.PersistentSubscriptions.Read(IAsyncStreamReader`1 requestStream, IServerStreamWriter`1 responseStream, ServerCallContext context) in /home/jwow/dev/EventStore/src/EventStore.Core/Services/Transport/Grpc/PersistentSubscriptions.Read.cs:line 61
   at EventStore.Core.Services.Transport.Grpc.PersistentSubscriptions.Read(IAsyncStreamReader`1 requestStream, IServerStreamWriter`1 responseStream, ServerCallContext context) in /home/jwow/dev/EventStore/src/EventStore.Core/Services/Transport/Grpc/PersistentSubscriptions.Read.cs:line 61
   at EventStore.Core.Services.Transport.Grpc.PersistentSubscriptions.Read(IAsyncStreamReader`1 requestStream, IServerStreamWriter`1 responseStream, ServerCallContext context) in /home/jwow/dev/EventStore/src/EventStore.Core/Services/Transport/Grpc/PersistentSubscriptions.Read.cs:line 30
   at Grpc.Shared.Server.DuplexStreamingServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, IAsyncStreamReader`1 requestStream, IServerStreamWriter`1 responseStream)
   at Grpc.Shared.Server.DuplexStreamingServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, IAsyncStreamReader`1 requestStream, IServerStreamWriter`1 responseStream)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
```
However this gets swallowed and replaced with `Cancelled`:
```
Call failed with gRPC error status. Status code: 'Cancelled', Message: 'gRPC call disposed.'.
```

Below are our structured logs for the failed test runs.
[export-8d7c1bbfea4dec4.clef.log](https://github.com/grpc/grpc-dotnet/files/4297933/export-8d7c1bbfea4dec4.clef.log)

### Anything else we should know about your project / environment?
https://github.com/EventStore/EventStore/pull/2303

**Comment by thefringeninja** [comment]
We dug into this and found out more information. A call to `RequestStream.WriteAsync` or `RequestStream.CompleteAsync` will produce `gRPC call disposed`, as the real exception has already occurred, then we get the real exception on a call to `ResponseAsync`:

EventStore/EventStore#2348

**Comment by JunTaoLuo** [comment]
Looks like you found the solution. We expect the trailers with the exception information to be available via the response stream but not the request stream. Please feel free to re-open if you have further questions or comments.
