### ISSUE TITLE
several interop tests failing against grpc-java client

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-dotnet#97]
Context: Most interop test pass when grpc-go or c-based library is used, but when grpc-java is used, there seems to be some problem.

E.g.:
```
~/github/grpc-java$ ./run-test-client.sh --server_host=localhost --server_port=50052 --test_case=large_unary --use_tls=false
```

Results in
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLKJ9F9LRHFI", Request id "0HLKJ9F9LRHFI:00000003": An unhandled exception was thrown by the application.
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Grpc.AspNetCore.Server.Internal.HttpContextServerCallContext.get_RequestHeadersCore() in /usr/local/google/home/jtattermusch/github/grpc-dotnet/src/Grpc.AspNetCore.Server/Internal/HttpContextServerCallContext.cs:line 95
   at Grpc.Core.ServerCallContext.get_RequestHeaders()
   at Grpc.Testing.TestServiceImpl.EnsureEchoMetadataAsync(ServerCallContext context) in /usr/local/google/home/jtattermusch/github/grpc-dotnet/testassets/InteropTestsWebsite/TestServiceImpl.cs:line 99
   at Grpc.Testing.TestServiceImpl.UnaryCall(SimpleRequest request, ServerCallContext context) in /usr/local/google/home/jtattermusch/github/grpc-dotnet/testassets/InteropTestsWebsite/TestServiceImpl.cs:line 40
   at Grpc.AspNetCore.Server.Internal.UnaryServerCallHandler`3.HandleCallAsync(HttpContext httpContext) in /usr/local/google/home/jtattermusch/github/grpc-dotnet/src/Grpc.AspNetCore.Server/Internal/UnaryServerCallHandler.cs:line 70
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 146.9647ms 500 
```

Likely some base64 encoding problem is at fault.

**Comment by jtattermusch** [comment]
The header sent by grpc-java is:
`grpc-trace-bin: AADQA7MnHnYTan7LCInL3K+EAfkpLdnnVVO1AgA` and `Convert.FromBase64String` fails with it. Problem with base64 padding?

**Comment by jtattermusch** [comment]
From https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

> Note that HTTP2 does not allow arbitrary octet sequences for header values so binary header values must be encoded using Base64 as per https://tools.ietf.org/html/rfc4648#section-4. Implementations MUST accept padded and un-padded values and should emit un-padded values.

Looks like we are failing to accept unpadded values for binary headers.

@JamesNK  @JunTaoLuo

**Comment by JamesNK** [comment]
> and should emit un-padded values

to do?

**Comment by JunTaoLuo** [comment]
Hmmm it says "should" which isn't a hard "must". Are the unpadded values there to improve efficiency to reduce the number of bytes sent over the wire? I'm not sure it improves efficiency given the pre and post processing we need to do.

**Comment by jtattermusch** [comment]
It looks like the interop problem has been fixed by https://github.com/grpc/grpc-dotnet/pull/98,
but currently the base64 parsing doesn't seem very efficient (extra string concatenation), so we should probably revisit the performance side of it at some point.

Passing interop tests againts grpc-java: 
https://source.cloud.google.com/results/invocations/89f6c1c8-4183-44c3-9dd9-5dba629d4d1e/targets/github%2Fgrpc%2Finterop_test/tests;query=java:aspnetcore;failed=false;passed=true;group=tests;test=cloud_to_cloud:node:aspnetcore_server:large_unary:tls;row=4
